package net.dungeonhub.hypixel.entities.inventory.items

//TODO load enum from SB endpoint? -> not possible really, only maybe as a test?
//TODO maybe add an item type to easier get the item class
enum class KnownSkyblockItemId(override val apiName: String, val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    SkyblockItemId {
    //Accessory

    //Admin Item

    //Armor
    ExceedinglyComfySneakers("EXCEEDINGLY_COMFY_SNEAKERS", { Armor(it.raw) }),
    FarmerBoots("FARMER_BOOTS", { Armor(it.raw) }),
    GhostlyBoots("GHOST_BOOTS", { Armor(it.raw) }),
    GunthersSneakers("GUNTHER_SNEAKERS", { Armor(it.raw) }),
    RanchersBoots("RANCHERS_BOOTS", { Armor(it.raw) }),
    SlugBoots("SLUG_BOOTS", { Armor(it.raw) }),
    SnakeInABoot("SNAKE_IN_A_BOOT", { Armor(it.raw) }),
    SpidersBoots("SPIDER_BOOTS", { Armor(it.raw) }),
    SpiritBoots("THORNS_BOOTS", { Armor(it.raw) }),
    SpringBoots("SPRING_BOOTS", { Armor(it.raw) }),
    SquidBoots("SQUID_BOOTS", { Armor(it.raw) }),
    UglyBoots("UGLY_BOOTS", { Armor(it.raw) }),
    EtalptsehCnorI("ETALPTSEHC_NORI", { Armor(it.raw) }),
    FlamingChestplate("FLAMING_CHESTPLATE", { Armor(it.raw) }),
    GuardianChestplate("GUARDIAN_CHESTPLATE", { Armor(it.raw) }),
    LivelySepultureChestplate("LIVELY_SEPULTURE_CHESTPLATE", { Armor(it.raw) }),
    MetalChestplate("METAL_CHESTPLATE", { Armor(it.raw) }),
    MithrilCoat("MITHRIL_COAT", { Armor(it.raw) }),
    ObsidianChestplate("OBSIDIAN_CHESTPLATE", { Armor(it.raw) }),
    OrangeChestplate("ORANGE_CHESTPLATE", { Armor(it.raw) }),
    ShimmersparkleChestplate("SHIMMERSPARKLE_CHESTPLATE", { Armor(it.raw) }),
    SteelChestplate("STEEL_CHESTPLATE", { Armor(it.raw) }),
    StoneChestplate("STONE_CHESTPLATE", { Armor(it.raw) }),
    WLogo("S_LOGO_CHESTPLATE", { Armor(it.raw) }),
    BurnedPants("BURNED_PANTS", { Armor(it.raw) }),
    ChickenLeggs("CHICKEN_LEGGS", { Armor(it.raw) }),
    CreeperPants("CREEPER_LEGGINGS", { Armor(it.raw) }),
    FemurgrowthLeggings("FEMURGROWTH_LEGGINGS", { Armor(it.raw) }),
    LeggingsOfTheCoven("LEGGINGS_OF_THE_COVEN", { Armor(it.raw) }),
    MoogmaLeggings("MOOGMA_LEGGINGS", { Armor(it.raw) }),
    StereoPants("MUSIC_PANTS", { Armor(it.raw) }),
    WizardmanLeggings("WIZARDMAN_LEGGINGS", { Armor(it.raw) }),
    ArmadilloMask("ARMADILLO_MASK", { Armor(it.raw) }),
    BeeMask("BEE_MASK", { Armor(it.raw) }),
    FrogMask("FROG_MASK", { Armor(it.raw) }),
    ParrotMask("PARROT_MASK", { Armor(it.raw) }),
    SalmonMask("SALMON_MASK", { Armor(it.raw) }),
    SnowmanMask("SNOWMAN_MASK", { Armor(it.raw) }),
    ZombieMask("ZOMBIE_MASK", { Armor(it.raw) }),
    AgaricusCapCap("AGARICUS_CAP_CAP", { Armor(it.raw) }),
    AntiBiteScarf("ANTI_BITE_SCARF", { Armor(it.raw) }),
    BlazeHat("BLAZE_HAT", { Armor(it.raw) }),
    BlobfishHat("BLOBFISH_HAT", { Armor(it.raw) }),
    BonzosMask("BONZO_MASK", { Armor(it.raw) }),
    ChickenHat("CHICKEN_HEAD", { Armor(it.raw) }),
    CloverHelmet("CLOVER_HELMET", { Armor(it.raw) }),
    ClownfishHat("CLOWNFISH_HAT", { Armor(it.raw) }),
    CowHat("COW_HEAD", { Armor(it.raw) }),
    CreeperHat("CREEPER_HAT", { Armor(it.raw) }),
    CrownOfAvarice("CROWN_OF_AVARICE", { Armor(it.raw) }),
    CrownOfGreed("CROWN_OF_GREED", { Armor(it.raw) }),
    CrystallizedHeart("CRYSTALLIZED_HEART", { Armor(it.raw) }),
    DarkGoggles("DARK_GOGGLES", { Armor(it.raw) }),
    DiamondBonzoHead("DIAMOND_BONZO_HEAD", { Armor(it.raw) }),
    DiamondLividHead("DIAMOND_LIVID_HEAD", { Armor(it.raw) }),
    DiamondNecronHead("DIAMOND_NECRON_HEAD", { Armor(it.raw) }),
    DiamondProfessorHead("DIAMOND_PROFESSOR_HEAD", { Armor(it.raw) }),
    DiamondSadanHead("DIAMOND_SADAN_HEAD", { Armor(it.raw) }),
    DiamondScarfHead("DIAMOND_SCARF_HEAD", { Armor(it.raw) }),
    DiamondThornHead("DIAMOND_THORN_HEAD", { Armor(it.raw) }),
    EndermanMask("ENDERMAN_MASK", { Armor(it.raw) }),
    FallenStarHelmet("FALLEN_STAR_HAT", { Armor(it.raw) }),
    FishHat("FISH_HAT", { Armor(it.raw) }),
    FlexHelmet("FLEX_HELMET", { Armor(it.raw) }),
    GhastHead("GHAST_HEAD", { Armor(it.raw) }),
    GoldenBonzoHead("GOLD_BONZO_HEAD", { Armor(it.raw) }),
    GoldenLividHead("GOLD_LIVID_HEAD", { Armor(it.raw) }),
    GoldenNecronHead("GOLD_NECRON_HEAD", { Armor(it.raw) }),
    GoldenProfessorHead("GOLD_PROFESSOR_HEAD", { Armor(it.raw) }),
    GoldenSadanHead("GOLD_SADAN_HEAD", { Armor(it.raw) }),
    GoldenScarfHead("GOLD_SCARF_HEAD", { Armor(it.raw) }),
    GoldenThornHead("GOLD_THORN_HEAD", { Armor(it.raw) }),
    GolemHat("GOLEM_HAT", { Armor(it.raw) }),
    HappyMask("HAPPY_MASK", { Armor(it.raw) }),
    HeadOfBetrayal("BETRAYAL_HEAD", { Armor(it.raw) }),
    KalhuikiMask("KALHUIKI_MASK", { Armor(it.raw) }),
    KrampusHelmet("KRAMPUS_HELMET", { Armor(it.raw) }),
    LanternHelmet("ENCHANTED_JACK_O_LANTERN", { Armor(it.raw) }),
    MagmaCubeHead("MAGMA_CUBE_HEAD", { Armor(it.raw) }),
    MagmafishHat("MAGMA_FISH_HAT", { Armor(it.raw) }),
    MenderCrown("MENDER_CROWN", { Armor(it.raw) }),
    MenderFedora("MENDER_FEDORA", { Armor(it.raw) }),
    MenderHelmet("MENDER_HELMET", { Armor(it.raw) }),
    NotDeadGehogMask("NOT_DEADGEHOG_MASK", { Armor(it.raw) }),
    PartyTopHat("PARTY_HAT", { Armor(it.raw) }),
    PigMask("PIG_MASK", { Armor(it.raw) }),
    PotatoCrown("POTATO_CROWN", { Armor(it.raw) }),
    PrecursorEye("PRECURSOR_EYE", { Armor(it.raw) }),
    PufferfishHat("PUFFERFISH_HAT", { Armor(it.raw) }),
    RabbitHat("RABBIT_HAT", { Armor(it.raw) }),
    ReaperMask("REAPER_MASK", { Armor(it.raw) }),
    RetroEncabulatingVisor("RETRO_ENCABULATING_VISOR", { Armor(it.raw) }),
    RevivedHeart("REVIVED_HEART", { Armor(it.raw) }),
    RacingHelmet("RACING_HELMET", { Armor(it.raw) }),
    SalmonHat("SALMON_HAT", { Armor(it.raw) }),
    SeaLanternHat("SEA_LANTERN_HAT", { Armor(it.raw) }),
    ShadowGoggles("SHADOW_GOGGLES", { Armor(it.raw) }),
    SkeletonHat("SKELETON_HAT", { Armor(it.raw) }),
    SkeletonsHelmet("SKELETON_HELMET", { Armor(it.raw) }),
    SlimeHat("SLIME_HAT", { Armor(it.raw) }),
    SniperHelmet("SNIPER_HELMET", { Armor(it.raw) }),
    SpaceHelmet("DCTR_SPACE_HELM", { Armor(it.raw) }),
    SpiderHat("SPIDER_HAT", { Armor(it.raw) }),
    SpiritMask("SPIRIT_MASK", { Armor(it.raw) }),
    SquidHat("SQUID_HAT", { Armor(it.raw) }),
    TaurusHelmet("TAURUS_HELMET", { Armor(it.raw) }),
    TheBuildersClay("DUECES_BUILDER_CLAY", { Armor(it.raw) }),
    UsedDetransfiguredFace("DETRANSFIGURED_MASK", { Armor(it.raw) }),
    VampireMask("VAMPIRE_MASK", { Armor(it.raw) }),
    VampireWitchMask("VAMPIRE_WITCH_MASK", { Armor(it.raw) }),
    WardenHelmet("WARDEN_HELMET", { Armor(it.raw) }),
    WarmWizardFace("WARM_WIZARD_FACE", { Armor(it.raw) }),
    WarmerWizardFace("WARM_WIZARD_FACE_2", { Armor(it.raw) }),
    WaterHydraHead("WATER_HYDRA_HEAD", { Armor(it.raw) }),
    WitchMask("WITCH_MASK", { Armor(it.raw) }),
    WitherGoggles("WITHER_GOGGLES", { Armor(it.raw) }),
    WizardFace("WIZARD_FACE", { Armor(it.raw) }),
    ZombieHat("ZOMBIE_HAT", { Armor(it.raw) }),
    ZombiesHeart("ZOMBIE_HEART", { Armor(it.raw) }),
    AdaptiveHelmet("ADAPTIVE_HELMET", { Armor(it.raw) }),
    AdaptiveChestplate("ADAPTIVE_CHESTPLATE", { Armor(it.raw) }),
    AdaptiveLeggings("ADAPTIVE_LEGGINGS", { Armor(it.raw) }),
    AdaptiveBoots("ADAPTIVE_BOOTS", { Armor(it.raw) }),
    UpgradedAdaptiveHelmet("STARRED_ADAPTIVE_HELMET", { Armor(it.raw) }),
    UpgradedAdaptiveChestplate("STARRED_ADAPTIVE_CHESTPLATE", { Armor(it.raw) }),
    UpgradedAdaptiveLeggings("STARRED_ADAPTIVE_LEGGINGS", { Armor(it.raw) }),
    UpgradedAdaptiveBoots("STARRED_ADAPTIVE_BOOTS", { Armor(it.raw) }),
    AnglerHelmet("ANGLER_HELMET", { Armor(it.raw) }),
    AnglerChestplate("ANGLER_CHESTPLATE", { Armor(it.raw) }),
    AnglerLeggings("ANGLER_LEGGINGS", { Armor(it.raw) }),
    AnglerBoots("ANGLER_BOOTS", { Armor(it.raw) }),
    ArachnesHelmet("ARACHNE_HELMET", { Armor(it.raw) }),
    ArachnesChestplate("ARACHNE_CHESTPLATE", { Armor(it.raw) }),
    ArachnesLeggings("ARACHNE_LEGGINGS", { Armor(it.raw) }),
    ArachnesBoots("ARACHNE_BOOTS", { Armor(it.raw) }),
    HelmetOfDivan("DIVAN_HELMET", { Armor(it.raw) }),
    ChestplateOfDivan("DIVAN_CHESTPLATE", { Armor(it.raw) }),
    LeggingsOfDivan("DIVAN_LEGGINGS", { Armor(it.raw) }),
    BootsOfDivan("DIVAN_BOOTS", { Armor(it.raw) }),
    HelmetOfGrowth("GROWTH_HELMET", { Armor(it.raw) }),
    ChestplateOfGrowth("GROWTH_CHESTPLATE", { Armor(it.raw) }),
    LeggingsOfGrowth("GROWTH_LEGGINGS", { Armor(it.raw) }),
    BootsOfGrowth("GROWTH_BOOTS", { Armor(it.raw) }),
    ArmorOfMagmaHelmet("ARMOR_OF_MAGMA_HELMET", { Armor(it.raw) }),
    ArmorOfMagmaChestplate("ARMOR_OF_MAGMA_CHESTPLATE", { Armor(it.raw) }),
    ArmorOfMagmaLeggings("ARMOR_OF_MAGMA_LEGGINGS", { Armor(it.raw) }),
    ArmorOfMagmaBoots("ARMOR_OF_MAGMA_BOOTS", { Armor(it.raw) }),
    HelmetOfThePack("HELMET_OF_THE_PACK", { Armor(it.raw) }),
    ChestplateOfThePack("CHESTPLATE_OF_THE_PACK", { Armor(it.raw) }),
    LeggingsOfThePack("LEGGINGS_OF_THE_PACK", { Armor(it.raw) }),
    BootsOfThePack("BOOTS_OF_THE_PACK", { Armor(it.raw) }),

    //Brewing Ingredient
    EnchantedCake("ENCHANTED_CAKE"),
    EnchantedRedstoneLamp("ENCHANTED_REDSTONE_LAMP"),
    FoulFlesh("FOUL_FLESH"),

    //Consumable

    //Cosmetic TODO: Pet Skins, FireSales, Furniture, Helmet Skins, Reward Bundles, Runes, Sprays
    AutumnHutBarnSkin("AUTUMN_HUT_BARN_SKIN"),
    BambooBarnSkin("BAMBOO_BARN_SKIN"),
    BeachBallBarnSkin("BEACH_BALL_BARN_SKIN"),
    BeautifallCabinBarnSkin("BEAUTIFALL_CABIN_BARN_SKIN"),
    BingoDisplay("BINGO_DISPLAY"),
    BonzoStatue("BONZO_STATUE"),
    BookOfStats("BOOK_OF_STATS"),
    CastleBarnSkin("CASTLE_BARN_SKIN"),
    ChocolateFactoryBarnSkin("CHOCOLATE_FACTORY_BARN_SKIN"),
    CollectionDisplay("COLLECTION_DISPLAY"),
    CozyCottageBarnSkin("COZY_COTTAGE_BARN_SKIN"),
    CubeBarnSkin("CUBE_BARN_SKIN"),
    DittoBlob("DITTO_BLOB"),
    DittoSkin("DITTO_SKIN"),
    DittoSkull("DITTO_SKULL"),
    EnchantedNookBarnSkin("ENCHANTED_NOOK_BARN_SKIN"),
    FrogBarnSkin("FROG_BARN_SKIN"),
    GoldenDanteStatue("GOLDEN_DANTE_STATUE"),
    HiveBarnSkin("HIVE_BARN_SKIN"),
    JerryBarnSkin("JERRY_BARN_SKIN"),
    BlackLamp("LAMP_BLACK"),
    GrayLamp("LAMP_GRAY"),
    LightGrayLamp("LAMP_LIGHT_GRAY"),
    WhiteLamp("LAMP_WHITE"),
    BrownLamp("LAMP_BROWN"),
    OrangeLamp("LAMP_ORANGE"),
    RedLamp("LAMP_RED"),
    YellowLamp("LAMP_YELLOW"),
    PurpleLamp("LAMP_PURPLE"),
    MagentaLamp("LAMP_MAGENTA"),
    LilacLamp("LAMP_LILAC"),
    PinkLamp("LAMP_PINK"),
    GreenLamp("LAMP_GREEN"),
    LimeLamp("LAMP_LIME"),
    BlueLamp("LAMP_BLUE"),
    CyanLamp("LAMP_CYAN"),
    LightBlueLamp("LAMP_LIGHT_BLUE"),
    RainbowLamp("LAMP_RAINBOW"),
    LuckyBarnSkin("LUCKY_BARN_SKIN"),
    MainStreetBarnSkin("MAIN_STREET_BARN_SKIN"),
    MushroomBarnSkin("MUSHROOM_BARN_SKIN"),
    PesthuntersLairBarnSkin("PESTHUNTERS_LAIR_BARN_SKIN"),
    PinwheelHouseBarnSkin("PINWHEEL_HOUSE_BARN_SKIN"),
    SandCastleBarnSkin("SAND_CASTLE_BARN_SKIN"),
    TavernBarnSkin("TAVERN_BARN_SKIN"),
    TheEndBarnSkin("END_BARN_SKIN"),
    TownHallBarnSkin("TOWN_HALL_BARN_SKIN"),
    TradingPostBarnSkin("TRADING_POST_BARN_SKIN"),
    WindmillBarnSkin("WINDMILL_BARN_SKIN"),
    WinterBarnSkin("WINTER_BARN_BARN_SKIN"),
    WinterHomesteadBarnSkin("WINTER_HOMESTEAD_BARN_SKIN"),

    //Crafting Material

    //Drill Part
    AmberPolishedDrillEngine("AMBER_POLISHED_DRILL_ENGINE"),
    Biofuel("BIOFUEL"),
    BlueCheeseGoblinOmelette("GOBLIN_OMELETTE_BLUE_CHEESE"),
    GemstoneFuelTank("GEMSTONE_FUEL_TANK"),
    GoblinOmelette("GOBLIN_OMELETTE"),
    MithrilInfusedFuelTank("MITHRIL_FUEL_TANK"),
    OilBarrel("OIL_BARREL"),
    PerfectlyCutFuelTank("PERFECTLY_CUT_FUEL_TANK"),
    PestoGoblinOmelette("GOBLIN_OMELETTE_PESTO"),
    RubyPolishedDrillEngine("RUBY_POLISHED_DRILL_ENGINE"),
    SapphirePolishedDrillEngine("SAPPHIRE_POLISHED_DRILL_ENGINE"),
    SpicyGoblinOmelette("GOBLIN_OMELETTE_SPICY"),
    SunnySideGoblinOmelette("GOBLIN_OMELETTE_SUNNY_SIDE"),
    TitaniumInfusedFuelTank("TITANIUM_FUEL_TANK"),
    TitaniumPlatedDrillEngine("TITANIUM_DRILL_ENGINE"),

    //Equipment
    ArachnesNecklace("ARACHNE_NECKLACE", { Gear(it.raw) }),
    ArachnesCloak("ARACHNE_CLOAK", { Gear(it.raw) }),
    ArachnesBelt("ARACHNE_BELT", { Gear(it.raw) }),
    ArachnesGloves("ARACHNE_GLOVES", { Gear(it.raw) }),

    //Forgeable Item

    //Item Sack

    //Memento
    BasketOfHope("POTATO_BASKET"),
    BingosSecrets("SECRET_BINGO_MEMENTO"),
    CakeSliceOfTheCentury("CENTURY_MEMENTO_RED"),
    CampaignPoster("CAMPAIGN_POSTER"),
    ExpensiveToy("EXPENSIVE_TOY"),
    FrenchBread("FRENCH_BREAD"),
    GoldenCollar("GOLDEN_COLLAR"),
    LockedBallotBox("LOCKED_BALLOT_BOX"),
    MoldyMuffin("MOLDY_MUFFIN"),
    PaintersPalette("PAINTERS_PALETTE"),
    PieceOfWizardPortal("WIZARD_PORTAL_MEMENTO"),
    ShinyRelic("SHINY_RELIC"),
    ThereAndBackAgain("RIFT_COMPLETION_MEMENTO"),

    //Minion

    //Mixin

    //Pet

    //Potion

    //Power Stone

    //Reforge Stone

    //Rift Item

    //Rift Timecharm

    //Shears

    //Tool

    //Vanilla Item

    //Wand

    //Weapon
    PhantomRod("PHANTOM_ROD", { Gear(it.raw) }),
    Shredder("THE_SHREDDER", { Gear(it.raw) }),
    Hyperion("HYPERION", { WitherBlade(it.raw) }),
    Valkyrie("VALKYRIE", { WitherBlade(it.raw) }),
    Scylla("SCYLLA", { WitherBlade(it.raw) }),
    Astraea("ASTRAEA", { WitherBlade(it.raw) }),
    NecronBlade("NECRON_BLADE", { WitherBlade(it.raw) }),
    Terminator("TERMINATOR", { Terminator(it.raw) }),

    //Misc
    KuudraKey("KUUDRA_TIER_KEY"),
    HotKuudraKey("KUUDRA_HOT_TIER_KEY"),
    BurningKuudraKey("KUUDRA_BURNING_TIER_KEY"),
    FieryKuudraKey("KUUDRA_FIERY_TIER_KEY"),
    InfernalKuudraKey("KUUDRA_INFERNAL_TIER_KEY"),
    TarantulaSilk("TARANTULA_SILK"),


    EnchantedBook("ENCHANTED_BOOK", { EnchantedBook(it.raw) }),
    GlossyMineralHelmetRoyalSkin("GLOSSY_MINERAL_HELMET_ROYAL"),
    CarnivalTicket("CARNIVAL_TICKET"),
    GreaterBackpack("GREATER_BACKPACK"),
    Recombobulator3000("RECOMBOBULATOR_3000"),
    UltimateCarrotCandyUpgrade("ULTIMATE_CARROT_CANDY_UPGRADE"),
    FlintArrow("ARROW"),
    ShatteredLocket("SHATTERED_PENDANT"),
    RadiantPowerOrb("RADIANT_POWER_ORB", { Deployable(it.raw) }),
    ManaFluxPowerOrb("MANA_FLUX_POWER_ORB", { Deployable(it.raw) }),
    OverfluxPowerOrb("OVERFLUX_POWER_ORB", { Deployable(it.raw) }),
    PlasmafluxPowerOrb("PLASMAFLUX_POWER_ORB", { Deployable(it.raw) }),
    WarningFlare("WARNING_FLARE", { Deployable(it.raw) }),
    AlertFlare("ALERT_FLARE", { Deployable(it.raw) }),
    SOSFlare("SOS_FLARE", { Deployable(it.raw) }),
    BuildersWand("BUILDERS_WAND", { BuildersWand(it.raw) }),
    AspectOfTheVoid("ASPECT_OF_THE_VOID"),
    RodOfTheSea("ROD_OF_THE_SEA"),
    SkyblockMenu("SKYBLOCK_MENU"),
    GrandExpBottle("GRAND_EXP_BOTTLE"),
    TitanicExpBottle("TITANIC_EXP_BOTTLE"),
    InfernoRod("INFERNO_ROD"),
    DivansDrill("DIVAN_DRILL"),
    Pickonimbus("PICKONIMBUS"),
    RoyalPigeon("ROYAL_PIGEON"),
    RoyalCompass("ROYAL_COMPASS"),
    DwarvenMetalDetector("DWARVEN_METAL_DETECTOR"),
    Treecapitator("TREECAPITATOR_AXE"),
    SkeletonKey("SKELETON_KEY"),
    IceSprayWand("ICE_SPRAY_WAND"),
    DaedalusAxe("DAEDALUS_AXE"),
    FireFreezeStaff("FIRE_FREEZE_STAFF"),
    Stonk("STONK_PICKAXE"),
    ImplosionBelt("IMPLOSION_BELT"),
    MoodyGrappleshot("MOODY_GRAPPLESHOT"),
    BobOmb("BOB_OMB"),
    Infinileap("INFINITE_SPIRIT_LEAP"),
    InfinityboomTNT("INFINITE_SUPERBOOM_TNT"),
    RunaansBow("RUNAANS_BOW"),
    AbiCase("ABICASE"),
    BalloonSnake("BALLOON_SNAKE"),
    AncestralSpade("ANCESTRAL_SPADE"),
    NecronsHandle("NECRON_HANDLE"),
    LunarPigmanSkin("PET_SKIN_PIGMAN_LUNAR_PIG"),
    FireVeilWand("FIRE_VEIL_WAND"),
    ThunderboltNecklace("THUNDERBOLT_NECKLACE"),
    PestVest("PEST_VEST"),
    Sprayonator("SPRAYONATOR"),
    CocoChopper("COCO_CHOPPER"),
    FungiCutter("FUNGI_CUTTER"),
    SqueakyMousemat("SQUEAKY_MOUSEMAT"),
    Pet("PET", { PetAsItem(it.raw) }),
    PoochSword("POOCH_SWORD"),
    SapphirePowerScroll("SAPPHIRE_POWER_SCROLL"),
    SorrowHelmet("SORROW_HELMET"),
    SorrowChestplate("SORROW_CHESTPLATE"),
    SorrowLeggings("SORROW_LEGGINGS"),
    SorrowBoots("SORROW_BOOTS"),
    PerfectChisel("PERFECT_CHISEL"),
    ScareFragment("SCARE_FRAGMENT"),
    ExpShareCore("PET_ITEM_EXP_SHARE_DROP"),
    NullEdge("NULL_EDGE"),
    NullBlade("NULL_BLADE"),
    JudgementCore("JUDGEMENT_CORE"),
    JumboBackpack("JUMBO_BACKPACK"),
    BookOfProgression("BOOK_OF_PROGRESSION"),
    FarmingTalisman("FARMING_TALISMAN"),
    VillageTalisman("VILLAGE_TALISMAN"),
    RodOfLegends("LEGEND_ROD"),
    AbiphoneXPlus("ABIPHONE_X_PLUS"),
    AbiphoneXPlusSpecialEdition("ABIPHONE_X_PLUS_SPECIAL_EDITION"),
    AbiphoneXIUltra("ABIPHONE_XI_ULTRA"),
    AbiphoneXIUltraStyle("ABIPHONE_XI_ULTRA_STYLE"),
    AbiphoneXIIMega("ABIPHONE_XII_MEGA"),
    AbiphoneXIIMegaColor("ABIPHONE_XII_MEGA_COLOR"),
    AbiphoneXIIIPro("ABIPHONE_XIII_PRO"),
    AbiphoneXIIIProGiga("ABIPHONE_XIII_PRO_GIGA"),
    AbiphoneXIVEnormous("ABIPHONE_XIV_ENORMOUS"),
    AbiphoneXIVEnormousPurple("ABIPHONE_XIV_ENORMOUS_PURPLE"),
    AbiphoneXIVEnormousBlack("ABIPHONE_XIV_ENORMOUS_BLACK"),
    AbiphoneFlipDragon("ABIPHONE_FLIP_DRAGON"),
    AbiphoneFlipNucleus("ABIPHONE_FLIP_NUCLEUS"),
    AbiphoneFlipVolcano("ABIPHONE_FLIP_VOLCANO"),
    AbiphoneBingo("ABINGOPHONE"),
    MithrilDrillSxR326("MITHRIL_DRILL_2");

    constructor(apiName: String) : this(apiName, { it })

    class UnknownSkyblockItemId(override val apiName: String) : SkyblockItemId

    companion object {
        fun fromApiName(apiName: String): SkyblockItemId {
            return KnownSkyblockItemId.entries.firstOrNull { it.apiName == apiName } ?: UnknownSkyblockItemId(apiName)
        }
    }
}