package net.dungeonhub.hypixel.entities.inventory.items

enum class KnownSkyblockItemId(override val apiName: String, val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    SkyblockItemId {
    //Accessory
    TwoIQPoints("TWO_IQ_POINT"),
    FifthAnniversaryBalloonHat("BALLOON_HAT_2024"),
    Abicase("ABICASE"),
    AgarimooArtifact("AGARIMOO_ARTIFACT"),
    AgarimooRing("AGARIMOO_RING"),
    AgarimooTalisman("AGARIMOO_TALISMAN"),
    AnitasArtifact("ANITA_ARTIFACT"),
    AnitasRing("ANITA_RING"),
    AnitasTalisman("ANITA_TALISMAN"),
    ArchaeologistsCompass("ARCHAEOLOGIST_COMPASS"),
    ArtifactOfCoins("ARTIFACT_OF_COINS"),
    ArtifactOfControl("ARTIFACT_OF_CONTROL"),
    ArtifactOfPower("POWER_ARTIFACT"),
    AtmosphericFilter("ATMOSPHERIC_FILTER"),
    AutoRecombobulator("AUTO_RECOMBOBULATOR"),
    BaitRing("BAIT_RING"),
    BatArtifact("BAT_ARTIFACT"),
    BatPersonArtifact("BAT_PERSON_ARTIFACT"),
    BatPersonRing("BAT_PERSON_RING"),
    BatPersonTalisman("BAT_PERSON_TALISMAN"),
    BatRing("BAT_RING"),
    BatTalisman("BAT_TALISMAN"),
    CommonBeastmasterCrest("BEASTMASTER_CREST_COMMON"),
    UncommonBeastmasterCrest("BEASTMASTER_CREST_UNCOMMON"),
    RareBeastmasterCrest("BEASTMASTER_CREST_RARE"),
    EpicBeastmasterCrest("BEASTMASTER_CREST_EPIC"),
    LegendaryBeastmasterCrest("BEASTMASTER_CREST_LEGENDARY"),
    BigBrainTalisman("BIG_BRAIN_TALISMAN"),
    BingoArtifact("BINGO_ARTIFACT"),
    BingoCombatTalisman("BINGO_COMBAT_TALISMAN"),
    BingoRelic("BINGO_RELIC"),
    BingoRing("BINGO_RING"),
    BingoTalisman("BINGO_TALISMAN"),
    BitsTalisman("BITS_TALISMAN"),
    BlazeTalisman("BLAZE_TALISMAN"),
    BloodDonorArtifact("BLOOD_DONOR_ARTIFACT"),
    BloodDonorRing("BLOOD_DONOR_RING"),
    BloodGodCrest("BLOOD_GOD_CREST"),
    BlueGiftTalisman("BLUE_GIFT_TALISMAN"),
    BlueJerryTalisman("JERRY_TALISMAN_BLUE"),
    BluetoothRing("BLUETOOTH_RING"),
    BookOfProgression("BOOK_OF_PROGRESSION"),
    BrokenPiggyBank("BROKEN_PIGGY_BANK"),
    BucketOfDye("BUCKET_OF_DYE"),
    BurningKuudraCore("BURNING_KUUDRA_CORE"),
    BurststopperArtifact("BURSTSTOPPER_ARTIFACT"),
    BurststopperTalisman("BURSTSTOPPER_TALISMAN"),
    CampfireInitiateBadgeOne("CAMPFIRE_TALISMAN_1"),
    CampfireInitiateBadgeTwo("CAMPFIRE_TALISMAN_2"),
    CampfireInitiateBadgeThree("CAMPFIRE_TALISMAN_3"),
    CampfireAdeptBadgeOne("CAMPFIRE_TALISMAN_4"),
    CampfireAdeptBadgeTwo("CAMPFIRE_TALISMAN_5"),
    CampfireAdeptBadgeThree("CAMPFIRE_TALISMAN_6"),
    CampfireAdeptBadgeFour("CAMPFIRE_TALISMAN_7"),
    CampfireCultistBadgeOne("CAMPFIRE_TALISMAN_8"),
    CampfireCultistBadgeTwo("CAMPFIRE_TALISMAN_9"),
    CampfireCultistBadgeThree("CAMPFIRE_TALISMAN_10"),
    CampfireCultistBadgeFour("CAMPFIRE_TALISMAN_11"),
    CampfireCultistBadgeFive("CAMPFIRE_TALISMAN_12"),
    CampfireScionBadgeOne("CAMPFIRE_TALISMAN_13"),
    CampfireScionBadgeTwo("CAMPFIRE_TALISMAN_14"),
    CampfireScionBadgeThree("CAMPFIRE_TALISMAN_15"),
    CampfireScionBadgeFour("CAMPFIRE_TALISMAN_16"),
    CampfireScionBadgeFive("CAMPFIRE_TALISMAN_17"),
    CampfireScionBadgeSix("CAMPFIRE_TALISMAN_18"),
    CampfireScionBadgeSeven("CAMPFIRE_TALISMAN_19"),
    CampfireScionBadgeEight("CAMPFIRE_TALISMAN_20"),
    CampfireGodBadgeOne("CAMPFIRE_TALISMAN_21"),
    CampfireGodBadgeTwo("CAMPFIRE_TALISMAN_22"),
    CampfireGodBadgeThree("CAMPFIRE_TALISMAN_23"),
    CampfireGodBadgeFour("CAMPFIRE_TALISMAN_24"),
    CampfireGodBadgeFive("CAMPFIRE_TALISMAN_25"),
    CampfireGodBadgeSix("CAMPFIRE_TALISMAN_26"),
    CampfireGodBadgeSeven("CAMPFIRE_TALISMAN_27"),
    CampfireGodBadgeEight("CAMPFIRE_TALISMAN_28"),
    CampfireGodBadgeNine("CAMPFIRE_TALISMAN_29"),
    CandyArtifact("CANDY_ARTIFACT"),
    CandyRelic("CANDY_RELIC"),
    CandyRing("CANDY_RING"),
    CandyTalisman("CANDY_TALISMAN"),
    CarnivalMaskBag("CARNIVAL_MASK_BAG"),
    CatTalisman("CAT_TALISMAN"),
    CatacombsExpertRing("CATACOMBS_EXPERT_RING"),
    CelestialStarstone("CRUX_TALISMAN_7"),
    CheetahTalisman("CHEETAH_TALISMAN"),
    ChummingTalisman("CHUMMING_TALISMAN"),
    ComboMania("COMBO_MANIA_TALISMAN"),
    CrabHatOfCelebration("PARTY_HAT_CRAB"),
    CrackedPiggyBank("CRACKED_PIGGY_BANK"),
    CrookedArtifact("CROOKED_ARTIFACT"),
    CropieTalisman("CROPIE_TALISMAN"),
    CruxTalisman("CRUX_TALISMAN_1"),
    CruxRing("CRUX_TALISMAN_2"),
    CruxArtifact("CRUX_TALISMAN_3"),
    CruxRelic("CRUX_TALISMAN_4"),
    CruxHeirloom("CRUX_TALISMAN_5"),
    CruxChronomicon("CRUX_TALISMAN_6"),
    DanteRing("DANTE_RING"),
    DanteTalisman("DANTE_TALISMAN"),
    DayCrystal("DAY_CRYSTAL"),
    DefectiveMonitor("DEFECTIVE_MONITOR"),
    DevourRing("DEVOUR_RING"),
    DraconicArtifact("DRACONIC_ARTIFACT"),
    DraconicRing("DRACONIC_RING"),
    DraconicTalisman("DRACONIC_TALISMAN"),
    DullSharkToothNecklace("DULL_SHARK_TOOTH_NECKLACE"),
    DwarvenMetalTalisman("DWARVEN_METAL"),
    EmeraldArtifact("EMERALD_ARTIFACT"),
    EmeraldRing("EMERALD_RING"),
    EnderArtifact("ENDER_ARTIFACT"),
    EnderRelic("ENDER_RELIC"),
    EternalCrystal("ETERNAL_CRYSTAL"),
    EternalHoof("ETERNAL_HOOF"),
    ExperienceArtifact("EXPERIENCE_ARTIFACT"),
    FarmerOrb("FARMER_ORB"),
    FarmingTalisman("FARMING_TALISMAN"),
    FeatherArtifact("FEATHER_ARTIFACT"),
    FeatherRing("FEATHER_TALISMAN"),
    FermentoArtifact("FERMENTO_ARTIFACT"),
    FieryKuudraCore("FIERY_KUUDRA_CORE"),
    FireTalisman("FIRE_TALISMAN"),
    FishAffinityTalisman("FISH_AFFINITY_TALISMAN"),
    FrozenChicken("FROZEN_CHICKEN"),
    FutureCaloriesTalisman("FUTURE_CALORIES"),
    GanacheChocolateSlab("GANACHE_CHOCOLATE_SLAB"),
    GeneralsMedallion("GENERAL_MEDALLION"),
    GlacialArtifact("GLACIAL_ARTIFACT"),
    GlacialRing("GLACIAL_RING"),
    GlacialTalisman("GLACIAL_TALISMAN"),
    GlossyMineralTalisman("GLOSSY_MINERAL_TALISMAN"),
    GoldGiftTalisman("GOLD_GIFT_TALISMAN"),
    GoldenJerryArtifact("JERRY_TALISMAN_GOLDEN"),
    GravityTalisman("GRAVITY_TALISMAN"),
    GreatSpookArtifact("GREAT_SPOOK_ARTIFACT"),
    GreatSpookRing("GREAT_SPOOK_RING"),
    GreatSpookTalisman("GREAT_SPOOK_TALISMAN"),
    GreenGiftTalisman("GREEN_GIFT_TALISMAN"),
    GreenJerryTalisman("JERRY_TALISMAN_GREEN"),
    HandyBloodChalice("HANDY_BLOOD_CHALICE"),
    HarmoniousSurgeryToolkit("HARMONIOUS_SURGERY_TOOLKIT"),
    HasteRing("HASTE_RING"),
    HealingRing("HEALING_RING"),
    HealingTalisman("HEALING_TALISMAN"),
    HegemonyArtifact("HEGEMONY_ARTIFACT"),
    HonedSharkToothNecklace("HONED_SHARK_TOOTH_NECKLACE"),
    HunterRing("HUNTER_RING"),
    HunterTalisman("HUNTER_TALISMAN"),
    InfernalKuudraCore("INFERNAL_KUUDRA_CORE"),
    IntimidationArtifact("INTIMIDATION_ARTIFACT"),
    IntimidationRelic("INTIMIDATION_RELIC"),
    IntimidationRing("INTIMIDATION_RING"),
    IntimidationTalisman("INTIMIDATION_TALISMAN"),
    IQPoint("IQ_POINT"),
    JacobusRegister("JACOBUS_REGISTER"),
    JakesPlushie("JAKE_PLUSHIE"),
    JungleAmulet("JUNGLE_AMULET"),
    KingTalisman("KING_TALISMAN"),
    KuudraFollowerArtifact("KUUDRA_FOLLOWER_ARTIFACT"),
    KuudraFollowerRelic("KUUDRA_FOLLOWER_RELIC"),
    LavaTalisman("LAVA_TALISMAN"),
    LuckyHoof("LUCKY_HOOF"),
    LushArtifact("LUSH_ARTIFACT"),
    LushRing("LUSH_RING"),
    LushTalisman("LUSH_TALISMAN"),
    LynxTalisman("LYNX_TALISMAN"),
    MagicEightBall("MAGIC_8_BALL"),
    MagneticTalisman("MAGNETIC_TALISMAN"),
    MasterSkullTierOne("MASTER_SKULL_TIER_1"),
    MasterSkullTierTwo("MASTER_SKULL_TIER_2"),
    MasterSkullTierThree("MASTER_SKULL_TIER_3"),
    MasterSkullTierFour("MASTER_SKULL_TIER_4"),
    MasterSkullTierFive("MASTER_SKULL_TIER_5"),
    MasterSkullTierSix("MASTER_SKULL_TIER_6"),
    MasterSkullTierSeven("MASTER_SKULL_TIER_7"),
    MelodysHair("MELODY_HAIR"),
    MineAffinityTalisman("MINE_TALISMAN"),
    MineralTalisman("MINERAL_TALISMAN"),
    MiniaturizedTubulator("MINIATURIZED_TUBULATOR"),
    NetherArtifact("NETHER_ARTIFACT"),
    NetherrackLookingSunshade("NETHERRACK_LOOKING_SUNSHADE"),
    NewYearCakeBag("NEW_YEAR_CAKE_BAG"),
    NibbleChocolateStick("NIBBLE_CHOCOLATE_STICK"),
    NightCrystal("NIGHT_CRYSTAL"),
    NightVisionCharm("NIGHT_VISION_CHARM"),
    OdgersBronzeTooth("ODGERS_BRONZE_TOOTH"),
    OdgersDiamondTooth("ODGERS_DIAMOND_TOOTH"),
    OdgersGoldTooth("ODGERS_GOLD_TOOTH"),
    OdgersSilverTooth("ODGERS_SILVER_TOOTH"),
    PandorasBox("PANDORAS_BOX"),
    PermaJelledGarlicFlavoredReHeatedGummyPolarBear("GARLIC_FLAVORED_GUMMY_BEAR"),
    PersonalCompactor4000("PERSONAL_COMPACTOR_4000"),
    PersonalCompactor5000("PERSONAL_COMPACTOR_5000"),
    PersonalCompactor6000("PERSONAL_COMPACTOR_6000"),
    PersonalCompactor7000("PERSONAL_COMPACTOR_7000"),
    PersonalDeletor4000("PERSONAL_DELETOR_4000"),
    PersonalDeletor5000("PERSONAL_DELETOR_5000"),
    PersonalDeletor6000("PERSONAL_DELETOR_6000"),
    PersonalDeletor7000("PERSONAL_DELETOR_7000"),
    PesthunterArtifact("PESTHUNTER_ARTIFACT"),
    PesthunterBadge("PESTHUNTER_BADGE"),
    PesthunterRing("PESTHUNTER_RING"),
    PigsFoot("PIGS_FOOT"),
    PiggyBank("PIGGY_BANK"),
    PocketEspressoMachine("POCKET_ESPRESSO_MACHINE"),
    PotatoTalisman("POTATO_TALISMAN"),
    PotionAffinityArtifact("ARTIFACT_POTION_AFFINITY"),
    PotionAffinityRing("RING_POTION_AFFINITY"),
    PotionAffinityTalisman("POTION_AFFINITY_TALISMAN"),
    PrestigeChocolateRealm("PRESTIGE_CHOCOLATE_REALM"),
    PulseRing("PULSE_RING"),
    PunchcardArtifact("PUNCHCARD_ARTIFACT"),
    PurpleGiftTalisman("PURPLE_GIFT_TALISMAN"),
    PurpleJerryTalisman("JERRY_TALISMAN_PURPLE"),
    RaggedySharkToothNecklace("RAGGEDY_SHARK_TOOTH_NECKLACE"),
    RazorSharpSharkToothNecklace("RAZOR_SHARP_SHARK_TOOTH_NECKLACE"),
    ReaperOrb("REAPER_ORB"),
    RedClawArtifact("RED_CLAW_ARTIFACT"),
    RedClawRing("RED_CLAW_RING"),
    RedClawTalisman("RED_CLAW_TALISMAN"),
    RelicOfCoins("RELIC_OF_COINS"),
    RelicOfPower("POWER_RELIC"),
    RichChocolateChunk("RICH_CHOCOLATE_CHUNK"),
    RiftPrism("RIFT_PRISM"),
    RingOfBrokenLove("RING_OF_BROKEN_LOVE"),
    RingOfCoins("RING_OF_COINS"),
    RingOfEternalLove("RING_OF_ETERNAL_LOVE"),
    ShinyYellowRock("WEDDING_RING_0"),
    YellowRockOfLove("WEDDING_RING_1"),
    MediocreRingOfLove("WEDDING_RING_2"),
    RubbishRingOfLove("WEDDING_RING_3"),
    ModestRingOfLove("WEDDING_RING_4"),
    RefinedRingOfLove("WEDDING_RING_5"),
    ClassyRingOfLove("WEDDING_RING_6"),
    ExquisiteRingOfLove("WEDDING_RING_7"),
    InvaluableRingOfLove("WEDDING_RING_8"),
    LegendaryRingOfLove("WEDDING_RING_9"),
    RingOfPower("POWER_RING"),
    RingOfTheCentury("CENTURY_RING"),
    Runebook("RUNEBOOK"),
    Satelite("SATELITE"),
    ScarfsGrimoire("SCARF_GRIMOIRE"),
    ScarfsStudies("SCARF_STUDIES"),
    ScarfsThesis("SCARF_THESIS"),
    ScavengerArtifact("SCAVENGER_ARTIFACT"),
    ScavengerRing("SCAVENGER_RING"),
    ScavengerTalisman("SCAVENGER_TALISMAN"),
    SeaCreatureArtifact("SEA_CREATURE_ARTIFACT"),
    SeaCreatureRing("SEA_CREATURE_RING"),
    SeaCreatureTalisman("SEA_CREATURE_TALISMAN"),
    SealOfTheFamily("SEAL_OF_THE_FAMILY"),
    SealRing("SEAL_RING"),
    SealTalisman("SEAL_TALISMAN"),
    ShadyRing("SHADY_RING"),
    SharpSharkToothNecklace("SHARP_SHARK_TOOTH_NECKLACE"),
    ShensRegalia("SHENS_REGALIA"),
    SkeletonTalisman("SKELETON_TALISMAN"),
    SlothHatOfCelebration("PARTY_HAT_SLOTH"),
    SmoothChocolateBar("SMOOTH_CHOCOLATE_BAR"),
    SoulflowBattery("SOULFLOW_BATTERY"),
    SoulflowPile("SOULFLOW_PILE"),
    SoulflowSupercell("SOULFLOW_SUPERCELL"),
    SpeedArtifact("SPEED_ARTIFACT"),
    SpeedRing("SPEED_RING"),
    SpeedTalisman("SPEED_TALISMAN"),
    SpiderArtifact("SPIDER_ARTIFACT"),
    SpiderRing("SPIDER_RING"),
    SpiderTalisman("SPIDER_TALISMAN"),
    SpikedAtrocity("SPIKED_ATROCITY"),
    SquashRing("SQUASH_RING"),
    SurvivorCube("SURVIVOR_CUBE"),
    TalismanOfCoins("COIN_TALISMAN"),
    TalismanOfPower("POWER_TALISMAN"),
    TalismanOfTheCentury("CENTURY_TALISMAN"),
    TarantulaTalisman("TARANTULA_TALISMAN"),
    TestBucketPleaseIgnore("TEST_BUCKET_PLEASE_IGNORE"),
    TinyDancer("TINY_DANCER"),
    TitaniumArtifact("TITANIUM_ARTIFACT"),
    TitaniumRelic("TITANIUM_RELIC"),
    TitaniumRing("TITANIUM_RING"),
    TitaniumTalisman("TITANIUM_TALISMAN"),
    TrapperCrest("TRAPPER_CREST"),
    TreasureArtifact("TREASURE_ARTIFACT"),
    TreasureRing("TREASURE_RING"),
    TreasureTalisman("TREASURE_TALISMAN"),
    VaccineArtifact("VACCINE_ARTIFACT"),
    VaccineRing("VACCINE_RING"),
    VaccineTalisman("VACCINE_TALISMAN"),
    VampireDentistRelic("VAMPIRE_DENTIST_RELIC"),
    VillageAffinityTalisman("VILLAGE_TALISMAN"),
    WardingTrinket("WARDING_TRINKET"),
    WhiteGiftTalisman("WHITE_GIFT_TALISMAN"),
    WitherArtifact("WITHER_ARTIFACT"),
    WitherRelic("WITHER_RELIC"),
    WolfPaw("WOLF_PAW"),
    WolfRing("WOLF_RING"),
    WolfTalisman("WOLF_TALISMAN"),
    WoodAffinityTalisman("WOOD_TALISMAN"),
    ZombieArtifact("ZOMBIE_ARTIFACT"),
    ZombieRing("ZOMBIE_RING"),
    ZombieTalisman("ZOMBIE_TALISMAN"),

    //Admin Item
    AdminLavaRod("ADMIN_ROD"),
    AdminsWarmSweater("ADMINS_WARM_SWEATER", { Armor(it.raw) }),
    Anubis("ANUBIS", { Armor(it.raw) }),
    ArenjeyGod("MEGA_LUCK", { Armor(it.raw) }),
    Boss("BOSS", { Armor(it.raw) }),
    BowOfTheUniverse("UNIVERSE_BOW", { Bow(it.raw) }),
    EnchantedClockAdmin("ENCHANTED_CLOCK"),
    FerocitySword150("FEROCITY_SWORD_150", { Weapon(it.raw) }),
    FerocitySword50("FEROCITY_SWORD_50", { Weapon(it.raw) }),
    GiantPileOfCash("PILE_OF_CASH"),
    Kindred("KINDRED", { Armor(it.raw) }),
    Raygun("RAYGUN", { Bow(it.raw) }),
    SwordOfTheMultiverse("SWORD_OF_THE_MULTIVERSE", { Weapon(it.raw) }),
    SwordOfTheStars("STAR_SWORD", { Weapon(it.raw) }),
    SwordOfTheStars3000("STAR_SWORD_3000", { Weapon(it.raw) }),
    SwordOfTheStars9000("STAR_SWORD_9000", { Weapon(it.raw) }),
    SwordOfTheUniverse("NOVA_SWORD", { Weapon(it.raw) }),
    TheFast("SPEED_RACER", { Armor(it.raw) }),
    Voodoo("VOODOO", { Armor(it.raw) }),
    Zoom("ZOOM_PICKAXE", { Gear(it.raw) }),

    //Armor
    ExceedinglyComfySneakers("EXCEEDINGLY_COMFY_SNEAKERS", { Armor(it.raw) }),
    FarmerBoots("FARMER_BOOTS", { Armor(it.raw) }),
    GhostlyBoots("GHOST_BOOTS", { Armor(it.raw) }),
    GunthersSneakers("GUNTHER_SNEAKERS", { Armor(it.raw) }),
    RanchersBoots("RANCHERS_BOOTS", { Armor(it.raw) }),
    SlugBoots("SLUG_BOOTS", { Armor(it.raw) }),
    SnakeInABoot("SNAKE_IN_A_BOOT", { Armor(it.raw) }),
    SpidersBoots("SPIDER_BOOTS", { Armor(it.raw) }),
    SpiritBoots("THORNS_BOOTS", { Armor(it.raw) }),
    SpringBoots("SPRING_BOOTS", { Armor(it.raw) }),
    SquidBoots("SQUID_BOOTS", { Armor(it.raw) }),
    UglyBoots("UGLY_BOOTS", { Armor(it.raw) }),
    EtalptsehCnorI("ETALPTSEHC_NORI", { Armor(it.raw) }),
    FlamingChestplate("FLAMING_CHESTPLATE", { Armor(it.raw) }),
    GuardianChestplate("GUARDIAN_CHESTPLATE", { Armor(it.raw) }),
    LivelySepultureChestplate("LIVELY_SEPULTURE_CHESTPLATE", { Armor(it.raw) }),
    MetalChestplate("METAL_CHESTPLATE", { Armor(it.raw) }),
    MithrilCoat("MITHRIL_COAT", { Armor(it.raw) }),
    ObsidianChestplate("OBSIDIAN_CHESTPLATE", { Armor(it.raw) }),
    OrangeChestplate("ORANGE_CHESTPLATE", { Armor(it.raw) }),
    ShimmersparkleChestplate("SHIMMERSPARKLE_CHESTPLATE", { Armor(it.raw) }),
    SteelChestplate("STEEL_CHESTPLATE", { Armor(it.raw) }),
    StoneChestplate("STONE_CHESTPLATE", { Armor(it.raw) }),
    WLogo("S_LOGO_CHESTPLATE", { Armor(it.raw) }),
    BurnedPants("BURNED_PANTS", { Armor(it.raw) }),
    ChickenLeggs("CHICKEN_LEGGS", { Armor(it.raw) }),
    CreeperPants("CREEPER_LEGGINGS", { Armor(it.raw) }),
    FemurgrowthLeggings("FEMURGROWTH_LEGGINGS", { Armor(it.raw) }),
    LeggingsOfTheCoven("LEGGINGS_OF_THE_COVEN", { Armor(it.raw) }),
    MoogmaLeggings("MOOGMA_LEGGINGS", { Armor(it.raw) }),
    StereoPants("MUSIC_PANTS", { Armor(it.raw) }),
    WizardmanLeggings("WIZARDMAN_LEGGINGS", { Armor(it.raw) }),
    ArmadilloMask("ARMADILLO_MASK", { Armor(it.raw) }),
    BeeMask("BEE_MASK", { Armor(it.raw) }),
    FrogMask("FROG_MASK", { Armor(it.raw) }),
    ParrotMask("PARROT_MASK", { Armor(it.raw) }),
    SalmonMask("SALMON_MASK", { Armor(it.raw) }),
    SnowmanMask("SNOWMAN_MASK", { Armor(it.raw) }),
    ZombieMask("ZOMBIE_MASK", { Armor(it.raw) }),
    AgaricusCapCap("AGARICUS_CAP_CAP", { Armor(it.raw) }),
    AntiBiteScarf("ANTI_BITE_SCARF", { Armor(it.raw) }),
    BlazeHat("BLAZE_HAT", { Armor(it.raw) }),
    BlobfishHat("BLOBFISH_HAT", { Armor(it.raw) }),
    BonzosMask("BONZO_MASK", { Armor(it.raw) }),
    ChickenHat("CHICKEN_HEAD", { Armor(it.raw) }),
    CloverHelmet("CLOVER_HELMET", { Armor(it.raw) }),
    ClownfishHat("CLOWNFISH_HAT", { Armor(it.raw) }),
    CowHat("COW_HEAD", { Armor(it.raw) }),
    CreeperHat("CREEPER_HAT", { Armor(it.raw) }),
    CrownOfAvarice("CROWN_OF_AVARICE", { Armor(it.raw) }),
    CrownOfGreed("CROWN_OF_GREED", { Armor(it.raw) }),
    CrystallizedHeart("CRYSTALLIZED_HEART", { Armor(it.raw) }),
    DarkGoggles("DARK_GOGGLES", { Armor(it.raw) }),
    DiamondBonzoHead("DIAMOND_BONZO_HEAD", { Armor(it.raw) }),
    DiamondLividHead("DIAMOND_LIVID_HEAD", { Armor(it.raw) }),
    DiamondNecronHead("DIAMOND_NECRON_HEAD", { Armor(it.raw) }),
    DiamondProfessorHead("DIAMOND_PROFESSOR_HEAD", { Armor(it.raw) }),
    DiamondSadanHead("DIAMOND_SADAN_HEAD", { Armor(it.raw) }),
    DiamondScarfHead("DIAMOND_SCARF_HEAD", { Armor(it.raw) }),
    DiamondThornHead("DIAMOND_THORN_HEAD", { Armor(it.raw) }),
    EndermanMask("ENDERMAN_MASK", { Armor(it.raw) }),
    FallenStarHelmet("FALLEN_STAR_HAT", { Armor(it.raw) }),
    FishHat("FISH_HAT", { Armor(it.raw) }),
    FlexHelmet("FLEX_HELMET", { Armor(it.raw) }),
    GhastHead("GHAST_HEAD", { Armor(it.raw) }),
    GoldenBonzoHead("GOLD_BONZO_HEAD", { Armor(it.raw) }),
    GoldenLividHead("GOLD_LIVID_HEAD", { Armor(it.raw) }),
    GoldenNecronHead("GOLD_NECRON_HEAD", { Armor(it.raw) }),
    GoldenProfessorHead("GOLD_PROFESSOR_HEAD", { Armor(it.raw) }),
    GoldenSadanHead("GOLD_SADAN_HEAD", { Armor(it.raw) }),
    GoldenScarfHead("GOLD_SCARF_HEAD", { Armor(it.raw) }),
    GoldenThornHead("GOLD_THORN_HEAD", { Armor(it.raw) }),
    GolemHat("GOLEM_HAT", { Armor(it.raw) }),
    HappyMask("HAPPY_MASK", { Armor(it.raw) }),
    HeadOfBetrayal("BETRAYAL_HEAD", { Armor(it.raw) }),
    KalhuikiMask("KALHUIKI_MASK", { Armor(it.raw) }),
    KrampusHelmet("KRAMPUS_HELMET", { Armor(it.raw) }),
    LanternHelmet("ENCHANTED_JACK_O_LANTERN", { Armor(it.raw) }),
    MagmaCubeHead("MAGMA_CUBE_HEAD", { Armor(it.raw) }),
    MagmafishHat("MAGMA_FISH_HAT", { Armor(it.raw) }),
    MenderCrown("MENDER_CROWN", { Armor(it.raw) }),
    MenderFedora("MENDER_FEDORA", { Armor(it.raw) }),
    MenderHelmet("MENDER_HELMET", { Armor(it.raw) }),
    NotDeadGehogMask("NOT_DEADGEHOG_MASK", { Armor(it.raw) }),
    PartyTopHat("PARTY_HAT", { Armor(it.raw) }),
    PigMask("PIG_MASK", { Armor(it.raw) }),
    PotatoCrown("POTATO_CROWN", { Armor(it.raw) }),
    PrecursorEye("PRECURSOR_EYE", { Armor(it.raw) }),
    PufferfishHat("PUFFERFISH_HAT", { Armor(it.raw) }),
    RabbitHat("RABBIT_HAT", { Armor(it.raw) }),
    ReaperMask("REAPER_MASK", { Armor(it.raw) }),
    RetroEncabulatingVisor("RETRO_ENCABULATING_VISOR", { Armor(it.raw) }),
    RevivedHeart("REVIVED_HEART", { Armor(it.raw) }),
    RacingHelmet("RACING_HELMET", { Armor(it.raw) }),
    SalmonHat("SALMON_HAT", { Armor(it.raw) }),
    SeaLanternHat("SEA_LANTERN_HAT", { Armor(it.raw) }),
    ShadowGoggles("SHADOW_GOGGLES", { Armor(it.raw) }),
    SkeletonHat("SKELETON_HAT", { Armor(it.raw) }),
    SkeletonsHelmet("SKELETON_HELMET", { Armor(it.raw) }),
    SlimeHat("SLIME_HAT", { Armor(it.raw) }),
    SniperHelmet("SNIPER_HELMET", { Armor(it.raw) }),
    SpaceHelmet("DCTR_SPACE_HELM", { Armor(it.raw) }),
    SpiderHat("SPIDER_HAT", { Armor(it.raw) }),
    SpiritMask("SPIRIT_MASK", { Armor(it.raw) }),
    SquidHat("SQUID_HAT", { Armor(it.raw) }),
    TaurusHelmet("TAURUS_HELMET", { Armor(it.raw) }),
    TheBuildersClay("DUECES_BUILDER_CLAY", { Armor(it.raw) }),
    UsedDetransfiguredFace("DETRANSFIGURED_MASK", { Armor(it.raw) }),
    VampireMask("VAMPIRE_MASK", { Armor(it.raw) }),
    VampireWitchMask("VAMPIRE_WITCH_MASK", { Armor(it.raw) }),
    WardenHelmet("WARDEN_HELMET", { Armor(it.raw) }),
    WarmWizardFace("WARM_WIZARD_FACE", { Armor(it.raw) }),
    WarmerWizardFace("WARM_WIZARD_FACE_2", { Armor(it.raw) }),
    WaterHydraHead("WATER_HYDRA_HEAD", { Armor(it.raw) }),
    WitchMask("WITCH_MASK", { Armor(it.raw) }),
    WitherGoggles("WITHER_GOGGLES", { Armor(it.raw) }),
    WizardFace("WIZARD_FACE", { Armor(it.raw) }),
    ZombieHat("ZOMBIE_HAT", { Armor(it.raw) }),
    ZombiesHeart("ZOMBIE_HEART", { Armor(it.raw) }),
    AdaptiveHelmet("ADAPTIVE_HELMET", { Armor(it.raw) }),
    AdaptiveChestplate("ADAPTIVE_CHESTPLATE", { Armor(it.raw) }),
    AdaptiveLeggings("ADAPTIVE_LEGGINGS", { Armor(it.raw) }),
    AdaptiveBoots("ADAPTIVE_BOOTS", { Armor(it.raw) }),
    UpgradedAdaptiveHelmet("STARRED_ADAPTIVE_HELMET", { Armor(it.raw) }),
    UpgradedAdaptiveChestplate("STARRED_ADAPTIVE_CHESTPLATE", { Armor(it.raw) }),
    UpgradedAdaptiveLeggings("STARRED_ADAPTIVE_LEGGINGS", { Armor(it.raw) }),
    UpgradedAdaptiveBoots("STARRED_ADAPTIVE_BOOTS", { Armor(it.raw) }),
    AnglerHelmet("ANGLER_HELMET", { Armor(it.raw) }),
    AnglerChestplate("ANGLER_CHESTPLATE", { Armor(it.raw) }),
    AnglerLeggings("ANGLER_LEGGINGS", { Armor(it.raw) }),
    AnglerBoots("ANGLER_BOOTS", { Armor(it.raw) }),
    ArachnesHelmet("ARACHNE_HELMET", { Armor(it.raw) }),
    ArachnesChestplate("ARACHNE_CHESTPLATE", { Armor(it.raw) }),
    ArachnesLeggings("ARACHNE_LEGGINGS", { Armor(it.raw) }),
    ArachnesBoots("ARACHNE_BOOTS", { Armor(it.raw) }),
    HelmetOfDivan("DIVAN_HELMET", { Armor(it.raw) }),
    ChestplateOfDivan("DIVAN_CHESTPLATE", { Armor(it.raw) }),
    LeggingsOfDivan("DIVAN_LEGGINGS", { Armor(it.raw) }),
    BootsOfDivan("DIVAN_BOOTS", { Armor(it.raw) }),
    HelmetOfGrowth("GROWTH_HELMET", { Armor(it.raw) }),
    ChestplateOfGrowth("GROWTH_CHESTPLATE", { Armor(it.raw) }),
    LeggingsOfGrowth("GROWTH_LEGGINGS", { Armor(it.raw) }),
    BootsOfGrowth("GROWTH_BOOTS", { Armor(it.raw) }),
    ArmorOfMagmaHelmet("ARMOR_OF_MAGMA_HELMET", { Armor(it.raw) }),
    ArmorOfMagmaChestplate("ARMOR_OF_MAGMA_CHESTPLATE", { Armor(it.raw) }),
    ArmorOfMagmaLeggings("ARMOR_OF_MAGMA_LEGGINGS", { Armor(it.raw) }),
    ArmorOfMagmaBoots("ARMOR_OF_MAGMA_BOOTS", { Armor(it.raw) }),
    HelmetOfThePack("HELMET_OF_THE_PACK", { Armor(it.raw) }),
    ChestplateOfThePack("CHESTPLATE_OF_THE_PACK", { Armor(it.raw) }),
    LeggingsOfThePack("LEGGINGS_OF_THE_PACK", { Armor(it.raw) }),
    BootsOfThePack("BOOTS_OF_THE_PACK", { Armor(it.raw) }),
    HelmetOfTheRisingSun("ARMOR_OF_THE_RESISTANCE_HELMET", { Armor(it.raw) }),
    ChestplateOfTheRisingSun("ARMOR_OF_THE_RESISTANCE_CHESTPLATE", { Armor(it.raw) }),
    LeggingsOfTheRisingSun("ARMOR_OF_THE_RESISTANCE_LEGGINGS", { Armor(it.raw) }),
    BootsOfTheRisingSun("ARMOR_OF_THE_RESISTANCE_BOOTS", { Armor(it.raw) }),
    HelmetOfTheStars("STAR_HELMET", { Armor(it.raw) }),
    ChestplateOfTheStars("STAR_CHESTPLATE", { Armor(it.raw) }),
    LeggingsOfTheStars("STAR_LEGGINGS", { Armor(it.raw) }),
    BootsOfTheStars("STAR_BOOTS", { Armor(it.raw) }),
    AuroraHelmet("AURORA_HELMET", { Armor(it.raw) }),
    AuroraChestplate("AURORA_CHESTPLATE", { Armor(it.raw) }),
    AuroraLeggings("AURORA_LEGGINGS", { Armor(it.raw) }),
    AuroraBoots("AURORA_BOOTS", { Armor(it.raw) }),
    HotAuroraHelmet("HOT_AURORA_HELMET", { Armor(it.raw) }),
    HotAuroraChestplate("HOT_AURORA_CHESTPLATE", { Armor(it.raw) }),
    HotAuroraLeggings("HOT_AURORA_LEGGINGS", { Armor(it.raw) }),
    HotAuroraBoots("HOT_AURORA_BOOTS", { Armor(it.raw) }),
    BurningAuroraHelmet("BURNING_AURORA_HELMET", { Armor(it.raw) }),
    BurningAuroraChestplate("BURNING_AURORA_CHESTPLATE", { Armor(it.raw) }),
    BurningAuroraLeggings("BURNING_AURORA_LEGGINGS", { Armor(it.raw) }),
    BurningAuroraBoots("BURNING_AURORA_BOOTS", { Armor(it.raw) }),
    FieryAuroraHelmet("FIERY_AURORA_HELMET", { Armor(it.raw) }),
    FieryAuroraChestplate("FIERY_AURORA_CHESTPLATE", { Armor(it.raw) }),
    FieryAuroraLeggings("FIERY_AURORA_LEGGINGS", { Armor(it.raw) }),
    FieryAuroraBoots("FIERY_AURORA_BOOTS", { Armor(it.raw) }),
    InfernalAuroraHelmet("INFERNAL_AURORA_HELMET", { Armor(it.raw) }),
    InfernalAuroraChestplate("INFERNAL_AURORA_CHESTPLATE", { Armor(it.raw) }),
    InfernalAuroraLeggings("INFERNAL_AURORA_LEGGINGS", { Armor(it.raw) }),
    InfernalAuroraBoots("INFERNAL_AURORA_BOOTS", { Armor(it.raw) }),
    BatPersonHelmet("BAT_PERSON_HELMET", { Armor(it.raw) }),
    BatPersonChestplate("BAT_PERSON_CHESTPLATE", { Armor(it.raw) }),
    BatPersonLeggings("BAT_PERSON_LEGGINGS", { Armor(it.raw) }),
    BatPersonBoots("BAT_PERSON_BOOTS", { Armor(it.raw) }),
    BerserkerHelmet("BERSERKER_HELMET", { Armor(it.raw) }),
    BerserkerChestplate("BERSERKER_CHESTPLATE", { Armor(it.raw) }),
    BerserkerLeggings("BERSERKER_LEGGINGS", { Armor(it.raw) }),
    BerserkerBoots("BERSERKER_BOOTS", { Armor(it.raw) }),
    BiohazardHelmet("BIOHAZARD_HELMET", { Armor(it.raw) }),
    BiohazardSuit("BIOHAZARD_SUIT", { Armor(it.raw) }),
    BiohazardLeggings("BIOHAZARD_LEGGINGS", { Armor(it.raw) }),
    BiohazardBoots("BIOHAZARD_BOOTS", { Armor(it.raw) }),
    BlazeHelmet("BLAZE_HELMET", { Armor(it.raw) }),
    BlazeChestplate("BLAZE_CHESTPLATE", { Armor(it.raw) }),
    BlazeLeggings("BLAZE_LEGGINGS", { Armor(it.raw) }),
    BlazeBoots("BLAZE_BOOTS", { Armor(it.raw) }),
    BouncyHelmet("BOUNCY_HELMET", { Armor(it.raw) }),
    BouncyChestplate("BOUNCY_CHESTPLATE", { Armor(it.raw) }),
    BouncyLeggings("BOUNCY_LEGGINGS", { Armor(it.raw) }),
    BouncyBoots("BOUNCY_BOOTS", { Armor(it.raw) }),
    BronzeHunterHelmet("BRONZE_HUNTER_HELMET", { Armor(it.raw) }),
    BronzeHunterChestplate("BRONZE_HUNTER_CHESTPLATE", { Armor(it.raw) }),
    BronzeHunterLeggings("BRONZE_HUNTER_LEGGINGS", { Armor(it.raw) }),
    BronzeHunterBoots("BRONZE_HUNTER_BOOTS", { Armor(it.raw) }),
    CactusHelmet("CACTUS_HELMET", { Armor(it.raw) }),
    CactusChestplate("CACTUS_CHESTPLATE", { Armor(it.raw) }),
    CactusLeggings("CACTUS_LEGGINGS", { Armor(it.raw) }),
    CactusBoots("CACTUS_BOOTS", { Armor(it.raw) }),
    CelesteHelmet("CELESTE_HELMET", { Armor(it.raw) }),
    CelesteChestplate("CELESTE_CHESTPLATE", { Armor(it.raw) }),
    CelesteLeggings("CELESTE_LEGGINGS", { Armor(it.raw) }),
    CelesteBoots("CELESTE_BOOTS", { Armor(it.raw) }),
    ChainmailHelmet("CHAINMAIL_HELMET", { Armor(it.raw) }),
    ChainmailChestplate("CHAINMAIL_CHESTPLATE", { Armor(it.raw) }),
    ChainmailLeggings("CHAINMAIL_LEGGINGS", { Armor(it.raw) }),
    ChainmailBoots("CHAINMAIL_BOOTS", { Armor(it.raw) }),
    CheapTuxedoJacket("CHEAP_TUXEDO_CHESTPLATE", { Armor(it.raw) }),
    CheapTuxedoPants("CHEAP_TUXEDO_LEGGINGS", { Armor(it.raw) }),
    CheapTuxedoOxfords("CHEAP_TUXEDO_BOOTS", { Armor(it.raw) }),
    CrimsonHelmet("CRIMSON_HELMET", { Armor(it.raw) }),
    CrimsonChestplate("CRIMSON_CHESTPLATE", { Armor(it.raw) }),
    CrimsonLeggings("CRIMSON_LEGGINGS", { Armor(it.raw) }),
    CrimsonBoots("CRIMSON_BOOTS", { Armor(it.raw) }),
    HotCrimsonHelmet("HOT_CRIMSON_HELMET", { Armor(it.raw) }),
    HotCrimsonChestplate("HOT_CRIMSON_CHESTPLATE", { Armor(it.raw) }),
    HotCrimsonLeggings("HOT_CRIMSON_LEGGINGS", { Armor(it.raw) }),
    HotCrimsonBoots("HOT_CRIMSON_BOOTS", { Armor(it.raw) }),
    BurningCrimsonHelmet("BURNING_CRIMSON_HELMET", { Armor(it.raw) }),
    BurningCrimsonChestplate("BURNING_CRIMSON_CHESTPLATE", { Armor(it.raw) }),
    BurningCrimsonLeggings("BURNING_CRIMSON_LEGGINGS", { Armor(it.raw) }),
    BurningCrimsonBoots("BURNING_CRIMSON_BOOTS", { Armor(it.raw) }),
    FieryCrimsonHelmet("FIERY_CRIMSON_HELMET", { Armor(it.raw) }),
    FieryCrimsonChestplate("FIERY_CRIMSON_CHESTPLATE", { Armor(it.raw) }),
    FieryCrimsonLeggings("FIERY_CRIMSON_LEGGINGS", { Armor(it.raw) }),
    FieryCrimsonBoots("FIERY_CRIMSON_BOOTS", { Armor(it.raw) }),
    InfernalCrimsonHelmet("INFERNAL_CRIMSON_HELMET", { Armor(it.raw) }),
    InfernalCrimsonChestplate("INFERNAL_CRIMSON_CHESTPLATE", { Armor(it.raw) }),
    InfernalCrimsonLeggings("INFERNAL_CRIMSON_LEGGINGS", { Armor(it.raw) }),
    InfernalCrimsonBoots("INFERNAL_CRIMSON_BOOTS", { Armor(it.raw) }),
    CropieHelmet("CROPIE_HELMET", { Armor(it.raw) }),
    CropieChestplate("CROPIE_CHESTPLATE", { Armor(it.raw) }),
    CropieLeggings("CROPIE_LEGGINGS", { Armor(it.raw) }),
    CropieBoots("CROPIE_BOOTS", { Armor(it.raw) }),
    CrystalHelmet("CRYSTAL_HELMET", { Armor(it.raw) }),
    CrystalChestplate("CRYSTAL_CHESTPLATE", { Armor(it.raw) }),
    CrystalLeggings("CRYSTAL_LEGGINGS", { Armor(it.raw) }),
    CrystalBoots("CRYSTAL_BOOTS", { Armor(it.raw) }),
    DiamondHelmet("DIAMOND_HELMET", { Armor(it.raw) }),
    DiamondChestplate("DIAMOND_CHESTPLATE", { Armor(it.raw) }),
    DiamondLeggings("DIAMOND_LEGGINGS", { Armor(it.raw) }),
    DiamondBoots("DIAMOND_BOOTS", { Armor(it.raw) }),
    DiamondHunterHelmet("DIAMOND_HUNTER_HELMET", { Armor(it.raw) }),
    DiamondHunterChestplate("DIAMOND_HUNTER_CHESTPLATE", { Armor(it.raw) }),
    DiamondHunterLeggings("DIAMOND_HUNTER_LEGGINGS", { Armor(it.raw) }),
    DiamondHunterBoots("DIAMOND_HUNTER_BOOTS", { Armor(it.raw) }),
    DiversMask("DIVER_HELMET", { Armor(it.raw) }),
    DiversShirt("DIVER_CHESTPLATE", { Armor(it.raw) }),
    DiversTrunks("DIVER_LEGGINGS", { Armor(it.raw) }),
    DiversBoots("DIVER_BOOTS", { Armor(it.raw) }),
    EleanorsCap("ELEANOR_CAP", { Armor(it.raw) }),
    EleanorsTunic("ELEANOR_TUNIC", { Armor(it.raw) }),
    EleanorsTrousers("ELEANOR_TROUSERS", { Armor(it.raw) }),
    EleanorsSlippers("ELEANOR_SLIPPERS", { Armor(it.raw) }),
    ElegantTuxedoJacket("ELEGANT_TUXEDO_CHESTPLATE", { Armor(it.raw) }),
    ElegantTuxedoPants("ELEGANT_TUXEDO_LEGGINGS", { Armor(it.raw) }),
    ElegantTuxedoOxfords("ELEGANT_TUXEDO_BOOTS", { Armor(it.raw) }),
    EmberHelmet("EMBER_HELMET", { Armor(it.raw) }),
    EmberChestplate("EMBER_CHESTPLATE", { Armor(it.raw) }),
    EmberLeggings("EMBER_LEGGINGS", { Armor(it.raw) }),
    EmberBoots("EMBER_BOOTS", { Armor(it.raw) }),
    EmberAshHelmet("FLAMEBREAKER_HELMET", { Armor(it.raw) }),
    EmberAshChestplate("FLAMEBREAKER_CHESTPLATE", { Armor(it.raw) }),
    EmberAshLeggings("FLAMEBREAKER_LEGGINGS", { Armor(it.raw) }),
    EmberAshBoots("FLAMEBREAKER_BOOTS", { Armor(it.raw) }),
    EmeraldArmorHelmet("EMERALD_ARMOR_HELMET", { Armor(it.raw) }),
    EmeraldArmorChestplate("EMERALD_ARMOR_CHESTPLATE", { Armor(it.raw) }),
    EmeraldArmorLeggings("EMERALD_ARMOR_LEGGINGS", { Armor(it.raw) }),
    EmeraldArmorBoots("EMERALD_ARMOR_BOOTS", { Armor(it.raw) }),
    EnderHelmet("END_HELMET", { Armor(it.raw) }),
    EnderChestplate("END_CHESTPLATE", { Armor(it.raw) }),
    EnderLeggings("END_LEGGINGS", { Armor(it.raw) }),
    EnderBoots("END_BOOTS", { Armor(it.raw) }),
    FairysFedora("FAIRY_HELMET", { Armor(it.raw) }),
    FairysPolo("FAIRY_CHESTPLATE", { Armor(it.raw) }),
    FairysTrousers("FAIRY_LEGGINGS", { Armor(it.raw) }),
    FairysGaloshes("FAIRY_BOOTS", { Armor(it.raw) }),
    FancyTuxedoJacket("FANCY_TUXEDO_CHESTPLATE", { Armor(it.raw) }),
    FancyTuxedoPants("FANCY_TUXEDO_LEGGINGS", { Armor(it.raw) }),
    FancyTuxedoOxfords("FANCY_TUXEDO_BOOTS", { Armor(it.raw) }),
    FarmArmorHelmet("FARM_ARMOR_HELMET", { Armor(it.raw) }),
    FarmArmorChestplate("FARM_ARMOR_CHESTPLATE", { Armor(it.raw) }),
    FarmArmorLeggings("FARM_ARMOR_LEGGINGS", { Armor(it.raw) }),
    FarmArmorBoots("FARM_ARMOR_BOOTS", { Armor(it.raw) }),
    FarmSuitHelmet("FARM_SUIT_HELMET", { Armor(it.raw) }),
    FarmSuitChestplate("FARM_SUIT_CHESTPLATE", { Armor(it.raw) }),
    FarmSuitLeggings("FARM_SUIT_LEGGINGS", { Armor(it.raw) }),
    FarmSuitBoots("FARM_SUIT_BOOTS", { Armor(it.raw) }),
    FermentoHelmet("FERMENTO_HELMET", { Armor(it.raw) }),
    FermentoChestplate("FERMENTO_CHESTPLATE", { Armor(it.raw) }),
    FermentoLeggings("FERMENTO_LEGGINGS", { Armor(it.raw) }),
    FermentoBoots("FERMENTO_BOOTS", { Armor(it.raw) }),
    FervorHelmet("FERVOR_HELMET", { Armor(it.raw) }),
    FervorChestplate("FERVOR_CHESTPLATE", { Armor(it.raw) }),
    FervorLeggings("FERVOR_LEGGINGS", { Armor(it.raw) }),
    FervorBoots("FERVOR_BOOTS", { Armor(it.raw) }),
    HotFervorHelmet("HOT_FERVOR_HELMET", { Armor(it.raw) }),
    HotFervorChestplate("HOT_FERVOR_CHESTPLATE", { Armor(it.raw) }),
    HotFervorLeggings("HOT_FERVOR_LEGGINGS", { Armor(it.raw) }),
    HotFervorBoots("HOT_FERVOR_BOOTS", { Armor(it.raw) }),
    BurningFervorHelmet("BURNING_FERVOR_HELMET", { Armor(it.raw) }),
    BurningFervorChestplate("BURNING_FERVOR_CHESTPLATE", { Armor(it.raw) }),
    BurningFervorLeggings("BURNING_FERVOR_LEGGINGS", { Armor(it.raw) }),
    BurningFervorBoots("BURNING_FERVOR_BOOTS", { Armor(it.raw) }),
    FieryFervorHelmet("FIERY_FERVOR_HELMET", { Armor(it.raw) }),
    FieryFervorChestplate("FIERY_FERVOR_CHESTPLATE", { Armor(it.raw) }),
    FieryFervorLeggings("FIERY_FERVOR_LEGGINGS", { Armor(it.raw) }),
    FieryFervorBoots("FIERY_FERVOR_BOOTS", { Armor(it.raw) }),
    InfernalFervorHelmet("INFERNAL_FERVOR_HELMET", { Armor(it.raw) }),
    InfernalFervorChestplate("INFERNAL_FERVOR_CHESTPLATE", { Armor(it.raw) }),
    InfernalFervorLeggings("INFERNAL_FERVOR_LEGGINGS", { Armor(it.raw) }),
    InfernalFervorBoots("INFERNAL_FERVOR_BOOTS", { Armor(it.raw) }),
    FinalDestinationHelmet("FINAL_DESTINATION_HELMET", { Armor(it.raw) }),
    FinalDestinationChestplate("FINAL_DESTINATION_CHESTPLATE", { Armor(it.raw) }),
    FinalDestinationLeggings("FINAL_DESTINATION_LEGGINGS", { Armor(it.raw) }),
    FinalDestinationBoots("FINAL_DESTINATION_BOOTS", { Armor(it.raw) }),
    FlamebreakerHelmet("FLAME_BREAKER_HELMET", { Armor(it.raw) }),
    FlamebreakerChestplate("FLAME_BREAKER_CHESTPLATE", { Armor(it.raw) }),
    FlamebreakerLeggings("FLAME_BREAKER_LEGGINGS", { Armor(it.raw) }),
    FlamebreakerBoots("FLAME_BREAKER_BOOTS", { Armor(it.raw) }),
    FrozenBlazeHelmet("FROZEN_BLAZE_HELMET", { Armor(it.raw) }),
    FrozenBlazeChestplate("FROZEN_BLAZE_CHESTPLATE", { Armor(it.raw) }),
    FrozenBlazeLeggings("FROZEN_BLAZE_LEGGINGS", { Armor(it.raw) }),
    FrozenBlazeBoots("FROZEN_BLAZE_BOOTS", { Armor(it.raw) }),
    GlaciteHelmet("GLACITE_HELMET", { Armor(it.raw) }),
    GlaciteChestplate("GLACITE_CHESTPLATE", { Armor(it.raw) }),
    GlaciteLeggings("GLACITE_LEGGINGS", { Armor(it.raw) }),
    GlaciteBoots("GLACITE_BOOTS", { Armor(it.raw) }),
    GlossyMineralHelmet("GLOSSY_MINERAL_HELMET", { Armor(it.raw) }),
    GlossyMineralChestplate("GLOSSY_MINERAL_CHESTPLATE", { Armor(it.raw) }),
    GlossyMineralLeggings("GLOSSY_MINERAL_LEGGINGS", { Armor(it.raw) }),
    GlossyMineralBoots("GLOSSY_MINERAL_BOOTS", { Armor(it.raw) }),
    GoblinHelmet("GOBLIN_HELMET", { Armor(it.raw) }),
    GoblinChestplate("GOBLIN_CHESTPLATE", { Armor(it.raw) }),
    GoblinLeggings("GOBLIN_LEGGINGS", { Armor(it.raw) }),
    GoblinBoots("GOBLIN_BOOTS", { Armor(it.raw) }),
    GoldHunterHelmet("GOLD_HUNTER_HELMET", { Armor(it.raw) }),
    GoldHunterChestplate("GOLD_HUNTER_CHESTPLATE", { Armor(it.raw) }),
    GoldHunterLeggings("GOLD_HUNTER_LEGGINGS", { Armor(it.raw) }),
    GoldHunterBoots("GOLD_HUNTER_BOOTS", { Armor(it.raw) }),
    GoldenHelmet("GOLD_HELMET", { Armor(it.raw) }),
    GoldenChestplate("GOLD_CHESTPLATE", { Armor(it.raw) }),
    GoldenLeggings("GOLD_LEGGINGS", { Armor(it.raw) }),
    GoldenBoots("GOLD_BOOTS", { Armor(it.raw) }),
    GoldorsHelmet("TANK_WITHER_HELMET", { Armor(it.raw) }),
    GoldorsChestplate("TANK_WITHER_CHESTPLATE", { Armor(it.raw) }),
    GoldorsLeggings("TANK_WITHER_LEGGINGS", { Armor(it.raw) }),
    GoldorsBoots("TANK_WITHER_BOOTS", { Armor(it.raw) }),
    GolemArmorHelmet("GOLEM_ARMOR_HELMET", { Armor(it.raw) }),
    GolemArmorChestplate("GOLEM_ARMOR_CHESTPLATE", { Armor(it.raw) }),
    GolemArmorLeggings("GOLEM_ARMOR_LEGGINGS", { Armor(it.raw) }),
    GolemArmorBoots("GOLEM_ARMOR_BOOTS", { Armor(it.raw) }),
    GreatSpookHelmet("GREAT_SPOOK_HELMET", { Armor(it.raw) }),
    GreatSpookChestplate("GREAT_SPOOK_CHESTPLATE", { Armor(it.raw) }),
    GreatSpookLeggings("GREAT_SPOOK_LEGGINGS", { Armor(it.raw) }),
    GreatSpookBoots("GREAT_SPOOK_BOOTS", { Armor(it.raw) }),
    HardenedDiamondHelmet("HARDENED_DIAMOND_HELMET", { Armor(it.raw) }),
    HardenedDiamondChestplate("HARDENED_DIAMOND_CHESTPLATE", { Armor(it.raw) }),
    HardenedDiamondLeggings("HARDENED_DIAMOND_LEGGINGS", { Armor(it.raw) }),
    HardenedDiamondBoots("HARDENED_DIAMOND_BOOTS", { Armor(it.raw) }),
    HeatHelmet("HEAT_HELMET", { Armor(it.raw) }),
    HeatChestplate("HEAT_CHESTPLATE", { Armor(it.raw) }),
    HeatLeggings("HEAT_LEGGINGS", { Armor(it.raw) }),
    HeatBoots("HEAT_BOOTS", { Armor(it.raw) }),
    HeavyHelmet("HEAVY_HELMET", { Armor(it.raw) }),
    HeavyChestplate("HEAVY_CHESTPLATE", { Armor(it.raw) }),
    HeavyLeggings("HEAVY_LEGGINGS", { Armor(it.raw) }),
    HeavyBoots("HEAVY_BOOTS", { Armor(it.raw) }),
    HollowHelmet("HOLLOW_HELMET", { Armor(it.raw) }),
    HollowChestplate("HOLLOW_CHESTPLATE", { Armor(it.raw) }),
    HollowLeggings("HOLLOW_LEGGINGS", { Armor(it.raw) }),
    HollowBoots("HOLLOW_BOOTS", { Armor(it.raw) }),
    HotHollowHelmet("HOT_HOLLOW_HELMET", { Armor(it.raw) }),
    HotHollowChestplate("HOT_HOLLOW_CHESTPLATE", { Armor(it.raw) }),
    HotHollowLeggings("HOT_HOLLOW_LEGGINGS", { Armor(it.raw) }),
    HotHollowBoots("HOT_HOLLOW_BOOTS", { Armor(it.raw) }),
    BurningHollowHelmet("BURNING_HOLLOW_HELMET", { Armor(it.raw) }),
    BurningHollowChestplate("BURNING_HOLLOW_CHESTPLATE", { Armor(it.raw) }),
    BurningHollowLeggings("BURNING_HOLLOW_LEGGINGS", { Armor(it.raw) }),
    BurningHollowBoots("BURNING_HOLLOW_BOOTS", { Armor(it.raw) }),
    FieryHollowHelmet("FIERY_HOLLOW_HELMET", { Armor(it.raw) }),
    FieryHollowChestplate("FIERY_HOLLOW_CHESTPLATE", { Armor(it.raw) }),
    FieryHollowLeggings("FIERY_HOLLOW_LEGGINGS", { Armor(it.raw) }),
    FieryHollowBoots("FIERY_HOLLOW_BOOTS", { Armor(it.raw) }),
    InfernalHollowHelmet("INFERNAL_HOLLOW_HELMET", { Armor(it.raw) }),
    InfernalHollowChestplate("INFERNAL_HOLLOW_CHESTPLATE", { Armor(it.raw) }),
    InfernalHollowLeggings("INFERNAL_HOLLOW_LEGGINGS", { Armor(it.raw) }),
    InfernalHollowBoots("INFERNAL_HOLLOW_BOOTS", { Armor(it.raw) }),
    HolyDragonHelmet("HOLY_DRAGON_HELMET", { Armor(it.raw) }),
    HolyDragonChestplate("HOLY_DRAGON_CHESTPLATE", { Armor(it.raw) }),
    HolyDragonLeggings("HOLY_DRAGON_LEGGINGS", { Armor(it.raw) }),
    HolyDragonBoots("HOLY_DRAGON_BOOTS", { Armor(it.raw) }),
    IronHelmet("IRON_HELMET", { Armor(it.raw) }),
    IronChestplate("IRON_CHESTPLATE", { Armor(it.raw) }),
    IronLeggings("IRON_LEGGINGS", { Armor(it.raw) }),
    IronBoots("IRON_BOOTS", { Armor(it.raw) }),
    KuudraFollowerHelmet("KUUDRA_FOLLOWER_HELMET", { Armor(it.raw) }),
    KuudraFollowerChestplate("KUUDRA_FOLLOWER_CHESTPLATE", { Armor(it.raw) }),
    KuudraFollowerLeggings("KUUDRA_FOLLOWER_LEGGINGS", { Armor(it.raw) }),
    KuudraFollowerBoots("KUUDRA_FOLLOWER_BOOTS", { Armor(it.raw) }),
    LapisArmorHelmet("LAPIS_ARMOR_HELMET", { Armor(it.raw) }),
    LapisArmorChestplate("LAPIS_ARMOR_CHESTPLATE", { Armor(it.raw) }),
    LapisArmorLeggings("LAPIS_ARMOR_LEGGINGS", { Armor(it.raw) }),
    LapisArmorBoots("LAPIS_ARMOR_BOOTS", { Armor(it.raw) }),
    LeafletHat("LEAFLET_HELMET", { Armor(it.raw) }),
    LeafletTunic("LEAFLET_CHESTPLATE", { Armor(it.raw) }),
    LeafletPants("LEAFLET_LEGGINGS", { Armor(it.raw) }),
    LeafletSandals("LEAFLET_BOOTS", { Armor(it.raw) }),
    LeatherHelmet("LEATHER_HELMET", { Armor(it.raw) }),
    LeatherChestplate("LEATHER_CHESTPLATE", { Armor(it.raw) }),
    LeatherLeggings("LEATHER_LEGGINGS", { Armor(it.raw) }),
    LeatherBoots("LEATHER_BOOTS", { Armor(it.raw) }),
    MagmaLordHelmet("MAGMA_LORD_HELMET", { Armor(it.raw) }),
    MagmaLordChestplate("MAGMA_LORD_CHESTPLATE", { Armor(it.raw) }),
    MagmaLordLeggings("MAGMA_LORD_LEGGINGS", { Armor(it.raw) }),
    MagmaLordBoots("MAGMA_LORD_BOOTS", { Armor(it.raw) }),
    MastiffCrown("MASTIFF_HELMET", { Armor(it.raw) }),
    MastiffChestplate("MASTIFF_CHESTPLATE", { Armor(it.raw) }),
    MastiffLeggings("MASTIFF_LEGGINGS", { Armor(it.raw) }),
    MastiffBoots("MASTIFF_BOOTS", { Armor(it.raw) }),
    MaxorsHelmet("SPEED_WITHER_HELMET", { Armor(it.raw) }),
    MaxorsChestplate("SPEED_WITHER_CHESTPLATE", { Armor(it.raw) }),
    MaxorsLeggings("SPEED_WITHER_LEGGINGS", { Armor(it.raw) }),
    MaxorsBoots("SPEED_WITHER_BOOTS", { Armor(it.raw) }),
    MelonHelmet("MELON_HELMET", { Armor(it.raw) }),
    MelonChestplate("MELON_CHESTPLATE", { Armor(it.raw) }),
    MelonLeggings("MELON_LEGGINGS", { Armor(it.raw) }),
    MelonBoots("MELON_BOOTS", { Armor(it.raw) }),
    MercenaryHelmet("MERCENARY_HELMET", { Armor(it.raw) }),
    MercenaryChestplate("MERCENARY_CHESTPLATE", { Armor(it.raw) }),
    MercenaryLeggings("MERCENARY_LEGGINGS", { Armor(it.raw) }),
    MercenaryBoots("MERCENARY_BOOTS", { Armor(it.raw) }),
    MinerHelmet("TANK_MINER_HELMET", { Armor(it.raw) }),
    MinerChestplate("TANK_MINER_CHESTPLATE", { Armor(it.raw) }),
    MinerLeggings("TANK_MINER_LEGGINGS", { Armor(it.raw) }),
    MinerBoots("TANK_MINER_BOOTS", { Armor(it.raw) }),
    MineralHelmet("MINERAL_HELMET", { Armor(it.raw) }),
    MineralChestplate("MINERAL_CHESTPLATE", { Armor(it.raw) }),
    MineralLeggings("MINERAL_LEGGINGS", { Armor(it.raw) }),
    MineralBoots("MINERAL_BOOTS", { Armor(it.raw) }),
    MushroomHelmet("MUSHROOM_HELMET", { Armor(it.raw) }),
    MushroomChestplate("MUSHROOM_CHESTPLATE", { Armor(it.raw) }),
    MushroomLeggings("MUSHROOM_LEGGINGS", { Armor(it.raw) }),
    MushroomBoots("MUSHROOM_BOOTS", { Armor(it.raw) }),
    NecromancerLordHelmet("NECROMANCER_LORD_HELMET", { Armor(it.raw) }),
    NecromancerLordChestplate("NECROMANCER_LORD_CHESTPLATE", { Armor(it.raw) }),
    NecromancerLordLeggings("NECROMANCER_LORD_LEGGINGS", { Armor(it.raw) }),
    NecromancerLordBoots("NECROMANCER_LORD_BOOTS", { Armor(it.raw) }),
    NecronsHelmet("POWER_WITHER_HELMET", { Armor(it.raw) }),
    NecronsChestplate("POWER_WITHER_CHESTPLATE", { Armor(it.raw) }),
    NecronsLeggings("POWER_WITHER_LEGGINGS", { Armor(it.raw) }),
    NecronsBoots("POWER_WITHER_BOOTS", { Armor(it.raw) }),
    NutcrackerHelmet("NUTCRACKER_HELMET", { Armor(it.raw) }),
    NutcrackerChestplate("NUTCRACKER_CHESTPLATE", { Armor(it.raw) }),
    NutcrackerLeggings("NUTCRACKER_LEGGINGS", { Armor(it.raw) }),
    NutcrackerBoots("NUTCRACKER_BOOTS", { Armor(it.raw) }),
    OldDragonHelmet("OLD_DRAGON_HELMET", { Armor(it.raw) }),
    OldDragonChestplate("OLD_DRAGON_CHESTPLATE", { Armor(it.raw) }),
    OldDragonLeggings("OLD_DRAGON_LEGGINGS", { Armor(it.raw) }),
    OldDragonBoots("OLD_DRAGON_BOOTS", { Armor(it.raw) }),
    PerfectHelmetTierI("PERFECT_HELMET_1", { Armor(it.raw) }),
    PerfectChestplateTierI("PERFECT_CHESTPLATE_1", { Armor(it.raw) }),
    PerfectLeggingsTierI("PERFECT_LEGGINGS_1", { Armor(it.raw) }),
    PerfectBootsTierI("PERFECT_BOOTS_1", { Armor(it.raw) }),
    ProspectingHelmet("MINER_OUTFIT_HELMET", { Armor(it.raw) }),
    ProspectingChestplate("MINER_OUTFIT_CHESTPLATE", { Armor(it.raw) }),
    ProspectingLeggings("MINER_OUTFIT_LEGGINGS", { Armor(it.raw) }),
    ProspectingBoots("MINER_OUTFIT_BOOTS", { Armor(it.raw) }),
    ProtectorDragonHelmet("PROTECTOR_DRAGON_HELMET", { Armor(it.raw) }),
    ProtectorDragonChestplate("PROTECTOR_DRAGON_CHESTPLATE", { Armor(it.raw) }),
    ProtectorDragonLeggings("PROTECTOR_DRAGON_LEGGINGS", { Armor(it.raw) }),
    ProtectorDragonBoots("PROTECTOR_DRAGON_BOOTS", { Armor(it.raw) }),
    PumpkinHelmet("PUMPKIN_HELMET", { Armor(it.raw) }),
    PumpkinChestplate("PUMPKIN_CHESTPLATE", { Armor(it.raw) }),
    PumpkinLeggings("PUMPKIN_LEGGINGS", { Armor(it.raw) }),
    PumpkinBoots("PUMPKIN_BOOTS", { Armor(it.raw) }),
    RabbitHelmet("RABBIT_HELMET", { Armor(it.raw) }),
    RabbitChestplate("RABBIT_CHESTPLATE", { Armor(it.raw) }),
    RabbitLeggings("RABBIT_LEGGINGS", { Armor(it.raw) }),
    RabbitBoots("RABBIT_BOOTS", { Armor(it.raw) }),
    RampartHelmet("RAMPART_HELMET", { Armor(it.raw) }),
    RampartChestplate("RAMPART_CHESTPLATE", { Armor(it.raw) }),
    RampartLeggings("RAMPART_LEGGINGS", { Armor(it.raw) }),
    RampartBoots("RAMPART_BOOTS", { Armor(it.raw) }),
    ReaperChestplate("REAPER_CHESTPLATE", { Armor(it.raw) }),
    ReaperLeggings("REAPER_LEGGINGS", { Armor(it.raw) }),
    ReaperBoots("REAPER_BOOTS", { Armor(it.raw) }),
    RekindledEmberHelmet("REKINDLED_EMBER_HELMET", { Armor(it.raw) }),
    RekindledEmberChestplate("REKINDLED_EMBER_CHESTPLATE", { Armor(it.raw) }),
    RekindledEmberLeggings("REKINDLED_EMBER_LEGGINGS", { Armor(it.raw) }),
    RekindledEmberBoots("REKINDLED_EMBER_BOOTS", { Armor(it.raw) }),
    RevenantChestplate("REVENANT_CHESTPLATE", { Armor(it.raw) }),
    RevenantLeggings("REVENANT_LEGGINGS", { Armor(it.raw) }),
    RevenantBoots("REVENANT_BOOTS", { Armor(it.raw) }),
    RosettasHelmet("ROSETTA_HELMET", { Armor(it.raw) }),
    RosettasChestplate("ROSETTA_CHESTPLATE", { Armor(it.raw) }),
    RosettasLeggings("ROSETTA_LEGGINGS", { Armor(it.raw) }),
    RosettasBoots("ROSETTA_BOOTS", { Armor(it.raw) }),
    RottenHelmet("ROTTEN_HELMET", { Armor(it.raw) }),
    RottenChestplate("ROTTEN_CHESTPLATE", { Armor(it.raw) }),
    RottenLeggings("ROTTEN_LEGGINGS", { Armor(it.raw) }),
    RottenBoots("ROTTEN_BOOTS", { Armor(it.raw) }),
    SalmonHelmet("SALMON_HELMET_NEW", { Armor(it.raw) }),
    SalmonChestplate("SALMON_CHESTPLATE_NEW", { Armor(it.raw) }),
    SalmonLeggings("SALMON_LEGGINGS_NEW", { Armor(it.raw) }),
    SalmonBoots("SALMON_BOOTS_NEW", { Armor(it.raw) }),
    VelvetTopHat("VELVET_TOP_HAT", { Armor(it.raw) }),
    CashmereJacket("CASHMERE_JACKET", { Armor(it.raw) }),
    SatinTrousers("SATIN_TROUSERS", { Armor(it.raw) }),
    OxfordShoes("OXFORD_SHOES", { Armor(it.raw) }),
    ShadowAssassinHelmet("SHADOW_ASSASSIN_HELMET", { Armor(it.raw) }),
    ShadowAssassinChestplate("SHADOW_ASSASSIN_CHESTPLATE", { Armor(it.raw) }),
    ShadowAssassinLeggings("SHADOW_ASSASSIN_LEGGINGS", { Armor(it.raw) }),
    ShadowAssassinBoots("SHADOW_ASSASSIN_BOOTS", { Armor(it.raw) }),
    UpgradedShadowAssassinHelmet("STARRED_SHADOW_ASSASSIN_HELMET", { Armor(it.raw) }),
    UpgradedShadowAssassinChestplate("STARRED_SHADOW_ASSASSIN_CHESTPLATE", { Armor(it.raw) }),
    UpgradedShadowAssassinLeggings("STARRED_SHADOW_ASSASSIN_LEGGINGS", { Armor(it.raw) }),
    UpgradedShadowAssassinBoots("STARRED_SHADOW_ASSASSIN_BOOTS", { Armor(it.raw) }),
    SharkScaleHelmet("SHARK_SCALE_HELMET", { Armor(it.raw) }),
    SharkScaleChestplate("SHARK_SCALE_CHESTPLATE", { Armor(it.raw) }),
    SharkScaleLeggings("SHARK_SCALE_LEGGINGS", { Armor(it.raw) }),
    SharkScaleBoots("SHARK_SCALE_BOOTS", { Armor(it.raw) }),
    ShimmeringLightHood("SHIMMERING_LIGHT_HOOD", { Armor(it.raw) }),
    ShimmeringLightTunic("SHIMMERING_LIGHT_TUNIC", { Armor(it.raw) }),
    ShimmeringLightTrousers("SHIMMERING_LIGHT_TROUSERS", { Armor(it.raw) }),
    ShimmeringLightSlippers("SHIMMERING_LIGHT_SLIPPERS", { Armor(it.raw) }),
    SilverHunterHelmet("SILVER_HUNTER_HELMET", { Armor(it.raw) }),
    SilverHunterChestplate("SILVER_HUNTER_CHESTPLATE", { Armor(it.raw) }),
    SilverHunterLeggings("SILVER_HUNTER_LEGGINGS", { Armor(it.raw) }),
    SilverHunterBoots("SILVER_HUNTER_BOOTS", { Armor(it.raw) }),
    SkeletonGruntHelmet("SKELETON_GRUNT_HELMET", { Armor(it.raw) }),
    SkeletonGruntChestplate("SKELETON_GRUNT_CHESTPLATE", { Armor(it.raw) }),
    SkeletonGruntLeggings("SKELETON_GRUNT_LEGGINGS", { Armor(it.raw) }),
    SkeletonGruntBoots("SKELETON_GRUNT_BOOTS", { Armor(it.raw) }),
    SkeletonLordHelmet("SKELETON_LORD_HELMET", { Armor(it.raw) }),
    SkeletonLordChestplate("SKELETON_LORD_CHESTPLATE", { Armor(it.raw) }),
    SkeletonLordLeggings("SKELETON_LORD_LEGGINGS", { Armor(it.raw) }),
    SkeletonLordBoots("SKELETON_LORD_BOOTS", { Armor(it.raw) }),
    SkeletonMasterHelmet("SKELETON_MASTER_HELMET", { Armor(it.raw) }),
    SkeletonMasterChestplate("SKELETON_MASTER_CHESTPLATE", { Armor(it.raw) }),
    SkeletonMasterLeggings("SKELETON_MASTER_LEGGINGS", { Armor(it.raw) }),
    SkeletonMasterBoots("SKELETON_MASTER_BOOTS", { Armor(it.raw) }),
    SkeletonSoldierHelmet("SKELETON_SOLDIER_HELMET", { Armor(it.raw) }),
    SkeletonSoldierChestplate("SKELETON_SOLDIER_CHESTPLATE", { Armor(it.raw) }),
    SkeletonSoldierLeggings("SKELETON_SOLDIER_LEGGINGS", { Armor(it.raw) }),
    SkeletonSoldierBoots("SKELETON_SOLDIER_BOOTS", { Armor(it.raw) }),
    SkeletorHelmet("SKELETOR_HELMET", { Armor(it.raw) }),
    SkeletorChestplate("SKELETOR_CHESTPLATE", { Armor(it.raw) }),
    SkeletorLeggings("SKELETOR_LEGGINGS", { Armor(it.raw) }),
    SkeletorBoots("SKELETOR_BOOTS", { Armor(it.raw) }),
    SnowSuitHelmet("SNOW_SUIT_HELMET", { Armor(it.raw) }),
    SnowSuitChestplate("SNOW_SUIT_CHESTPLATE", { Armor(it.raw) }),
    SnowSuitLeggings("SNOW_SUIT_LEGGINGS", { Armor(it.raw) }),
    SnowSuitBoots("SNOW_SUIT_BOOTS", { Armor(it.raw) }),
    SorrowHelmet("SORROW_HELMET", { Armor(it.raw) }),
    SorrowChestplate("SORROW_CHESTPLATE", { Armor(it.raw) }),
    SorrowLeggings("SORROW_LEGGINGS", { Armor(it.raw) }),
    SorrowBoots("SORROW_BOOTS", { Armor(it.raw) }),
    SpeedsterHelmet("SPEEDSTER_HELMET", { Armor(it.raw) }),
    SpeedsterChestplate("SPEEDSTER_CHESTPLATE", { Armor(it.raw) }),
    SpeedsterLeggings("SPEEDSTER_LEGGINGS", { Armor(it.raw) }),
    SpeedsterBoots("SPEEDSTER_BOOTS", { Armor(it.raw) }),
    SpongeHelmet("SPONGE_HELMET", { Armor(it.raw) }),
    SpongeChestplate("SPONGE_CHESTPLATE", { Armor(it.raw) }),
    SpongeLeggings("SPONGE_LEGGINGS", { Armor(it.raw) }),
    SpongeShoes("SPONGE_BOOTS", { Armor(it.raw) }),
    SpookyHelmet("SPOOKY_HELMET", { Armor(it.raw) }),
    SpookyChestplate("SPOOKY_CHESTPLATE", { Armor(it.raw) }),
    SpookyLeggings("SPOOKY_LEGGINGS", { Armor(it.raw) }),
    SpookyBoots("SPOOKY_BOOTS", { Armor(it.raw) }),
    SquashHelmet("SQUASH_HELMET", { Armor(it.raw) }),
    SquashChestplate("SQUASH_CHESTPLATE", { Armor(it.raw) }),
    SquashLeggings("SQUASH_LEGGINGS", { Armor(it.raw) }),
    SquashBoots("SQUASH_BOOTS", { Armor(it.raw) }),
    SquireHelmet("SQUIRE_HELMET", { Armor(it.raw) }),
    SquireChestplate("SQUIRE_CHESTPLATE", { Armor(it.raw) }),
    SquireLeggings("SQUIRE_LEGGINGS", { Armor(it.raw) }),
    SquireBoots("SQUIRE_BOOTS", { Armor(it.raw) }),
    StarlightHelmet("STARLIGHT_HELMET", { Armor(it.raw) }),
    StarlightChestplate("STARLIGHT_CHESTPLATE", { Armor(it.raw) }),
    StarlightLeggings("STARLIGHT_LEGGINGS", { Armor(it.raw) }),
    StarlightBoots("STARLIGHT_BOOTS", { Armor(it.raw) }),
    StormsHelmet("WISE_WITHER_HELMET", { Armor(it.raw) }),
    StormsChestplate("WISE_WITHER_CHESTPLATE", { Armor(it.raw) }),
    StormsLeggings("WISE_WITHER_LEGGINGS", { Armor(it.raw) }),
    StormsBoots("WISE_WITHER_BOOTS", { Armor(it.raw) }),
    StrongDragonHelmet("STRONG_DRAGON_HELMET", { Armor(it.raw) }),
    StrongDragonChestplate("STRONG_DRAGON_CHESTPLATE", { Armor(it.raw) }),
    StrongDragonLeggings("STRONG_DRAGON_LEGGINGS", { Armor(it.raw) }),
    StrongDragonBoots("STRONG_DRAGON_BOOTS", { Armor(it.raw) }),
    SuperHeavyHelmet("SUPER_HEAVY_HELMET", { Armor(it.raw) }),
    SuperHeavyChestplate("SUPER_HEAVY_CHESTPLATE", { Armor(it.raw) }),
    SuperHeavyLeggings("SUPER_HEAVY_LEGGINGS", { Armor(it.raw) }),
    SuperHeavyBoots("SUPER_HEAVY_BOOTS", { Armor(it.raw) }),
    SuperiorDragonHelmet("SUPERIOR_DRAGON_HELMET", { Armor(it.raw) }),
    SuperiorDragonChestplate("SUPERIOR_DRAGON_CHESTPLATE", { Armor(it.raw) }),
    SuperiorDragonLeggings("SUPERIOR_DRAGON_LEGGINGS", { Armor(it.raw) }),
    SuperiorDragonBoots("SUPERIOR_DRAGON_BOOTS", { Armor(it.raw) }),
    TarantulaHelmet("TARANTULA_HELMET", { Armor(it.raw) }),
    TarantulaChestplate("TARANTULA_CHESTPLATE", { Armor(it.raw) }),
    TarantulaLeggings("TARANTULA_LEGGINGS", { Armor(it.raw) }),
    TarantulaBoots("TARANTULA_BOOTS", { Armor(it.raw) }),
    TerrorHelmet("TERROR_HELMET", { Armor(it.raw) }),
    TerrorChestplate("TERROR_CHESTPLATE", { Armor(it.raw) }),
    TerrorLeggings("TERROR_LEGGINGS", { Armor(it.raw) }),
    TerrorBoots("TERROR_BOOTS", { Armor(it.raw) }),
    HotTerrorHelmet("HOT_TERROR_HELMET", { Armor(it.raw) }),
    HotTerrorChestplate("HOT_TERROR_CHESTPLATE", { Armor(it.raw) }),
    HotTerrorLeggings("HOT_TERROR_LEGGINGS", { Armor(it.raw) }),
    HotTerrorBoots("HOT_TERROR_BOOTS", { Armor(it.raw) }),
    BurningTerrorHelmet("BURNING_TERROR_HELMET", { Armor(it.raw) }),
    BurningTerrorChestplate("BURNING_TERROR_CHESTPLATE", { Armor(it.raw) }),
    BurningTerrorLeggings("BURNING_TERROR_LEGGINGS", { Armor(it.raw) }),
    BurningTerrorBoots("BURNING_TERROR_BOOTS", { Armor(it.raw) }),
    FieryTerrorHelmet("FIERY_TERROR_HELMET", { Armor(it.raw) }),
    FieryTerrorChestplate("FIERY_TERROR_CHESTPLATE", { Armor(it.raw) }),
    FieryTerrorLeggings("FIERY_TERROR_LEGGINGS", { Armor(it.raw) }),
    FieryTerrorBoots("FIERY_TERROR_BOOTS", { Armor(it.raw) }),
    InfernalTerrorHelmet("INFERNAL_TERROR_HELMET", { Armor(it.raw) }),
    InfernalTerrorChestplate("INFERNAL_TERROR_CHESTPLATE", { Armor(it.raw) }),
    InfernalTerrorLeggings("INFERNAL_TERROR_LEGGINGS", { Armor(it.raw) }),
    InfernalTerrorBoots("INFERNAL_TERROR_BOOTS", { Armor(it.raw) }),
    ThunderHelmet("THUNDER_HELMET", { Armor(it.raw) }),
    ThunderChestplate("THUNDER_CHESTPLATE", { Armor(it.raw) }),
    ThunderLeggings("THUNDER_LEGGINGS", { Armor(it.raw) }),
    ThunderBoots("THUNDER_BOOTS", { Armor(it.raw) }),
    TitansHelmet("TITAN_HELMET", { Armor(it.raw) }),
    TitansChestplate("TITAN_CHESTPLATE", { Armor(it.raw) }),
    TitansLeggings("TITAN_LEGGINGS", { Armor(it.raw) }),
    TitansBoots("TITAN_BOOTS", { Armor(it.raw) }),
    UnstableDragonHelmet("UNSTABLE_DRAGON_HELMET", { Armor(it.raw) }),
    UnstableDragonChestplate("UNSTABLE_DRAGON_CHESTPLATE", { Armor(it.raw) }),
    UnstableDragonLeggings("UNSTABLE_DRAGON_LEGGINGS", { Armor(it.raw) }),
    UnstableDragonBoots("UNSTABLE_DRAGON_BOOTS", { Armor(it.raw) }),
    WerewolfHelmet("WEREWOLF_HELMET", { Armor(it.raw) }),
    WerewolfChestplate("WEREWOLF_CHESTPLATE", { Armor(it.raw) }),
    WerewolfLeggings("WEREWOLF_LEGGINGS", { Armor(it.raw) }),
    WerewolfBoots("WEREWOLF_BOOTS", { Armor(it.raw) }),
    WiseDragonHelmet("WISE_DRAGON_HELMET", { Armor(it.raw) }),
    WiseDragonChestplate("WISE_DRAGON_CHESTPLATE", { Armor(it.raw) }),
    WiseDragonLeggings("WISE_DRAGON_LEGGINGS", { Armor(it.raw) }),
    WiseDragonBoots("WISE_DRAGON_BOOTS", { Armor(it.raw) }),
    WitherHelmet("WITHER_HELMET", { Armor(it.raw) }),
    WitherChestplate("WITHER_CHESTPLATE", { Armor(it.raw) }),
    WitherLeggings("WITHER_LEGGINGS", { Armor(it.raw) }),
    WitherBoots("WITHER_BOOTS", { Armor(it.raw) }),
    WyldHelmetOnAHelmet("WYLD_HELMET", { Armor(it.raw) }),
    WyldChainTop("WYLD_CHESTPLATE", { Armor(it.raw) }),
    WyldLeggings("WYLD_LEGGINGS", { Armor(it.raw) }),
    WyldBoots("WYLD_BOOTS", { Armor(it.raw) }),
    YogHelmet("ARMOR_OF_YOG_HELMET", { Armor(it.raw) }),
    YogChestplate("ARMOR_OF_YOG_CHESTPLATE", { Armor(it.raw) }),
    YogLeggings("ARMOR_OF_YOG_LEGGINGS", { Armor(it.raw) }),
    YogBoots("ARMOR_OF_YOG_BOOTS", { Armor(it.raw) }),
    YoungDragonHelmet("YOUNG_DRAGON_HELMET", { Armor(it.raw) }),
    YoungDragonChestplate("YOUNG_DRAGON_CHESTPLATE", { Armor(it.raw) }),
    YoungDragonLeggings("YOUNG_DRAGON_LEGGINGS", { Armor(it.raw) }),
    YoungDragonBoots("YOUNG_DRAGON_BOOTS", { Armor(it.raw) }),
    ZombieChestplate("ZOMBIE_CHESTPLATE", { Armor(it.raw) }),
    ZombieLeggings("ZOMBIE_LEGGINGS", { Armor(it.raw) }),
    ZombieBoots("ZOMBIE_BOOTS", { Armor(it.raw) }),
    ZombieCommanderHelmet("ZOMBIE_COMMANDER_HELMET", { Armor(it.raw) }),
    ZombieCommanderChestplate("ZOMBIE_COMMANDER_CHESTPLATE", { Armor(it.raw) }),
    ZombieCommanderLeggings("ZOMBIE_COMMANDER_LEGGINGS", { Armor(it.raw) }),
    ZombieCommanderBoots("ZOMBIE_COMMANDER_BOOTS", { Armor(it.raw) }),
    ZombieKnightHelmet("ZOMBIE_KNIGHT_HELMET", { Armor(it.raw) }),
    ZombieKnightChestplate("ZOMBIE_KNIGHT_CHESTPLATE", { Armor(it.raw) }),
    ZombieKnightLeggings("ZOMBIE_KNIGHT_LEGGINGS", { Armor(it.raw) }),
    ZombieKnightBoots("ZOMBIE_KNIGHT_BOOTS", { Armor(it.raw) }),
    ZombieLordHelmet("ZOMBIE_LORD_HELMET", { Armor(it.raw) }),
    ZombieLordChestplate("ZOMBIE_LORD_CHESTPLATE", { Armor(it.raw) }),
    ZombieLordLeggings("ZOMBIE_LORD_LEGGINGS", { Armor(it.raw) }),
    ZombieLordBoots("ZOMBIE_LORD_BOOTS", { Armor(it.raw) }),
    ZombieSoldierHelmet("ZOMBIE_SOLDIER_HELMET", { Armor(it.raw) }),
    ZombieSoldierChestplate("ZOMBIE_SOLDIER_CHESTPLATE", { Armor(it.raw) }),
    ZombieSoldierLeggings("ZOMBIE_SOLDIER_LEGGINGS", { Armor(it.raw) }),
    ZombieSoldierBoots("ZOMBIE_SOLDIER_BOOTS", { Armor(it.raw) }),

    //Brewing Ingredient
    EnchantedCake("ENCHANTED_CAKE"),
    EnchantedRedstoneLamp("ENCHANTED_REDSTONE_LAMP"),
    FoulFlesh("FOUL_FLESH"),

    //Consumable
    DwarvenOsBlockBran("DWARVEN_OS_BLOCK_BRAN"),
    DwarvenOsGemstoneGrahams("DWARVEN_OS_GEMSTONE_GRAHAMS"),
    DwarvenOsMetallicMinis("DWARVEN_OS_METALLIC_MINIS"),
    DwarvenOsOreOats("DWARVEN_OS_ORE_OATS"),
    ToxicArrowPoison("TOXIC_ARROW_POISON"),
    TwilightArrowPoison("TWILIGHT_ARROW_POISON"),
    BlessedBait("BLESSED_BAIT"),
    CarrotBait("CARROT_BAIT"),
    CorruptedBait("CORRUPTED_BAIT"),
    DarkBait("DARK_BAIT"),
    FishBait("FISH_BAIT"),
    FrozenBait("FROZEN_BAIT"),
    GlowyChumBait("GLOWY_CHUM_BAIT"),
    GoldenBait("GOLDEN_BAIT"),
    HotBait("HOT_BAIT"),
    IceBait("ICE_BAIT"),
    LightBait("LIGHT_BAIT"),
    MinnowBait("MINNOW_BAIT"),
    SharkBait("SHARK_BAIT"),
    SpikedBait("SPIKED_BAIT"),
    SpookyBait("SPOOKY_BAIT"),
    WhaleBait("WHALE_BAIT"),
    WormBait("WORM_BAIT"),

    //Cosmetic TODO: Pet Skins, FireSales, Furniture, Helmet Skins, Reward Bundles, Runes, Sprays
    AutumnHutBarnSkin("AUTUMN_HUT_BARN_SKIN"),
    BambooBarnSkin("BAMBOO_BARN_SKIN"),
    BeachBallBarnSkin("BEACH_BALL_BARN_SKIN"),
    BeautifallCabinBarnSkin("BEAUTIFALL_CABIN_BARN_SKIN"),
    BingoDisplay("BINGO_DISPLAY"),
    BonzoStatue("BONZO_STATUE"),
    BookOfStats("BOOK_OF_STATS"),
    CastleBarnSkin("CASTLE_BARN_SKIN"),
    ChocolateFactoryBarnSkin("CHOCOLATE_FACTORY_BARN_SKIN"),
    CollectionDisplay("COLLECTION_DISPLAY"),
    CozyCottageBarnSkin("COZY_COTTAGE_BARN_SKIN"),
    CubeBarnSkin("CUBE_BARN_SKIN"),
    DittoBlob("DITTO_BLOB"),
    DittoSkin("DITTO_SKIN"),
    DittoSkull("DITTO_SKULL"),
    EnchantedNookBarnSkin("ENCHANTED_NOOK_BARN_SKIN"),
    FrogBarnSkin("FROG_BARN_SKIN"),
    GoldenDanteStatue("GOLDEN_DANTE_STATUE"),
    HiveBarnSkin("HIVE_BARN_SKIN"),
    JerryBarnSkin("JERRY_BARN_SKIN"),
    BlackLamp("LAMP_BLACK"),
    GrayLamp("LAMP_GRAY"),
    LightGrayLamp("LAMP_LIGHT_GRAY"),
    WhiteLamp("LAMP_WHITE"),
    BrownLamp("LAMP_BROWN"),
    OrangeLamp("LAMP_ORANGE"),
    RedLamp("LAMP_RED"),
    YellowLamp("LAMP_YELLOW"),
    PurpleLamp("LAMP_PURPLE"),
    MagentaLamp("LAMP_MAGENTA"),
    LilacLamp("LAMP_LILAC"),
    PinkLamp("LAMP_PINK"),
    GreenLamp("LAMP_GREEN"),
    LimeLamp("LAMP_LIME"),
    BlueLamp("LAMP_BLUE"),
    CyanLamp("LAMP_CYAN"),
    LightBlueLamp("LAMP_LIGHT_BLUE"),
    RainbowLamp("LAMP_RAINBOW"),
    LuckyBarnSkin("LUCKY_BARN_SKIN"),
    MainStreetBarnSkin("MAIN_STREET_BARN_SKIN"),
    MushroomBarnSkin("MUSHROOM_BARN_SKIN"),
    PesthuntersLairBarnSkin("PESTHUNTERS_LAIR_BARN_SKIN"),
    PinwheelHouseBarnSkin("PINWHEEL_HOUSE_BARN_SKIN"),
    SandCastleBarnSkin("SAND_CASTLE_BARN_SKIN"),
    TavernBarnSkin("TAVERN_BARN_SKIN"),
    TheEndBarnSkin("END_BARN_SKIN"),
    TownHallBarnSkin("TOWN_HALL_BARN_SKIN"),
    TradingPostBarnSkin("TRADING_POST_BARN_SKIN"),
    WindmillBarnSkin("WINDMILL_BARN_SKIN"),
    WinterBarnSkin("WINTER_BARN_BARN_SKIN"),
    WinterHomesteadBarnSkin("WINTER_HOMESTEAD_BARN_SKIN"),

    //Crafting Material - there are none

    //Drill Part
    AmberPolishedDrillEngine("AMBER_POLISHED_DRILL_ENGINE"),
    Biofuel("BIOFUEL"),
    BlueCheeseGoblinOmelette("GOBLIN_OMELETTE_BLUE_CHEESE"),
    GemstoneFuelTank("GEMSTONE_FUEL_TANK"),
    GoblinOmelette("GOBLIN_OMELETTE"),
    MithrilInfusedFuelTank("MITHRIL_FUEL_TANK"),
    OilBarrel("OIL_BARREL"),
    PerfectlyCutFuelTank("PERFECTLY_CUT_FUEL_TANK"),
    PestoGoblinOmelette("GOBLIN_OMELETTE_PESTO"),
    RubyPolishedDrillEngine("RUBY_POLISHED_DRILL_ENGINE"),
    SapphirePolishedDrillEngine("SAPPHIRE_POLISHED_DRILL_ENGINE"),
    SpicyGoblinOmelette("GOBLIN_OMELETTE_SPICY"),
    SunnySideGoblinOmelette("GOBLIN_OMELETTE_SUNNY_SIDE"),
    TitaniumInfusedFuelTank("TITANIUM_FUEL_TANK"),
    TitaniumPlatedDrillEngine("TITANIUM_DRILL_ENGINE"),

    //Equipment
    AdaptiveBelt("ADAPTIVE_BELT", { Gear(it.raw) }),
    AmberNecklace("AMBER_NECKLACE", { Gear(it.raw) }),
    AmethystGauntlet("AMETHYST_GAUNTLET", { Gear(it.raw) }),
    AncientCloak("ANCIENT_CLOAK", { Gear(it.raw) }),
    AnnihilationCloak("ANNIHILATION_CLOAK", { Gear(it.raw) }),
    ArachnesBelt("ARACHNE_BELT", { Gear(it.raw) }),
    ArachnesCloak("ARACHNE_CLOAK", { Gear(it.raw) }),
    ArachnesGloves("ARACHNE_GLOVES", { Gear(it.raw) }),
    ArachnesNecklace("ARACHNE_NECKLACE", { Gear(it.raw) }),
    BalloonSnake("BALLOON_SNAKE", { Gear(it.raw) }),
    BlackBelt("DOJO_BLACK_BELT", { Gear(it.raw) }),
    BlazeBelt("BLAZE_BELT", { Gear(it.raw) }),
    BlueBelt("DOJO_BLUE_BELT", { Gear(it.raw) }),
    BoneNecklace("BONE_NECKLACE", { Gear(it.raw) }),
    BrownBelt("DOJO_BROWN_BELT", { Gear(it.raw) }),
    ClayBracelet("CLAY_BRACELET", { Gear(it.raw) }),
    ClownfishCloak("CLOWNFISH_CLOAK", { Gear(it.raw) }),
    DeliriumNecklace("DELIRIUM_NECKLACE", { Gear(it.raw) }),
    DemonslayerGauntlet("DEMONLORD_GAUNTLET", { Gear(it.raw) }),
    DestructionCloak("DESTRUCTION_CLOAK", { Gear(it.raw) }),
    DisinfestorGloves("DISINFESTOR_GLOVES", { Gear(it.raw) }),
    DragonfadeCloak("DRAGONFADE_CLOAK", { Gear(it.raw) }),
    DragonfuseGlove("DRAGONFUSE_GLOVE", { Gear(it.raw) }),
    DwarvenHandwarmers("DWARVEN_HANDWARMERS", { Gear(it.raw) }),
    EnderBelt("ENDER_BELT", { Gear(it.raw) }),
    EnderCloak("ENDER_CLOAK", { Gear(it.raw) }),
    EnderGauntlet("ENDER_GAUNTLET", { Gear(it.raw) }),
    EnderNecklace("ENDER_NECKLACE", { Gear(it.raw) }),
    EnigmaCloak("ENIGMA_CLOAK", { Gear(it.raw) }),
    FinwaveBelt("FINWAVE_BELT", { Gear(it.raw) }),
    FinwaveCloak("FINWAVE_CLOAK", { Gear(it.raw) }),
    FinwaveGloves("FINWAVE_GLOVES", { Gear(it.raw) }),
    FlamingFist("FLAMING_FIST", { Gear(it.raw) }),
    FrozenAmulet("FROZEN_AMULET", { Gear(it.raw) }),
    GauntletOfContagion("GAUNTLET_OF_CONTAGION", { Gear(it.raw) }),
    GhastCloak("GHAST_CLOAK", { Gear(it.raw) }),
    GillsplashBelt("GILLSPLASH_BELT", { Gear(it.raw) }),
    GillsplashCloak("GILLSPLASH_CLOAK", { Gear(it.raw) }),
    GillsplashGloves("GILLSPLASH_GLOVES", { Gear(it.raw) }),
    GlowstoneGauntlet("GLOWSTONE_GAUNTLET", { Gear(it.raw) }),
    GoldenBelt("GOLDEN_BELT", { Gear(it.raw) }),
    GreatSpookBelt("GREAT_SPOOK_BELT", { Gear(it.raw) }),
    GreatSpookCloak("GREAT_SPOOK_CLOAK", { Gear(it.raw) }),
    GreatSpookGloves("GREAT_SPOOK_GLOVES", { Gear(it.raw) }),
    GreatSpookNecklace("GREAT_SPOOK_NECKLACE", { Gear(it.raw) }),
    GreenBelt("DOJO_GREEN_BELT", { Gear(it.raw) }),
    IchthyicBelt("ICHTHYIC_BELT", { Gear(it.raw) }),
    IchthyicCloak("ICHTHYIC_CLOAK", { Gear(it.raw) }),
    IchthyicGloves("ICHTHYIC_GLOVES", { Gear(it.raw) }),
    ImplosionBelt("IMPLOSION_BELT", { Gear(it.raw) }),
    JadeBelt("JADE_BELT", { Gear(it.raw) }),
    KnuckleSandwich("KNUCKLE_SANDWICH", { Gear(it.raw) }),
    LavaShellNecklace("LAVA_SHELL_NECKLACE", { Gear(it.raw) }),
    LeechBelt("LEECH_BELT", { Gear(it.raw) }),
    LotusBelt("LOTUS_BELT", { Gear(it.raw) }),
    LotusBracelet("LOTUS_BRACELET", { Gear(it.raw) }),
    LotusCloak("LOTUS_CLOAK", { Gear(it.raw) }),
    LotusNecklace("LOTUS_NECKLACE", { Gear(it.raw) }),
    LuminousBracelet("LUMINOUS_BRACELET", { Gear(it.raw) }),
    MagmaLordGauntlet("MAGMA_LORD_GAUNTLET", { Gear(it.raw) }),
    MagmaNecklace("MAGMA_NECKLACE", { Gear(it.raw) }),
    MithrilBelt("MITHRIL_BELT", { Gear(it.raw) }),
    MithrilCloak("MITHRIL_CLOAK", { Gear(it.raw) }),
    MithrilGauntlet("MITHRIL_GAUNTLET", { Gear(it.raw) }),
    MithrilNecklace("MITHRIL_NECKLACE", { Gear(it.raw) }),
    MoltenBelt("MOLTEN_BELT", { Gear(it.raw) }),
    MoltenBracelet("MOLTEN_BRACELET", { Gear(it.raw) }),
    MoltenCloak("MOLTEN_CLOAK", { Gear(it.raw) }),
    MoltenNecklace("MOLTEN_NECKLACE", { Gear(it.raw) }),
    PartyBelt("PARTY_BELT", { Gear(it.raw) }),
    PartyCloak("PARTY_CLOAK", { Gear(it.raw) }),
    PartyGloves("PARTY_GLOVES", { Gear(it.raw) }),
    PartyNecklace("PARTY_NECKLACE", { Gear(it.raw) }),
    PeltBelt("PELT_BELT", { Gear(it.raw) }),
    PendantOfDivan("DIVAN_PENDANT", { Gear(it.raw) }),
    PestVest("PEST_VEST", { Gear(it.raw) }),
    PesthuntersBelt("PESTHUNTERS_BELT", { Gear(it.raw) }),
    PesthuntersCloak("PESTHUNTERS_CLOAK", { Gear(it.raw) }),
    PesthuntersGloves("PESTHUNTERS_GLOVES", { Gear(it.raw) }),
    PesthuntersNecklace("PESTHUNTERS_NECKLACE", { Gear(it.raw) }),
    PrismarineNecklace("PRISMARINE_NECKLACE", { Gear(it.raw) }),
    RiftNecklace("RIFT_NECKLACE_OUTSIDE", { Gear(it.raw) }),
    RiftNecklaceInsideRift("RIFT_NECKLACE_INSIDE", { Gear(it.raw) }),
    SapphireCloak("SAPPHIRE_CLOAK", { Gear(it.raw) }),
    ScourgeCloak("SCOURGE_CLOAK", { Gear(it.raw) }),
    ScovilleBelt("SCOVILLE_BELT", { Gear(it.raw) }),
    ShadowAssassinCloak("SHADOW_ASSASSIN_CLOAK", { Gear(it.raw) }),
    ShensRingalia("SHENS_RINGALIA", { Gear(it.raw) }),
    SilkriderSafetyBelt("SILKRIDER_SAFETY_BELT", { Gear(it.raw) }),
    SnowBelt("SNOW_BELT", { Gear(it.raw) }),
    SnowCloak("SNOW_CLOAK", { Gear(it.raw) }),
    SnowGloves("SNOW_GLOVES", { Gear(it.raw) }),
    SnowNecklace("SNOW_NECKLACE", { Gear(it.raw) }),
    SoulweaverGloves("SOULWEAVER_GLOVES", { Gear(it.raw) }),
    SpongeBelt("SPONGE_BELT", { Gear(it.raw) }),
    SynthesizerV1("SYNTHESIZER_V1", { Gear(it.raw) }),
    SynthesizerV2("SYNTHESIZER_V2", { Gear(it.raw) }),
    SynthesizerV3("SYNTHESIZER_V3", { Gear(it.raw) }),
    TeraShellNecklace("TERA_SHELL_NECKLACE", { Gear(it.raw) }),
    ThunderboltNecklace("THUNDERBOLT_NECKLACE", { Gear(it.raw) }),
    TitaniumBelt("TITANIUM_BELT", { Gear(it.raw) }),
    TitaniumCloak("TITANIUM_CLOAK", { Gear(it.raw) }),
    TitaniumGauntlet("TITANIUM_GAUNTLET", { Gear(it.raw) }),
    TitaniumNecklace("TITANIUM_NECKLACE", { Gear(it.raw) }),
    UpgradedAdaptiveBelt("STARRED_ADAPTIVE_BELT", { Gear(it.raw) }),
    UpgradedBoneNecklace("STARRED_BONE_NECKLACE", { Gear(it.raw) }),
    UpgradedShadowAssassinCloak("STARRED_SHADOW_ASSASSIN_CLOAK", { Gear(it.raw) }),
    VanquishedBlazeBelt("VANQUISHED_BLAZE_BELT", { Gear(it.raw) }),
    VanquishedGhastCloak("VANQUISHED_GHAST_CLOAK", { Gear(it.raw) }),
    VanquishedGlowstoneGauntlet("VANQUISHED_GLOWSTONE_GAUNTLET", { Gear(it.raw) }),
    VanquishedMagmaNecklace("VANQUISHED_MAGMA_NECKLACE", { Gear(it.raw) }),
    VerminBelt("VERMIN_BELT", { Gear(it.raw) }),
    WhiteBelt("DOJO_WHITE_BELT", { Gear(it.raw) }),
    YellowBelt("DOJO_YELLOW_BELT", { Gear(it.raw) }),
    ZorrosCape("ZORROS_CAPE", { Gear(it.raw) }),

    //Forgeable Item TODO

    //Item Sack
    SmallAgronomySack("SMALL_AGRONOMY_SACK"),
    MediumAgronomySack("MEDIUM_AGRONOMY_SACK"),
    LargeAgronomySack("LARGE_AGRONOMY_SACK"),
    LargeEnchantedAgronomySack("LARGE_ENCHANTED_AGRONOMY_SACK"),
    BronzeTrophyFishingSack("BRONZE_TROPHY_FISHING_SACK"),
    SilverTrophyFishingSack("SILVER_TROPHY_FISHING_SACK"),
    SmallCombatSack("SMALL_COMBAT_SACK"),
    MediumCombatSack("MEDIUM_COMBAT_SACK"),
    LargeCombatSack("LARGE_COMBAT_SACK"),
    LargeEnchantedCombatSack("LARGE_ENCHANTED_COMBAT_SACK"),
    CrystalHollowsSack("CRYSTAL_HOLLOWS_SACK"),
    SmallDragonSack("SMALL_DRAGON_SACK"),
    MediumDragonSack("MEDIUM_DRAGON_SACK"),
    LargeDragonSack("LARGE_DRAGON_SACK"),
    DungeonSack("LARGE_DUNGEON_SACK"),
    DwarvenSack("DWARVEN_MINES_SACK"),
    SmallFishingSack("SMALL_FISHING_SACK"),
    MediumFishingSack("MEDIUM_FISHING_SACK"),
    LargeFishingSack("LARGE_FISHING_SACK"),
    LargeEnchantedFishingSack("LARGE_ENCHANTED_FISHING_SACK"),
    FlowerSack("FLOWER_SACK"),
    SmallForagingSack("SMALL_FORAGING_SACK"),
    MediumForagingSack("MEDIUM_FORAGING_SACK"),
    LargeForagingSack("LARGE_FORAGING_SACK"),
    LargeEnchantedForagingSack("LARGE_ENCHANTED_FORAGING_SACK"),
    GardenSack("GARDEN_SACK"),
    SmallGemstoneSack("SMALL_GEMSTONE_SACK"),
    MediumGemstoneSack("MEDIUM_GEMSTONE_SACK"),
    LargeGemstoneSack("LARGE_GEMSTONE_SACK"),
    SmallHusbandrySack("SMALL_HUSBANDRY_SACK"),
    MediumHusbandrySack("MEDIUM_HUSBANDRY_SACK"),
    LargeHusbandrySack("LARGE_HUSBANDRY_SACK"),
    LargeEnchantedHusbandrySack("LARGE_ENCHANTED_HUSBANDRY_SACK"),
    SmallLavaFishingSack("SMALL_LAVA_FISHING_SACK"),
    MediumLavaFishingSack("MEDIUM_LAVA_FISHING_SACK"),
    LargeLavaFishingSack("LARGE_LAVA_FISHING_SACK"),
    SmallMiningSack("SMALL_MINING_SACK"),
    MediumMiningSack("MEDIUM_MINING_SACK"),
    LargeMiningSack("LARGE_MINING_SACK"),
    LargeEnchantedMiningSack("LARGE_ENCHANTED_MINING_SACK"),
    SmallNetherSack("SMALL_NETHER_SACK"),
    MediumNetherSack("MEDIUM_NETHER_SACK"),
    LargeNetherSack("LARGE_NETHER_SACK"),
    RuneSack("RUNE_SACK"),
    SmallSlayerSack("SMALL_SLAYER_SACK"),
    MediumSlayerSack("MEDIUM_SLAYER_SACK"),
    LargeSlayerSack("LARGE_SLAYER_SACK"),
    SpookySack("LARGE_CANDY_SACK"),
    WinterSack("LARGE_WINTER_SACK"),

    //Memento
    BasketOfHope("POTATO_BASKET"),
    BingosSecrets("SECRET_BINGO_MEMENTO"),
    CakeSliceOfTheCentury("CENTURY_MEMENTO_RED"),
    CampaignPoster("CAMPAIGN_POSTER"),
    ExpensiveToy("EXPENSIVE_TOY"),
    FrenchBread("FRENCH_BREAD"),
    GoldenCollar("GOLDEN_COLLAR"),
    LockedBallotBox("LOCKED_BALLOT_BOX"),
    MoldyMuffin("MOLDY_MUFFIN"),
    PaintersPalette("PAINTERS_PALETTE"),
    PieceOfWizardPortal("WIZARD_PORTAL_MEMENTO"),
    ShinyRelic("SHINY_RELIC"),
    ThereAndBackAgain("RIFT_COMPLETION_MEMENTO"),

    //Minion

    //Mixin - there are none

    //Pet

    //Potion

    //Power Stone
    AcaciaBirdhouse("ACACIA_BIRDHOUSE"),
    BeatingHeart("BEATING_HEART"),
    BubbaBlister("BUBBA_BLISTER"),
    DarkOrb("DARK_ORB"),
    DisplacedLeech("DISPLACED_LEECH"),
    EccentricPainting("ECCENTRIC_PAINTING"),
    EndStoneShulker("END_STONE_SHULKER"),
    EnderMonocle("ENDER_MONOCLE"),
    FangtasticChocolateChip("CHOCOLATE_CHIP"),
    Furball("FURBALL"),
    GlaciteShard("GLACITE_SHARD"),
    HazmatEnderman("HAZMAT_ENDERMAN"),
    HornsOfTorment("HORNS_OF_TORMENT"),
    LuxuriousSpool("LUXURIOUS_SPOOL"),
    MagmaUrchin("MAGMA_URCHIN"),
    Mandraa("MANDRAA"),
    ObsidianTablet("OBSIDIAN_TABLET"),
    PreciousPearl("PRECIOUS_PEARL"),
    RockCandy("ROCK_CANDY"),
    ScorchedBooks("SCORCHED_BOOKS"),
    VitaminDeath("VITAMIN_DEATH"),

    //Reforge Stone

    //Rift Item
    AgaricusCapBunch("AGARICUS_CAP_BUNCH"),
    AgaricusChumcap("AGARICUS_CHUM_CAP"),
    AgaricusSoup("AGARICUS_SOUP"),
    AgarimooTongue("AGARIMOO_TONGUE"),
    AntiMorphPotion("ANTI_MORPH_POTION"),
    BacteFragment("BACTE_FRAGMENT"),
    BarrysMontgrayPen("BARRY_PEN"),
    BerberisBlowgun("BERBERIS_BLOWGUN"),
    BerberisFuelInjector("BERBERIS_FUEL_INJECTOR"),
    Bloodbadge("BLOODBADGE"),
    BottledOdonata("BOTTLED_ODONATA"),
    CaducousExtract("CADUCOUS_EXTRACT"),
    CaducousFeeder("CADUCOUS_FEEDER"),
    CaducousLegume("CADUCOUS_LEGUME"),
    CaducousStemBunch("CADUCOUS_STEM_BUNCH"),
    CovenSeal("COVEN_SEAL"),
    Cruxmotion("CRUXMOTION"),
    DaeL("MIRRORED_LEASH"),
    DarkPebble("DARK_PEBBLE"),
    DeadCatDetector("DEAD_CAT_DETECTOR"),
    DeadgehogSpine("DEADGEHOG_SPINE"),
    DetectiveScanner("DETECTIVE_SCANNER"),
    Discrite("DISCRITE"),
    DoRgnihsiF("MIRRORED_FISHING_ROD"),
    DoubloonOfTheFamily("FAMILY_DOUBLOON"),
    EmmettPointer("EMMETT_POINTER"),
    EmptyChumcapBucket("EMPTY_CHUMCAP_BUCKET"),
    EmptyOdonataBottle("EMPTY_ODONATA_BOTTLE"),
    EnchantedClock("ENCHANTED_TIME_CLOCK"),
    EnchantedVampiricMelon("ENCHANTED_VAMPIRIC_MELON"),
    ExportableCarrots("EXPORTABLE_CARROTS"),
    ExtremelyRealShuriken("FAKE_SHURIKEN"),
    FakeNeuroscienceDegree("FAKE_NEUROSCIENCE_DEGREE"),
    FreeWill("FREE_WILL"),
    FrostyCrux("FROSTY_CRUX"),
    FrozenWater("FROZEN_WATER"),
    FrozenWaterPungi("FROZEN_WATER_PUNGI"),
    GnirtS("MIRRORED_STRING"),
    GuardianLuckyBlock("GUARDIAN_LUCKY_BLOCK"),
    GunthesizerLichen("GUNTHESIZER_LICHEN"),
    HealingMelon("HEALING_MELON"),
    Hemobomb("HEMOBOMB"),
    Hemoglass("HEMOGLASS"),
    Highlite("HIGHLITE"),
    HolyIce("HOLY_ICE"),
    Horsezooka("HORSEZOOKA"),
    HotDog("HOT_DOG"),
    JinxedVoodooDoll("VOODOO_DOLL_WILTED"),
    JuicyHealingMelon("JUICY_HEALING_MELON"),
    JumpElixir("RIFT_JUMP_ELIXIR"),
    KcitS("MIRRORED_STICK"),
    KeyToInfestedHouseSoul("KEY_TO_KAT_SOUL"),
    KnalPdooWkaO("MIRRORED_WOOD"),
    LarvaHook("LARVA_HOOK"),
    LarvaSilk("LARVA_SILK"),
    LeechSupremeFragment("LEECH_SUPREME_FRAGMENT"),
    LilPad("LIL_PAD"),
    LivingMetal("LIVING_METAL"),
    LivingMetalAnchor("LIVING_METAL_ANVIL"),
    LivingMetalBootspawn("LM_EGG_BOOTS"),
    LivingMetalCapspawn("LM_EGG_CAP"),
    LivingMetalChestspawn("LM_EGG_CHEST"),
    LivingMetalPantspawn("LM_EGG_LEGS"),
    LlabemilS("MIRRORED_SLIME_BALL"),
    LusciousHealingMelon("LUSCIOUS_HEALING_MELON"),
    McGrubbersBurger("MCGRUBBER_BURGER"),
    MetaphoricEgg("METAPHORIC_EGG"),
    MutedBark("MUTED_BARK"),
    NearlyCoherentdoRgnihsiF("NEARLY_COHERENT_ROD"),
    NearlyWholeCarrot("NEARLY_WHOLE_CARROT"),
    NullifiedMetal("NULLIFIED_METAL"),
    Obsolite("OBSOLITE"),
    PlaceableFairySoul("PLACEABLE_FAIRY_SOUL_RIFT"),
    PlumbersBucket("RIFT_BUCKET"),
    PolarvoidBook("POLARVOID_BOOK"),
    Postcard("POSTCARD"),
    PreDigestionFish("PRE_DIGESTION_FISH"),
    ProtoChicken("PROTOCHICKEN"),
    PuffCrux("PUFF_CRUX"),
    RemmaHyniT("TINY_HAMMER"),
    RemoteTimeChamberRemote("REMOTE_TIME_CHAMBER_REMOTE"),
    RiftBoat("REED_BOAT"),
    RiftwartRoots("RIFTWART_ROOTS"),
    ScribeCrux("SCRIBE_CRUX"),
    ShadowCrux("SHADOW_CRUX"),
    ShyCrux("SHAME_CRUX"),
    SilkwireStick("SILKWIRE_STICK"),
    SpeedElixir("RIFT_SPEED_ELIXIR"),
    SplatterCrux("SPLATTER_CRUX"),
    Spotlite("SPOTLITE"),
    StabilityElixir("RIFT_STABILITY_ELIXIR"),
    StrengthElixir("RIFT_STRENGTH_ELIXIR"),
    SuperLeechModifier("SUPER_LEECH_MODIFIER"),
    TightPantsFragment("TIGHT_PANTS_FRAGMENT"),
    TimeGun("TIME_GUN"),
    TreelikeWool("BEDWARS_WOOL"),
    TurbomaxVacuumCleaner("TURBOMAX_VACUUM"),
    UbiksCube("UBIKS_CUBE"),
    UglyBootsFragment("UGLY_BOOTS_FRAGMENT"),
    UnfangedVampirePart("UNFANGED_VAMPIRE_PART"),
    VampiricMelon("VAMPIRIC_MELON"),
    VeryScientificPaper("VERY_SCIENTIFIC_PAPER"),
    VoltCrux("VOLT_CRUX"),
    WLogoFragment("S_LOGO_FRAGMENT"),
    WardingDiamathame("WAND_OF_WARDING"),
    WiltedBerberisBunch("WILTED_BERBERIS_BUNCH"),
    WizardsBreadcrumbs("WIZARD_BREADCRUMBS"),
    Youngite("YOUNGITE"),
    ZoopTheFish("ZOOP_THE_FISH"),

    //Rift Timecharm
    CelestialTimecharm("RIFT_TROPHY_MOUNTAIN"),
    ChickenNEggTimecharm("RIFT_TROPHY_CHICKEN_N_EGG"),
    GlobulateTimecharm("RIFT_TROPHY_SLIME"),
    LivingTimecharm("RIFT_TROPHY_LAZY_LIVING"),
    MirrorverseTimecharm("RIFT_TROPHY_MIRRORED"),
    SkyBlockCitizenTimecharm("RIFT_TROPHY_CITIZEN"),
    SupremeTimecharm("RIFT_TROPHY_WYLDLY_SUPREME"),
    VampiricTimecharm("RIFT_TROPHY_VAMPIRIC"),

    //Shears
    EnchantedShears("ENCHANTED_SHEARS", { Gear(it.raw) }),
    MobysShears("MOBYS_SHEARS", { Gear(it.raw) }),
    Shears("SHEARS", { Gear(it.raw) }),

    //Tool

    //Vanilla Item TODO: https://wiki.hypixel.net/Decorative_Block_Variations
    ActivatorRail("ACTIVATOR_RAIL"),
    Anvil("ANVIL"),
    Apple("APPLE"),
    BakedPotato("BAKED_POTATO"),
    BoneMeal("INK_SACK:15"),
    Bread("BREAD"),
    BrewingStand("BREWING_STAND_ITEM"),
    CactusGreen("INK_SACK:2"),
    Cake("CAKE"),
    Carrot("CARROT_ITEM"),
    Clownfish("RAW_FISH:2"),
    CocoaBeans("INK_SACK:3"),
    Comparator("REDSTONE_COMPARATOR"),
    CookedChicken("COOKED_CHICKEN"),
    CookedFish("COOKED_FISH"),
    CookedMutton("COOKED_MUTTON"),
    CookedPorkchop("GRILLED_PORK"),
    CookedRabbit("COOKED_RABBIT"),
    CookedSalmon("COOKED_FISH:1"),
    Cookie("COOKIE"),
    CyanDye("INK_SACK:6"),
    DandelionYellow("INK_SACK:11"),
    DaylightSensor("DAYLIGHT_DETECTOR"),
    DetectorRail("DETECTOR_RAIL"),
    Dispenser("DISPENSER"),
    Dropper("DROPPER"),
    Egg("EGG"),
    EmptyMap("EMPTY_MAP"),
    EnchantedGoldenApple("GOLDEN_APPLE:1"),
    EyeOfEnder("EYE_OF_ENDER"),
    FermentedSpiderEye("FERMENTED_SPIDER_EYE"),
    Flint("FLINT"),
    GlisteringMelon("SPECKLED_MELON"),
    GoldenApple("GOLDEN_APPLE"),
    GoldenCarrot("GOLDEN_CARROT"),
    GrayDye("INK_SACK:8"),
    HayBale("HAY_BLOCK"),
    HeavyWeightedPressurePlate("IRON_PLATE"),
    Hopper("HOPPER"),
    InkSac("INK_SACK"),
    IronTrapdoor("IRON_TRAPDOOR"),
    LapisLazuli("INK_SACK:4"),
    Lever("LEVER"),
    LightBlueDye("INK_SACK:12"),
    LightGrayDye("INK_SACK:7"),
    LightWeightedPressurePlate("GOLD_PLATE"),
    LimeDye("INK_SACK:10"),
    MagentaDye("INK_SACK:13"),
    Melon("MELON"),
    Minecart("MINECART"),
    MinecartWithChest("STORAGE_MINECART"),
    MinecartWithCommandBlock("COMMAND_MINECART"),
    MinecartWithFurnace("POWERED_MINECART"),
    MinecartWithHopper("HOPPER_MINECART"),
    MinecartWithTNT("EXPLOSIVE_MINECART"),
    MushroomStew("MUSHROOM_SOUP"),
    Mutton("MUTTON"),
    OrangeDye("INK_SACK:14"),
    PinkDye("INK_SACK:9"),
    Piston("PISTON_BASE"),
    PoisonousPotato("POISONOUS_POTATO"),
    Potato("POTATO_ITEM"),
    PoweredRail("POWERED_RAIL"),
    Pufferfish("RAW_FISH:3"),
    PumpkinPie("PUMPKIN_PIE"),
    PurpleDye("INK_SACK:5"),
    RabbitHide("RABBIT_HIDE"),
    RabbitStew("RABBIT_STEW"),
    RabbitsFoot("RABBIT_FOOT"),
    Rail("RAILS"),
    RawBeef("RAW_BEEF"),
    RawChicken("RAW_CHICKEN"),
    RawFish("RAW_FISH"),
    RawPorkchop("PORK"),
    RawRabbit("RABBIT"),
    RawSalmon("RAW_FISH:1"),
    RedstoneLamp("REDSTONE_LAMP_OFF"),
    RedstoneTorch("REDSTONE_TORCH_ON"),
    Repeater("DIODE"),
    RoseRed("INK_SACK:1"),
    RottenFlesh("ROTTEN_FLESH"),
    SpiderEye("SPIDER_EYE"),
    Steak("COOKED_BEEF"),
    StickyPiston("PISTON_STICKY_BASE"),
    StonePressurePlate("STONE_PLATE"),
    Sugar("SUGAR"),
    TNT("TNT"),
    TrappedChest("TRAPPED_CHEST"),
    TripwireHook("TRIPWIRE_HOOK"),
    WoodenPressurePlate("WOOD_PLATE"),
    WoodenTrapdoor("TRAP_DOOR"),
    Bed("BED"),
    Bookshelf("BOOKSHELF"),
    Boat("BOAT"),
    Cauldron("CAULDRON_ITEM"),
    Furnace("FURNACE"),
    ItemFrame("ITEM_FRAME"),
    Torch("TORCH"),
    Web("WEB"),
    BrownMushroomBlock("HUGE_MUSHROOM_1"),
    RedMushroomBlock("HUGE_MUSHROOM_2"),
    MelonBlock("MELON_BLOCK"),
    JackoLantern("JACK_O_LANTERN"),
    BlazePowder("BLAZE_POWDER"),
    Book("BOOK"),
    Bowl("BOWL"),
    Bucket("BUCKET"),
    CarrotOnAStick("CARROT_STICK"),
    Clock("WATCH"),
    Compass("COMPASS"),
    ExperienceBottle("EXP_BOTTLE"),
    FlintAndSteel("FLINT_AND_STEEL"),
    GlassBottle("GLASS_BOTTLE"),
    GoldNugget("GOLD_NUGGET"),
    LavaBucket("LAVA_BUCKET"),
    Lead("LEASH"),
    MelonSeeds("MELON_SEEDS"),
    MilkBucket("MILK_BUCKET"),
    NetherBrick("NETHER_BRICK_ITEM"),
    Paper("PAPER"),
    PumpkinSeeds("PUMPKIN_SEEDS"),
    Snowball("SNOW_BALL"),
    Stick("STICK"),
    WaterBucket("WATER_BUCKET"),
    WaterBottle("POTION"),
    FireworkRocket("FIREWORK"),
    OakWoodPlanks("WOOD"),
    SpruceWoodPlanks("WOOD:1"),
    BirchWoodPlanks("WOOD:2"),
    JungleWoodPlanks("WOOD:3"),
    DarkOakWoodPlanks("WOOD:5"),
    AcaciaWoodPlanks("WOOD:4"),
    OakWoodSlab("WOOD_STEP"),
    SpruceWoodSlab("WOOD_STEP:1"),
    BirchWoodSlab("WOOD_STEP:2"),
    JungleWoodSlab("WOOD_STEP:3"),
    DarkOakWoodSlab("WOOD_STEP:5"),
    AcaciaWoodSlab("WOOD_STEP:4"),
    OakWoodStairs("WOOD_STAIRS"),
    SpruceWoodStairs("SPRUCE_WOOD_STAIRS"),
    BirchWoodStairs("BIRCH_WOOD_STAIRS"),
    JungleWoodStairs("JUNGLE_WOOD_STAIRS"),
    DarkOakWoodStairs("DARK_OAK_STAIRS"),
    AcaciaWoodStairs("ACACIA_STAIRS"),
    OakFence("FENCE"),
    SpruceFence("SPRUCE_FENCE"),
    BirchFence("BIRCH_FENCE"),
    JungleFence("JUNGLE_FENCE"),
    DarkOakFence("DARK_OAK_FENCE"),
    AcaciaFence("ACACIA_FENCE"),
    OakFenceGate("FENCE_GATE"),
    SpruceFenceGate("SPRUCE_FENCE_GATE"),
    BirchFenceGate("BIRCH_FENCE_GATE"),
    JungleFenceGate("JUNGLE_FENCE_GATE"),
    DarkOakFenceGate("DARK_OAK_FENCE_GATE"),
    AcaciaFenceGate("ACACIA_FENCE_GATE"),
    OakDoor("WOOD_DOOR"),
    SpruceDoor("SPRUCE_DOOR_ITEM"),
    BirchDoor("BIRCH_DOOR_ITEM"),
    JungleDoor("JUNGLE_DOOR_ITEM"),
    DarkOakDoor("DARK_OAK_DOOR_ITEM"),
    AcaciaDoor("ACACIA_DOOR_ITEM"),
    Ladder("LADDER"),
    CraftingTable("WORKBENCH"),
    Chest("CHEST"),
    Stone("STONE"),
    Granite("STONE:1"),
    PolishedGranite("STONE:2"),
    Diorite("STONE:3"),
    PolishedDiorite("STONE:4"),
    Andesite("STONE:5"),
    PolishedAndesite("STONE:6"),
    StoneSlab("STEP"),
    CobblestoneSlab("STEP:3"),
    CobblestoneStairs("COBBLESTONE_STAIRS"),
    CobblestoneWall("COBBLE_WALL"),
    MossyCobblestoneWall("COBBLE_WALL:1"),
    MossStone("MOSSY_COBBLESTONE"),
    MossyStoneBricks("SMOOTH_BRICK:1"),
    StoneBrickSlab("STEP:5"),
    StoneBrickStairs("SMOOTH_STAIRS"),
    StoneBricks("SMOOTH_BRICK"),
    CrackedStoneBricks("SMOOTH_BRICK:2"),
    ChiseledStoneBricks("SMOOTH_BRICK:3"),
    SandstoneSlab("STEP:1"),
    SandstoneStairs("SANDSTONE_STAIRS"),
    Sandstone("SANDSTONE"),
    SmoothSandstone("SANDSTONE:2"),
    ChiseledSandstone("SANDSTONE:1"),
    RedSandstoneSlab("STONE_SLAB2"),
    RedSandstoneStairs("RED_SANDSTONE_STAIRS"),
    RedSandstone("RED_SANDSTONE"),
    RedSmoothSandstone("RED_SANDSTONE:2"),
    RedChiseledSandstone("RED_SANDSTONE:1"),
    QuartzSlab("STEP:7"),
    QuartzStairs("QUARTZ_STAIRS"),
    BlockOfQuartz("QUARTZ_BLOCK"),
    ChiseledQuartzBlock("QUARTZ_BLOCK:1"),
    PillarQuartzBlock("QUARTZ_BLOCK:2"),
    NetherBrickSlab("STEP:6"),
    NetherBrickStair("NETHER_BRICK_STAIRS"),
    NetherBricks("NETHER_BRICK"),
    NetherBrickFence("NETHER_FENCE"),
    SoulSand("SOUL_SAND"),
    Glowstone("GLOWSTONE"),
    Dirt("DIRT"),
    CoarseDirt("DIRT:1"),
    Podzol("DIRT:2"),
    Grass("GRASS"),
    Clay("CLAY"),

    //Wand
    AspectOfTheLeechUncommon("ASPECT_OF_THE_LEECH_1", { Gear(it.raw) }),
    AspectOfTheLeechRare("ASPECT_OF_THE_LEECH_2", { Gear(it.raw) }),
    AspectOfTheLeechEpic("ASPECT_OF_THE_LEECH_3", { Gear(it.raw) }),
    BingoBlaster("BINGO_BLASTER", { Gear(it.raw) }),
    CelesteWand("CELESTE_WAND", { Gear(it.raw) }),
    FireVeilWand("FIRE_VEIL_WAND", { Gear(it.raw) }),
    GyrokineticWand("GYROKINETIC_WAND", { Gear(it.raw) }),
    HellstormWand("HELLSTORM_STAFF", { Gear(it.raw) }),
    HollowWand("HOLLOW_WAND", { Gear(it.raw) }),
    StaffOfTheRisingMoon("STAFF_OF_THE_RISING_MOON"),
    StaffOfTheRisingSun("HOPE_OF_THE_RESISTANCE", { Gear(it.raw) }),
    GeneralsStaffOfTheRisingSun("GENERALS_HOPE_OF_THE_RESISTANCE", { Gear(it.raw) }),
    StaffOfTheVolcano("STAFF_OF_THE_VOLCANO", { Gear(it.raw) }),
    StarlightWand("STARLIGHT_WAND", { Gear(it.raw) }),
    TheAlchemistsStaff("ALCHEMISTS_STAFF", { Gear(it.raw) }),
    WandOfAtonement("WAND_OF_ATONEMENT", { Gear(it.raw) }),
    WandOfFarming("FARMING_WAND"),
    WandOfHealing("WAND_OF_HEALING", { Gear(it.raw) }),
    WandOfMending("WAND_OF_MENDING", { Gear(it.raw) }),
    WandOfRestoration("WAND_OF_RESTORATION", { Gear(it.raw) }),
    WandOfStrength("WAND_OF_STRENGTH", { Gear(it.raw) }),
    WizardWand("WIZARD_WAND", { Gear(it.raw) }),

    //Weapon
    PhantomRod("PHANTOM_ROD", { Gear(it.raw) }),
    Shredder("THE_SHREDDER", { Gear(it.raw) }),
    Hyperion("HYPERION", { WitherBlade(it.raw) }),
    Valkyrie("VALKYRIE", { WitherBlade(it.raw) }),
    Scylla("SCYLLA", { WitherBlade(it.raw) }),
    Astraea("ASTRAEA", { WitherBlade(it.raw) }),
    NecronBlade("NECRON_BLADE", { WitherBlade(it.raw) }),
    Terminator("TERMINATOR", { Terminator(it.raw) }),

    //Misc
    KuudraKey("KUUDRA_TIER_KEY"),
    HotKuudraKey("KUUDRA_HOT_TIER_KEY"),
    BurningKuudraKey("KUUDRA_BURNING_TIER_KEY"),
    FieryKuudraKey("KUUDRA_FIERY_TIER_KEY"),
    InfernalKuudraKey("KUUDRA_INFERNAL_TIER_KEY"),
    TarantulaSilk("TARANTULA_SILK"),


    EnchantedBook("ENCHANTED_BOOK", { EnchantedBook(it.raw) }),
    GlossyMineralHelmetRoyalSkin("GLOSSY_MINERAL_HELMET_ROYAL"),
    CarnivalTicket("CARNIVAL_TICKET"),
    GreaterBackpack("GREATER_BACKPACK"),
    Recombobulator3000("RECOMBOBULATOR_3000"),
    UltimateCarrotCandyUpgrade("ULTIMATE_CARROT_CANDY_UPGRADE"),
    FlintArrow("ARROW"),
    ShatteredLocket("SHATTERED_PENDANT"),
    RadiantPowerOrb("RADIANT_POWER_ORB", { Deployable(it.raw) }),
    ManaFluxPowerOrb("MANA_FLUX_POWER_ORB", { Deployable(it.raw) }),
    OverfluxPowerOrb("OVERFLUX_POWER_ORB", { Deployable(it.raw) }),
    PlasmafluxPowerOrb("PLASMAFLUX_POWER_ORB", { Deployable(it.raw) }),
    WarningFlare("WARNING_FLARE", { Deployable(it.raw) }),
    AlertFlare("ALERT_FLARE", { Deployable(it.raw) }),
    SOSFlare("SOS_FLARE", { Deployable(it.raw) }),
    BuildersWand("BUILDERS_WAND", { BuildersWand(it.raw) }),
    AspectOfTheVoid("ASPECT_OF_THE_VOID"),
    RodOfTheSea("ROD_OF_THE_SEA"),
    SkyblockMenu("SKYBLOCK_MENU"),
    GrandExpBottle("GRAND_EXP_BOTTLE"),
    TitanicExpBottle("TITANIC_EXP_BOTTLE"),
    InfernoRod("INFERNO_ROD"),
    DivansDrill("DIVAN_DRILL"),
    Pickonimbus("PICKONIMBUS"),
    RoyalPigeon("ROYAL_PIGEON"),
    RoyalCompass("ROYAL_COMPASS"),
    DwarvenMetalDetector("DWARVEN_METAL_DETECTOR"),
    Treecapitator("TREECAPITATOR_AXE"),
    SkeletonKey("SKELETON_KEY"),
    IceSprayWand("ICE_SPRAY_WAND"),
    DaedalusAxe("DAEDALUS_AXE"),
    FireFreezeStaff("FIRE_FREEZE_STAFF"),
    Stonk("STONK_PICKAXE"),
    MoodyGrappleshot("MOODY_GRAPPLESHOT"),
    BobOmb("BOB_OMB"),
    Infinileap("INFINITE_SPIRIT_LEAP"),
    InfinityboomTNT("INFINITE_SUPERBOOM_TNT"),
    RunaansBow("RUNAANS_BOW"),
    AncestralSpade("ANCESTRAL_SPADE"),
    NecronsHandle("NECRON_HANDLE"),
    LunarPigmanSkin("PET_SKIN_PIGMAN_LUNAR_PIG"),
    Sprayonator("SPRAYONATOR"),
    CocoChopper("COCO_CHOPPER"),
    FungiCutter("FUNGI_CUTTER"),
    SqueakyMousemat("SQUEAKY_MOUSEMAT"),
    Pet("PET", { PetAsItem(it.raw) }),
    PoochSword("POOCH_SWORD"),
    SapphirePowerScroll("SAPPHIRE_POWER_SCROLL"),
    PerfectChisel("PERFECT_CHISEL"),
    ScareFragment("SCARE_FRAGMENT"),
    ExpShareCore("PET_ITEM_EXP_SHARE_DROP"),
    NullEdge("NULL_EDGE"),
    NullBlade("NULL_BLADE"),
    JudgementCore("JUDGEMENT_CORE"),
    JumboBackpack("JUMBO_BACKPACK"),
    RodOfLegends("LEGEND_ROD"),
    AbiphoneXPlus("ABIPHONE_X_PLUS"),
    AbiphoneXPlusSpecialEdition("ABIPHONE_X_PLUS_SPECIAL_EDITION"),
    AbiphoneXIUltra("ABIPHONE_XI_ULTRA"),
    AbiphoneXIUltraStyle("ABIPHONE_XI_ULTRA_STYLE"),
    AbiphoneXIIMega("ABIPHONE_XII_MEGA"),
    AbiphoneXIIMegaColor("ABIPHONE_XII_MEGA_COLOR"),
    AbiphoneXIIIPro("ABIPHONE_XIII_PRO"),
    AbiphoneXIIIProGiga("ABIPHONE_XIII_PRO_GIGA"),
    AbiphoneXIVEnormous("ABIPHONE_XIV_ENORMOUS"),
    AbiphoneXIVEnormousPurple("ABIPHONE_XIV_ENORMOUS_PURPLE"),
    AbiphoneXIVEnormousBlack("ABIPHONE_XIV_ENORMOUS_BLACK"),
    AbiphoneFlipDragon("ABIPHONE_FLIP_DRAGON"),
    AbiphoneFlipNucleus("ABIPHONE_FLIP_NUCLEUS"),
    AbiphoneFlipVolcano("ABIPHONE_FLIP_VOLCANO"),
    AbiphoneBingo("ABINGOPHONE"),
    MithrilDrillSxR326("MITHRIL_DRILL_2");

    constructor(apiName: String) : this(apiName, { it })

    class UnknownSkyblockItemId(override val apiName: String) : SkyblockItemId

    companion object {
        fun fromApiName(apiName: String): SkyblockItemId {
            return KnownSkyblockItemId.entries.firstOrNull { it.apiName == apiName } ?: UnknownSkyblockItemId(apiName)
        }
    }
}