package net.dungeonhub.hypixel.entities.inventory.items

enum class KnownEnchantment(
    override val apiName: String,
    val ultimate: Boolean,
    val stacking: Boolean,
    vararg targets: EnchantmentTarget
) : Enchantment {
    Angler("angler", false, false, EnchantmentTarget.FishingRods),
    AquaAffinity("aqua_affinity", false, false, EnchantmentTarget.Armor),
    BaneOfArthropods("bane_of_arthropods", false, false, EnchantmentTarget.Swords),
    BigBrain("big_brain", false, false, EnchantmentTarget.Armor),
    BlastProtection("blast_protection", false, false, EnchantmentTarget.Armor),
    Blessing("blessing", false, false, EnchantmentTarget.FishingRods),
    Caster("caster", false, false, EnchantmentTarget.FishingRods),
    Cayenne("cayenne", false, false, EnchantmentTarget.Equipment),
    Champion("champion", false, true, EnchantmentTarget.Swords),
    Chance("chance", false, false, EnchantmentTarget.Bows),
    Charm("charm", false, false, EnchantmentTarget.FishingRods),
    Cleave("cleave", false, false, EnchantmentTarget.Swords),
    Compact("compact", false, true, EnchantmentTarget.Tools),
    Corruption("corruption", false, false, EnchantmentTarget.FishingRods),
    CounterStrike("counter_strike", false, false, EnchantmentTarget.Armor),
    Critical("critical", false, false, EnchantmentTarget.Swords),
    Cubism("cubism", false, false, EnchantmentTarget.Swords, EnchantmentTarget.Bows),
    Cultivating("cultivating", false, true, EnchantmentTarget.Tools),
    Dedication("dedication", false, false, EnchantmentTarget.Tools),
    Delicate("delicate", false, false, EnchantmentTarget.Tools),
    DepthStrider("depth_strider", false, false, EnchantmentTarget.Armor),
    DivineGift("divine_gift", false, false, EnchantmentTarget.Swords, EnchantmentTarget.Bows),
    DragonHunter("dragon_hunter", false, false, EnchantmentTarget.Swords, EnchantmentTarget.Bows),
    DragonTracer("aiming", false, false, EnchantmentTarget.Bows),
    Efficiency("efficiency", false, false, EnchantmentTarget.Tools),
    EnderSlayer("ender_slayer", false, false, EnchantmentTarget.Swords),
    Execute("execute", false, false, EnchantmentTarget.Swords),
    Experience("experience", false, false, EnchantmentTarget.Swords, EnchantmentTarget.Tools),
    Expertise("expertise", false, true, EnchantmentTarget.FishingRods),
    FeatherFalling("feather_falling", false, false, EnchantmentTarget.Armor),
    FerociousMana("ferocious_mana", false, false, EnchantmentTarget.Armor),
    FireAspect("fire_aspect", false, false, EnchantmentTarget.Swords),
    FireProtection("fire_protection", false, false, EnchantmentTarget.Armor),
    FirstStrike("first_strike", false, false, EnchantmentTarget.Swords),
    Flame("flame", false, false, EnchantmentTarget.Bows),
    Fortune("fortune", false, false, EnchantmentTarget.Tools),
    Frail("frail", false, false, EnchantmentTarget.FishingRods),
    FrostWalker("frost_walker", false, false, EnchantmentTarget.Armor),
    GiantKiller("giant_killer", false, false, EnchantmentTarget.Swords),
    GreatSpook("great_spook", false, false, EnchantmentTarget.Armor),
    GreenThumb("green_thumb", false, false, EnchantmentTarget.Equipment),
    Growth("growth", false, false, EnchantmentTarget.Armor),
    HardenedMana("hardened_mana", false, false, EnchantmentTarget.Armor),
    Harvesting("harvesting", false, false, EnchantmentTarget.Tools),
    Hecatomb("hecatomb", false, true, EnchantmentTarget.Armor),
    IceCold("ice_cold", false, false, EnchantmentTarget.Armor),
    Impaling("impaling", false, false, EnchantmentTarget.Swords, EnchantmentTarget.Bows, EnchantmentTarget.FishingRods),
    InfiniteQuiver("infinite_quiver", false, false, EnchantmentTarget.Bows),
    Knockback("knockback", false, false, EnchantmentTarget.Swords),
    Lapidary("lapidary", false, false, EnchantmentTarget.Tools),
    Lethality("lethality", false, false, EnchantmentTarget.Swords),
    LifeSteal("life_steal", false, false, EnchantmentTarget.Swords),
    Looting("looting", false, false, EnchantmentTarget.Swords, EnchantmentTarget.FishingRods),
    Luck("luck", false, false, EnchantmentTarget.Swords),
    LuckOfTheSea("luck_of_the_sea", false, false, EnchantmentTarget.FishingRods),
    Lure("lure", false, false, EnchantmentTarget.FishingRods),
    Magnet("magnet", false, false, EnchantmentTarget.FishingRods),
    ManaSteal("mana_steal", false, false, EnchantmentTarget.Swords),
    ManaVampire("mana_vampire", false, false, EnchantmentTarget.Armor),
    Overload("overload", false, false, EnchantmentTarget.Bows),
    Paleontologist("paleontologist", false, false, EnchantmentTarget.Tools),
    Pesterminator("pesterminator", false, false, EnchantmentTarget.Armor),
    Piercing("piercing", false, false, EnchantmentTarget.Bows),
    Piscary("piscary", false, false, EnchantmentTarget.FishingRods),
    Power("power", false, false, EnchantmentTarget.Bows),
    Prismatic("pristine", false, false, EnchantmentTarget.Tools),
    ProjectileProtection("projectile_protection", false, false, EnchantmentTarget.Armor),
    Prosecute("prosecute", false, false, EnchantmentTarget.Swords),
    Prosperity("prosperity", false, false, EnchantmentTarget.Equipment),
    Protection("protection", false, false, EnchantmentTarget.Armor),
    Punch("punch", false, false, EnchantmentTarget.Bows),
    Quantum("quantum", false, false, EnchantmentTarget.Equipment),
    QuickBite("quick_bite", false, false, EnchantmentTarget.FishingRods),
    Rainbow("rainbow", false, false, EnchantmentTarget.Tools),
    Reflection("reflection", false, false, EnchantmentTarget.Armor),
    Rejuvenate("rejuvenate", false, false, EnchantmentTarget.Armor),
    Replenish("replenish", false, false, EnchantmentTarget.Tools),
    Respiration("respiration", false, false, EnchantmentTarget.Armor),
    Respite("respite", false, false, EnchantmentTarget.Armor),
    Scavenger("scavenger", false, false, EnchantmentTarget.Swords),
    Sharpness("sharpness", false, false, EnchantmentTarget.Swords),
    SilkTouch("silk_touch", false, false, EnchantmentTarget.Tools),
    SmallBrain("small_brain", false, false, EnchantmentTarget.Armor),
    SmartyPants("smarty_pants", false, false, EnchantmentTarget.Armor),
    SmeltingTouch("smelting_touch", false, false, EnchantmentTarget.Tools),
    Smite("smite", false, false, EnchantmentTarget.Swords),
    Smoldering("smoldering", false, false, EnchantmentTarget.Swords, EnchantmentTarget.Bows),
    Snipe("snipe", false, false, EnchantmentTarget.Bows),
    SpikedHook("spiked_hook", false, false, EnchantmentTarget.FishingRods),
    StrongMana("strong_mana", false, false, EnchantmentTarget.Armor),
    SugarRush("sugar_rush", false, false, EnchantmentTarget.Armor),
    Sunder("sunder", false, false, EnchantmentTarget.Tools),
    Syphon("syphon", false, false, EnchantmentTarget.Swords),
    Tabasco(
        "tabasco",
        false,
        false,
        EnchantmentTarget.Swords,
        EnchantmentTarget.Bows,
        EnchantmentTarget.FishingRods,
        EnchantmentTarget.Tools
    ),
    Thorns("thorns", false, false, EnchantmentTarget.Armor),
    Thunderbolt("thunderbolt", false, false, EnchantmentTarget.Swords),
    Thunderlord("thunderlord", false, false, EnchantmentTarget.Swords),
    Tidal("tidal", false, false, EnchantmentTarget.Armor),
    TitanKiller("titan_killer", false, false, EnchantmentTarget.Swords),
    Toxophilite("toxophilite", false, true, EnchantmentTarget.Bows),
    Transylvanian("transylvanian", false, false, EnchantmentTarget.Armor),
    TripleStrike("triple_strike", false, false, EnchantmentTarget.Swords),
    TrueProtection("true_protection", false, false, EnchantmentTarget.Armor),
    TurboCacti("turbo_cactus", false, false, EnchantmentTarget.Tools),
    TurboCane("turbo_cane", false, false, EnchantmentTarget.Tools),
    TurboCarrot("turbo_carrot", false, false, EnchantmentTarget.Tools),
    TurboCocoa("turbo_coco", false, false, EnchantmentTarget.Tools),
    TurboMelon("turbo_melon", false, false, EnchantmentTarget.Tools),
    TurboMushrooms("turbo_mushrooms", false, false, EnchantmentTarget.Tools),
    TurboPotato("turbo_potato", false, false, EnchantmentTarget.Tools),
    TurboPumpkin("turbo_pumpkin", false, false, EnchantmentTarget.Tools),
    TurboWarts("turbo_warts", false, false, EnchantmentTarget.Tools),
    TurboWheat("turbo_wheat", false, false, EnchantmentTarget.Tools),
    Vampirism("vampirism", false, false, EnchantmentTarget.Swords),
    Venomous("venomous", false, false, EnchantmentTarget.Swords),
    Vicious("vicious", false, false, EnchantmentTarget.Swords, EnchantmentTarget.Bows),

    Bank("ultimate_bank", true, false, EnchantmentTarget.Armor),
    BobbinTime("ultimate_bobbin_time", true, false, EnchantmentTarget.Armor),
    Chimera("ultimate_chimera", true, false, EnchantmentTarget.Swords),
    Combo("ultimate_combo", true, false, EnchantmentTarget.Swords),
    Duplex("ultimate_reiterate", true, false, EnchantmentTarget.Bows),
    FatalTempo(
        "ultimate_fatal_tempo",
        true,
        false,
        EnchantmentTarget.Swords,
        EnchantmentTarget.Bows,
        EnchantmentTarget.FishingRods,
        EnchantmentTarget.Tools
    ),
    Flash("ultimate_flash", true, false, EnchantmentTarget.FishingRods),
    Flowstate("ultimate_flowstate", true, false, EnchantmentTarget.Tools),
    HabaneroTactics("ultimate_habanero_tactics", true, false, EnchantmentTarget.Armor),
    Inferno(
        "ultimate_inferno",
        true,
        false,
        EnchantmentTarget.Swords,
        EnchantmentTarget.Bows,
        EnchantmentTarget.FishingRods,
        EnchantmentTarget.Tools
    ),
    LastStand("ultimate_last_stand", true, false, EnchantmentTarget.Armor),
    Legion("ultimate_legion", true, false, EnchantmentTarget.Armor),
    NoPainNoGain("ultimate_no_pain_no_gain", true, false, EnchantmentTarget.Armor),
    OneForAll("ultimate_one_for_all", true, false, EnchantmentTarget.Swords),
    Refrigerate("ultimate_refrigerate", true, false, EnchantmentTarget.Armor),
    Rend("ultimate_rend", true, false, EnchantmentTarget.Bows),
    SoulEater("ultimate_soul_eater", true, false, EnchantmentTarget.Swords, EnchantmentTarget.Bows),
    Swarm("ultimate_swarm", true, false, EnchantmentTarget.Swords, EnchantmentTarget.Bows),
    TheOne("ultimate_the_one", true, false, EnchantmentTarget.Equipment),
    UltimateJerry("ultimate_jerry", true, false, EnchantmentTarget.Swords),
    UltimateWise(
        "ultimate_wise",
        true,
        false,
        EnchantmentTarget.Swords,
        EnchantmentTarget.Bows,
        EnchantmentTarget.Wands,
        EnchantmentTarget.FishingRods,
        EnchantmentTarget.Tools
    ),
    Wisdom("ultimate_wisdom", true, false, EnchantmentTarget.Armor);

    val displayName = name.replace(Regex("([A-Z])"), " $1").trim()

    enum class DeprecatedEnchantment(
        override val apiName: String,
        val ultimate: Boolean,
        vararg targets: EnchantmentTarget
    ) : Enchantment {
        Telekinesis(
            "telekinesis", false, EnchantmentTarget.Swords, EnchantmentTarget.Bows, EnchantmentTarget.Tools,
            EnchantmentTarget.FishingRods, EnchantmentTarget.Wands
        );
    }

    enum class EnchantmentTarget {
        Swords,
        Bows,
        Armor,
        Tools,
        FishingRods,
        Wands,
        Equipment;
    }

    class UnknownEnchantment(override val apiName: String) : Enchantment

    companion object {
        fun fromApiName(apiName: String): Enchantment {
            return KnownEnchantment.entries.firstOrNull {
                it.apiName == apiName
            } ?: DeprecatedEnchantment.entries.firstOrNull {
                it.apiName == apiName
            } ?: UnknownEnchantment(apiName)
        }
    }
}