package net.dungeonhub.hypixel.entities.skyblock.pet

enum class KnownPetType(override val apiName: String) : PetType {
    Ammonite("AMMONITE"),
    Ankylosaurus("ANKYLOSAURUS"),
    Armadillo("ARMADILLO"),
    BabyYeti("BABY_YETI"),
    Bal("BAL"),
    Bat("BAT"),
    Bee("BEE"),
    Bingo("BINGO"),
    BlackCat("BLACK_CAT"),
    Blaze("BLAZE"),
    BlueWhale("BLUE_WHALE"),
    Chicken("CHICKEN"),
    Dolphin("DOLPHIN"),
    DropletWisp("DROPLET_WISP"),
    Eerie("EERIE"),
    Elephant("ELEPHANT"),
    EnderDragon("ENDER_DRAGON"),
    Enderman("ENDERMAN"),
    Endermite("ENDERMITE"),
    FlyingFish("FLYING_FISH"),
    Frog("FROG"),
    FrostWisp("FROST_WISP"),
    Ghoul("GHOUL"),
    Giraffe("GIRAFFE"),
    GlacialWisp("GLACIAL_WISP"),
    GlaciteGolem("GLACITE_GOLEM"),
    Goblin("GOBLIN"),
    GoldenDragon("GOLDEN_DRAGON"),
    Golem("GOLEM"),
    GrandmaWolf("GRANDMA_WOLF"),
    Griffin("GRIFFIN"),
    Guardian("GUARDIAN"),
    Hedgehog("HEDGEHOG"),
    HermitCrab("HERMIT_CRAB"),
    Horse("HORSE"),
    Hound("HOUND"),
    Jellyfish("JELLYFISH"),
    Jerry("JERRY"),
    Kuudra("KUUDRA"),
    Lion("LION"),
    MagmaCube("MAGMA_CUBE"),
    Mammoth("MAMMOTH"),
    Megalodon("MEGALODON"),
    MithrilGolem("MITHRIL_GOLEM"),
    Mole("MOLE"),
    Monkey("MONKEY"),
    Montezuma("FRACTURED_MONTEZUMA_SOUL"),
    MooshroomCow("MOOSHROOM_COW"),
    Ocelot("OCELOT"),
    Owl("OWL"),
    Parrot("PARROT"),
    Penguin("PENGUIN"),
    Phoenix("PHOENIX"),
    Pig("PIG"),
    Pigman("PIGMAN"),
    Rabbit("RABBIT"),
    Rat("RAT"),
    Reindeer("REINDEER"),
    RiftFerret("RIFT_FERRET"),
    Rock("ROCK"),
    Scatha("SCATHA"),
    Sheep("SHEEP"),
    Silverfish("SILVERFISH"),
    Skeleton("SKELETON"),
    SkeletonHorse("SKELETON_HORSE"),
    Slug("SLUG"),
    Snail("SNAIL"),
    Snowman("SNOWMAN"),
    Spider("SPIDER"),
    Spinosaurus("SPINOSAURUS"),
    Spirit("SPIRIT"),
    Squid("SQUID"),
    SubzeroWisp("SUBZERO_WISP"),
    TRex("TYRANNOSAURUS"),
    Tarantula("TARANTULA"),
    Tiger("TIGER"),
    Turtle("TURTLE"),
    WitherSkeleton("WITHER_SKELETON"),
    Wolf("WOLF"),
    Zombie("ZOMBIE");

    class UnknownPetType(override val apiName: String) : PetType

    companion object {
        fun fromApiName(apiName: String): PetType {
            return KnownPetType.entries.firstOrNull { it.apiName == apiName }
                ?: UnknownPetType(apiName)
        }
    }
}