package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.*

enum class AdminItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    AdminLavaRod("ADMIN_ROD"),
    AdminsWarmSweater("ADMINS_WARM_SWEATER", { Armor(it.raw) }),
    AimingBow("AIMING_BOW", { Bow(it.raw) }),
    Anubis("ANUBIS", { Armor(it.raw) }),
    ArenjeyGod("MEGA_LUCK", { Armor(it.raw) }),
    ArgofayTrinket("ARGOFAY_TRINKET", { Accessory(it.raw) }),
    ArtifactOfSpace("ARTIFACT_OF_SPACE", { Accessory(it.raw) }),
    AutowandSleeve("AUTOWAND_SLEEVE"),
    BarnIsland("BARN_ISLAND"),
    BigSpringBoots("BIG_SPRING_BOOTS", { Armor(it.raw) }),
    BiggerSpringBoots("BIGGER_SPRING_BOOTS", { Armor(it.raw) }),
    BlueCandy("BLUE_CANDY"),
    BlueSheepSkin("PET_SKIN_SHEEP_BLUE"),
    Boss("BOSS", { Armor(it.raw) }),
    BottleOfNightmare("BOTTLE_OF_NIGHTMARE"),
    BowOfTheUniverse("UNIVERSE_BOW", { Bow(it.raw) }),
    BoxOfBoosterCookies("BOOSTER_COOKIE_BOX"),
    BrokenHandle("BROKEN_HANDLE"),
    ChewedPieceOfGum("CHEWED_GUM"),
    ClownTheFish("CLOWN_THE_FISH"),
    CompassTalisman("COMPASS_TALISMAN", { Accessory(it.raw) }),
    Copper("COPPER"),
    CottonCandy("COTTON_CANDY"),
    CryptWitherlordSword("CRYPT_WITHERLORD_SWORD", { Weapon(it.raw) }),
    DashingBoots("DASHING_BOOTS", { Armor(it.raw) }),
    DiamondRefinery("DIAMOND_REFINERY"),
    DirtyRug("DIRTY_RUG"),
    DraconicBlade("DRACONIC_BLADE"),
    ElectricWand("ELECTRIC_WAND_ITEM"),
    EmptySodaCan("EMPTY_SODA_CAN"),
    EnchantedBeef("ENCHANTED_COOKED_BEEF"),
    EnchantedClockAdmin("ENCHANTED_CLOCK"),
    EnchantedGriffinFeather("ENCHANTED_GRIFFIN_FEATHER"),
    EndermanHat("ENDERMAN_HAT", { Armor(it.raw) }),
    EpeeDePatrice("PATRICE_SWORD"),
    ExtraLargeGemstoneSack("EXTRA_LARGE_GEMSTONE_SACK"),
    FairyFlute("FAIRY_FLUTE"),
    FairySoulsPamphlet("FAIRY_SOULS_PAMPHLET"),
    FairyWingsCharm("FAIRY_WINGS_CHARM"),
    FakeGoldRing("FAKE_GOLD_RING"),
    FerocitySword150("FEROCITY_SWORD_150", { Weapon(it.raw) }),
    FerocitySword50("FEROCITY_SWORD_50", { Weapon(it.raw) }),
    Fertilizer("FERTILIZER"),
    FestiveFrisbee("FESTIVE_FRISBEE"),
    FireFlowerTool("FIRE_FLOWER_TOOL"),
    FireSoul("FIRE_SOUL"),
    Firestone("FIRE_STONE"),
    FreshSpringWater("FRESH_SPRING_WATER"),
    GatewayWand("GATEWAY_WAND"),
    GhastBoots("GHAST_BOOTS", { Armor(it.raw) }),
    GhastChestplate("GHAST_CHESTPLATE", { Armor(it.raw) }),
    GhastLeggings("GHAST_LEGGINGS", { Armor(it.raw) }),
    GiantFlesh("GIANT_FLESH"),
    GiantPileOfCash("PILE_OF_CASH"),
    GiantTheFish("GIANT_THE_FISH"),
    GraySheepSkin("PET_SKIN_SHEEP_GRAY"),
    GreaterStorageUpgrade("GREATER_ENCHANTED_CHEST_UPGRADE"),
    GreenSheepSkin("PET_SKIN_SHEEP_GREEN"),
    GrizzlyPaw("GRIZZLY_PAW", { Accessory(it.raw) }),
    Hammer("DUNGEON_HAMMER"),
    HarvestingSword("HARVESTING_SWORD"),
    HelmetOfLiveReloading("HELMET_OF_LIVE_RELOADING", { Armor(it.raw) }),
    IncorrectSnubfinDolphinSkin("PET_SKIN_DOLPHIN_SNUBNOSE"),
    IronAlloy("IRON_ALLOY"),
    JarOfPickles("JAR_OF_PICKLES"),
    Kindred("KINDRED", { Armor(it.raw) }),
    LargeRunesSack("LARGE_RUNES_SACK"),
    LightGraySheepSkin("PET_SKIN_SHEEP_LIGHT_GRAY"),
    MagentaSheepSkin("PET_SKIN_SHEEP_MAGENTA"),
    MagicalStaff("MAGICAL_STAFF"),
    MagmaBucketUpgrade("MAGMA_BUCKET_UPGRADE"),
    MasterSkullTierEight("MASTER_SKULL_TIER_8", { Accessory(it.raw) }),
    MasterSkullTierNine("MASTER_SKULL_TIER_9", { Accessory(it.raw) }),
    MasterSkullTierTen("MASTER_SKULL_TIER_10", { Accessory(it.raw) }),
    MediumRunesSack("MEDIUM_RUNES_SACK"),
    MegaJerryLure("MEGA_JERRY_LURE"),
    MiningIsland("MINING_ISLAND"),
    MithrilTech("MITHRIL_TECH"),
    MoldyBread("MOLDY_BREAD"),
    MusicDiscRevenge("REVENGE"),
    NeurotoxinNeedle("NEUROTOXIN_NEEDLE"),
    OldBoot("OLD_BOOT", { Accessory(it.raw) }),
    OrganicBrownMushroom("ORGANIC_BROWN_MUSHROOM"),
    OrganicCactus("ORGANIC_CACTUS"),
    OrganicCarrot("ORGANIC_CARROT_ITEM"),
    OrganicCocoaBeans("ORGANIC_COCOA_BEANS"),
    OrganicEgg("ORGANIC_EGG"),
    OrganicMelon("ORGANIC_MELON"),
    OrganicMilk("ORGANIC_MILK"),
    OrganicMushroom("ORGANIC_MUSHROOM"),
    OrganicNetherWart("ORGANIC_NETHER_STALK"),
    OrganicPotato("ORGANIC_POTATO_ITEM"),
    OrganicPumpkin("ORGANIC_PUMPKIN"),
    OrganicRedMushroom("ORGANIC_RED_MUSHROOM"),
    OrganicSugarCane("ORGANIC_SUGAR_CANE"),
    OrganicWheat("ORGANIC_WHEAT"),
    OrganicWool("ORGANIC_WOOL"),
    OverchewedDetritus("OVERCHEWED_DETRITUS"),
    PerfectHopper("PERFECT_HOPPER"),
    PetSatchel("PET_SATCHEL"),
    PolymorphWand("POLYMORPH_WAND"),
    RandomBook("RANDOM_BOOK"),
    RandomFirework("RANDOM_FIREWORK"),
    Raygun("RAYGUN", { Bow(it.raw) }),
    RedCrossPotion("FAKE_HEALTH_POT"),
    RedSheepSkin("PET_SKIN_SHEEP_RED"),
    RingOfSpace("RING_OF_SPACE", { Accessory(it.raw) }),
    RottenApple("ROTTEN_APPLE"),
    SeismicWaveStick("SEISMIC_WAVE_STICK"),
    SmallRunesSack("SMALL_RUNES_SACK"),
    SpellbookTest("SPELL_BOOK_TEST"),
    StingerBow("STINGER_BOW", { Bow(it.raw) }),
    SwordOfLiveReloading("SWORD_OF_LIVE_RELOADING", { Weapon(it.raw) }),
    SwordOfTheMultiverse("SWORD_OF_THE_MULTIVERSE", { Weapon(it.raw) }),
    SwordOfTheStars("STAR_SWORD", { Weapon(it.raw) }),
    SwordOfTheStars3000("STAR_SWORD_3000", { Weapon(it.raw) }),
    SwordOfTheStars9000("STAR_SWORD_9000", { Weapon(it.raw) }),
    SwordOfTheUniverse("NOVA_SWORD", { Weapon(it.raw) }),
    TNTCharge("TNT_CHARGE"),
    TalismanOfSpace("TALISMAN_OF_SPACE", { Accessory(it.raw) }),
    TestRiftWand("TEST_WAND_WEAPON"),
    TestVampireChestplate("TEST_VAMPIRE_CHESTPLATE"),
    TheFast("SPEED_RACER", { Armor(it.raw) }),
    TitaniumAlloy("TITANIUM_ALLOY"),
    TravelScrollToDragontail("DRAGONTAIL_TRAVEL_SCROLL"),
    TravelScrollToScarleton("SCARLETON_TRAVEL_SCROLL"),
    TravelScrollToTheBlazeFarm("BLAZE_FARM_TRAVEL_SCROLL"),
    TravelScrollToTheKuudraPassage("WASTELAND_TRAVEL_SCROLL"),
    TreeHook("TREE_HOOK"),
    VenomousSword("VENOMOUS_SWORD", { Weapon(it.raw) }),
    Voodoo("VOODOO", { Armor(it.raw) }),
    WandofRecall("WAND_OF_RECALL"),
    YellowSheepSkin("PET_SKIN_SHEEP_YELLOW"),
    Zoom("ZOOM_PICKAXE", { Gear(it.raw) });

    constructor(apiName: String) : this(apiName, { it })
}