package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.*

enum class AdminItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    AdminLavaRod("ADMIN_ROD"),
    AdminsWarmSweater("ADMINS_WARM_SWEATER", { Armor(it.raw) }),
    Anubis("ANUBIS", { Armor(it.raw) }),
    ArenjeyGod("MEGA_LUCK", { Armor(it.raw) }),
    ArtifactOfSpace("ARTIFACT_OF_SPACE", { Accessory(it.raw) }),
    BlueSheepSkin("PET_SKIN_SHEEP_BLUE"),
    Boss("BOSS", { Armor(it.raw) }),
    BowOfTheUniverse("UNIVERSE_BOW", { Bow(it.raw) }),
    BoxOfBoosterCookies("BOOSTER_COOKIE_BOX"),
    CryptWitherlordSword("CRYPT_WITHERLORD_SWORD", { Weapon(it.raw) }),
    DashingBoots("DASHING_BOOTS", { Armor(it.raw) }),
    EmptySodaCan("EMPTY_SODA_CAN"),
    EnchantedClockAdmin("ENCHANTED_CLOCK"),
    ExtraLargeGemstoneSack("EXTRA_LARGE_GEMSTONE_SACK"),
    FairySoulsPamphlet("FAIRY_SOULS_PAMPHLET"),
    FerocitySword150("FEROCITY_SWORD_150", { Weapon(it.raw) }),
    FerocitySword50("FEROCITY_SWORD_50", { Weapon(it.raw) }),
    FestiveFrisbee("FESTIVE_FRISBEE"),
    FireSoul("FIRE_SOUL"),
    GhastBoots("GHAST_BOOTS", { Armor(it.raw) }),
    GhastChestplate("GHAST_CHESTPLATE", { Armor(it.raw) }),
    GhastLeggings("GHAST_LEGGINGS", { Armor(it.raw) }),
    GiantFlesh("GIANT_FLESH"),
    GiantPileOfCash("PILE_OF_CASH"),
    GiantTheFish("GIANT_THE_FISH"),
    GraySheepSkin("PET_SKIN_SHEEP_GRAY"),
    GreenSheepSkin("PET_SKIN_SHEEP_GREEN"),
    HelmetOfLiveReloading("HELMET_OF_LIVE_RELOADING", { Armor(it.raw) }),
    IronAlloy("IRON_ALLOY"),
    Kindred("KINDRED", { Armor(it.raw) }),
    LargeRunesSack("LARGE_RUNES_SACK"),
    LightGraySheepSkin("PET_SKIN_SHEEP_LIGHT_GRAY"),
    MagentaSheepSkin("PET_SKIN_SHEEP_MAGENTA"),
    MasterSkullTierEight("MASTER_SKULL_TIER_8", { Accessory(it.raw) }),
    MasterSkullTierNine("MASTER_SKULL_TIER_9", { Accessory(it.raw) }),
    MasterSkullTierTen("MASTER_SKULL_TIER_10", { Accessory(it.raw) }),
    MediumRunesSack("MEDIUM_RUNES_SACK"),
    MegaJerryLure("MEGA_JERRY_LURE"),
    NeurotoxinNeedle("NEUROTOXIN_NEEDLE"),
    OverchewedDetritus("OVERCHEWED_DETRITUS"),
    PerfectHopper("PERFECT_HOPPER"),
    PetSatchel("PET_SATCHEL"),
    RandomFirework("RANDOM_FIREWORK"),
    Raygun("RAYGUN", { Bow(it.raw) }),
    RedSheepSkin("PET_SKIN_SHEEP_RED"),
    RingOfSpace("RING_OF_SPACE", { Accessory(it.raw) }),
    RottenApple("ROTTEN_APPLE"),
    SmallRunesSack("SMALL_RUNES_SACK"),
    StingerBow("STINGER_BOW", { Bow(it.raw) }),
    SwordOfLiveReloading("SWORD_OF_LIVE_RELOADING", { Weapon(it.raw) }),
    SwordOfTheMultiverse("SWORD_OF_THE_MULTIVERSE", { Weapon(it.raw) }),
    SwordOfTheStars("STAR_SWORD", { Weapon(it.raw) }),
    SwordOfTheStars3000("STAR_SWORD_3000", { Weapon(it.raw) }),
    SwordOfTheStars9000("STAR_SWORD_9000", { Weapon(it.raw) }),
    SwordOfTheUniverse("NOVA_SWORD", { Weapon(it.raw) }),
    TNTCharge("TNT_CHARGE"),
    TalismanOfSpace("TALISMAN_OF_SPACE", { Accessory(it.raw) }),
    TheFast("SPEED_RACER", { Armor(it.raw) }),
    TitaniumAlloy("TITANIUM_ALLOY"),
    TreeHook("TREE_HOOK"),
    Voodoo("VOODOO", { Armor(it.raw) }),
    WandofRecall("WAND_OF_RECALL"),
    YellowSheepSkin("PET_SKIN_SHEEP_YELLOW"),
    Zoom("ZOOM_PICKAXE", { Gear(it.raw) });

    constructor(apiName: String) : this(apiName, { it })
}