package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.SkyblockItem

enum class CosmeticItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    //TODO: Pet Skins, FireSales, Furniture, Helmet Skins, Reward Bundles, Runes, Sprays, https://wiki.hypixel.net/Dyes
    AutumnHutBarnSkin("AUTUMN_HUT_BARN_SKIN"),
    BambooBarnSkin("BAMBOO_BARN_SKIN"),
    BeachBallBarnSkin("BEACH_BALL_BARN_SKIN"),
    BeautifallCabinBarnSkin("BEAUTIFALL_CABIN_BARN_SKIN"),
    BingoDisplay("BINGO_DISPLAY"),
    BonzoStatue("BONZO_STATUE"),
    BookOfStats("BOOK_OF_STATS"),
    CastleBarnSkin("CASTLE_BARN_SKIN"),
    ChocolateFactoryBarnSkin("CHOCOLATE_FACTORY_BARN_SKIN"),
    CollectionDisplay("COLLECTION_DISPLAY"),
    CozyCottageBarnSkin("COZY_COTTAGE_BARN_SKIN"),
    CubeBarnSkin("CUBE_BARN_SKIN"),
    DittoBlob("DITTO_BLOB"),
    DittoSkin("DITTO_SKIN"),
    DittoSkull("DITTO_SKULL"),
    EnchantedNookBarnSkin("ENCHANTED_NOOK_BARN_SKIN"),
    FrogBarnSkin("FROG_BARN_SKIN"),
    GoldenDanteStatue("GOLDEN_DANTE_STATUE"),
    HiveBarnSkin("HIVE_BARN_SKIN"),
    JerryBarnSkin("JERRY_BARN_SKIN"),
    BlackLamp("LAMP_BLACK"),
    GrayLamp("LAMP_GRAY"),
    LightGrayLamp("LAMP_LIGHT_GRAY"),
    WhiteLamp("LAMP_WHITE"),
    BrownLamp("LAMP_BROWN"),
    OrangeLamp("LAMP_ORANGE"),
    RedLamp("LAMP_RED"),
    YellowLamp("LAMP_YELLOW"),
    PurpleLamp("LAMP_PURPLE"),
    MagentaLamp("LAMP_MAGENTA"),
    LilacLamp("LAMP_LILAC"),
    PinkLamp("LAMP_PINK"),
    GreenLamp("LAMP_GREEN"),
    LimeLamp("LAMP_LIME"),
    BlueLamp("LAMP_BLUE"),
    CyanLamp("LAMP_CYAN"),
    LightBlueLamp("LAMP_LIGHT_BLUE"),
    RainbowLamp("LAMP_RAINBOW"),
    LuckyBarnSkin("LUCKY_BARN_SKIN"),
    MainStreetBarnSkin("MAIN_STREET_BARN_SKIN"),
    MushroomBarnSkin("MUSHROOM_BARN_SKIN"),
    PesthuntersLairBarnSkin("PESTHUNTERS_LAIR_BARN_SKIN"),
    PinwheelHouseBarnSkin("PINWHEEL_HOUSE_BARN_SKIN"),
    SandCastleBarnSkin("SAND_CASTLE_BARN_SKIN"),
    TavernBarnSkin("TAVERN_BARN_SKIN"),
    TheEndBarnSkin("END_BARN_SKIN"),
    TownHallBarnSkin("TOWN_HALL_BARN_SKIN"),
    TradingPostBarnSkin("TRADING_POST_BARN_SKIN"),
    WindmillBarnSkin("WINDMILL_BARN_SKIN"),
    WinterBarnSkin("WINTER_BARN_BARN_SKIN"),
    WinterHomesteadBarnSkin("WINTER_HOMESTEAD_BARN_SKIN"),
    GlossyMineralHelmetRoyalSkin("GLOSSY_MINERAL_HELMET_ROYAL"),
    LunarPigmanSkin("PET_SKIN_PIGMAN_LUNAR_PIG"),
    PlushieRabbitSkin("PET_SKIN_RABBIT_PLUSHIE"),
    RoseRabbitSkin("PET_SKIN_RABBIT_ROSE"),
    NeonRedSheepSkin("PET_SKIN_SHEEP_NEON_RED");

    constructor(apiName: String) : this(apiName, { it })
}