package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.Armor
import net.dungeonhub.hypixel.entities.inventory.items.SkyblockItem
import net.dungeonhub.hypixel.entities.inventory.items.Weapon

/**
 * These are item ids for items that are simply used in GUIs to display something.
 * An example for this is the Gemstone Item in the Collection Menu, or the Cancel Parkour Block you get into your Hotbar. They hold no function and are not obtainable, but they still theoretically exist as valid Skyblock Items.
 */
enum class DisplayItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    AmberCrystal("AMBER_CRYSTAL"),
    AmethystCrystal("AMETHYST_CRYSTAL"),
    AquamarineCrystal("AQUAMARINE_CRYSTAL"),
    ArcherDungeonAbility1("ARCHER_DUNGEON_ABILITY_1"),
    ArcherDungeonAbility2("ARCHER_DUNGEON_ABILITY_2"),
    ArcherDungeonAbility3("ARCHER_DUNGEON_ABILITY_3"),
    ArcherUltimateAbility("ARCHER_ULTIMATE_ABILITY"),
    BossSpiritBow("BOSS_SPIRIT_BOW"),
    CancelParkour("CANCEL_PARKOUR_ITEM"),
    CancelRace("CANCEL_RACE_ITEM"),
    CancelWizardmanRace("CANCEL_WIZARDMAN_RACE_ITEM"),
    CastleOfStone("CASTLE_OF_STONE"),
    CatacombsPass0("CATACOMBS_PASS_0"),
    CatacombsPass1("CATACOMBS_PASS_1"),
    CatacombsPass10("CATACOMBS_PASS_10"),
    CatacombsPass2("CATACOMBS_PASS_2"),
    CatacombsPass3("CATACOMBS_PASS_3"),
    CatacombsPass4("CATACOMBS_PASS_4"),
    CatacombsPass5("CATACOMBS_PASS_5"),
    CatacombsPass6("CATACOMBS_PASS_6"),
    CatacombsPass7("CATACOMBS_PASS_7"),
    CatacombsPass8("CATACOMBS_PASS_8"),
    CatacombsPass9("CATACOMBS_PASS_9"),
    CitrineCrystal("CITRINE_CRYSTAL"),
    CryptSkullKey("CRYPT_SKULL_KEY"),
    DeadgehogHelmet("DEADGEHOG_HELMET", { Armor(it.raw) }),
    DungeonBlueSupportOrb("DUNGEON_BLUE_SUPPORT_ORB"),
    DungeonBossKey("DUNGEON_BOSS_KEY"),
    DungeonGreenSupportOrb("DUNGEON_GREEN_SUPPORT_ORB"),
    DungeonNormalKey("DUNGEON_NORMAL_KEY"),
    DungeonRedSupportOrb("DUNGEON_RED_SUPPORT_ORB"),
    ElleFuelCell("ELLE_FUEL_CELL"),
    ElleSupplies("ELLE_SUPPLIES"),
    EmperorHead("EMPEROR_HEAD", { Armor(it.raw) }),
    EmperorLeggings("EMPEROR_LEGGINGS", { Armor(it.raw) }),
    EmperorRobes("EMPEROR_ROBES", { Armor(it.raw) }),
    EmperorShoes("EMPEROR_SHOES", { Armor(it.raw) }),
    ExplosiveShotAbility("EXPLOSIVE_SHOT_ABILITY"),
    FallenStarBoots("FALLEN_STAR_BOOTS"),
    FallenStarChestplate("FALLEN_STAR_CHESTPLATE"),
    FallenStarLeggings("FALLEN_STAR_LEGGINGS"),
    FullFairyControl("FULL_FAIRY_CONTROL"),
    GemstoneCollection("GEMSTONE_COLLECTION"),
    GemstonePowderTier1("GEMSTONE_POWDER_TIER_1"),
    GemstonePowderTier2("GEMSTONE_POWDER_TIER_2"),
    GemstonePowderTier3("GEMSTONE_POWDER_TIER_3"),
    GhostAxeAbility("GHOST_THROWING_AXE"),
    GoldenKey("DUNGEON_GOLDEN_KEY"),
    HarvestingUpgrade("HARVESTING_UPGRADE"),
    HauntAbility("HAUNT_ABILITY"),
    HealerDungeonAbility1("HEALER_DUNGEON_ABILITY_1"),
    HealerDungeonAbility2("HEALER_DUNGEON_ABILITY_2"),
    HealerDungeonAbility3("HEALER_DUNGEON_ABILITY_3"),
    HealingCircle("HEALING_CIRCLE_ITEM"),
    HorsemansScythe("HORSEMAN_SCYTHE"),
    JadeCrystal("JADE_CRYSTAL"),
    JasperCrystal("JASPER_CRYSTAL"),
    KeyA("KEY_A"),
    KeyB("KEY_B"),
    KeyC("KEY_C"),
    KeyD("KEY_D"),
    KeyF("KEY_F"),
    KeyFragment("KEY_FRAGMENT"),
    KeyS("KEY_S"),
    KeyX("KEY_X"),
    LargePotionBag("LARGE_POTION_BAG"),
    LargeTalismanBag("LARGE_TALISMAN_BAG"),
    LeaveChallenge("LEAVE_CHALLENGE_BUTTON"),
    MageDungeonAbility2("MAGE_DUNGEON_ABILITY_2"),
    MageDungeonAbility3("MAGE_DUNGEON_ABILITY_3"),
    MasterCatacombsPass0("MASTER_CATACOMBS_PASS_0"),
    MasterCatacombsPass1("MASTER_CATACOMBS_PASS_1"),
    MasterCatacombsPass10("MASTER_CATACOMBS_PASS_10"),
    MasterCatacombsPass2("MASTER_CATACOMBS_PASS_2"),
    MasterCatacombsPass3("MASTER_CATACOMBS_PASS_3"),
    MasterCatacombsPass4("MASTER_CATACOMBS_PASS_4"),
    MasterCatacombsPass5("MASTER_CATACOMBS_PASS_5"),
    MasterCatacombsPass6("MASTER_CATACOMBS_PASS_6"),
    MasterCatacombsPass7("MASTER_CATACOMBS_PASS_7"),
    MasterCatacombsPass8("MASTER_CATACOMBS_PASS_8"),
    MasterCatacombsPass9("MASTER_CATACOMBS_PASS_9"),
    MaxorEnergyCrystal("MAXOR_ENERGY_CRYSTAL"),
    MediumPotionBag("MEDIUM_POTION_BAG"),
    MediumTalismanBag("MEDIUM_TALISMAN_BAG"),
    MiniatureNuke("MINIATURE_NUKE"),
    MiningCore("MINING_CORE"),
    MinosHunterBoots("MINOS_HUNTER_BOOTS", { Armor(it.raw) }),
    MinosHunterChestplate("MINOS_HUNTER_CHESTPLATE", { Armor(it.raw) }),
    MinosHunterHelmet("MINOS_HUNTER_HELMET", { Armor(it.raw) }),
    MinosHunterLeggings("MINOS_HUNTER_LEGGINGS", { Armor(it.raw) }),
    MithrilPowderTier1("MITHRIL_POWDER_TIER_1"),
    MithrilPowderTier2("MITHRIL_POWDER_TIER_2"),
    MithrilPowderTier3("MITHRIL_POWDER_TIER_3"),
    MushroomCollection("MUSHROOM_COLLECTION"),
    OnyxCrystal("ONYX_CRYSTAL"),
    OpalCrystal("OPAL_CRYSTAL"),
    OpenKuudraShop("KUUDRA_SHOP_ITEM"),
    PeridotCrystal("PERIDOT_CRYSTAL"),
    PopUpWallAbility("MAGE_DUNGEON_ABILITY_1"),
    PurchaseRevivePerk("AUTO_REVIVE_PERK_ITEM"),
    RagnarokAbility("RAGNAROK_ABILITY"),
    ResourceCrystal("RESOURCE_REGENERATOR_CRYSTAL"),
    ReviveDeadPerk("REVIVE_PERK_ITEM"),
    ReviveFinalKillPerk("FINAL_REVIVE_PERK_ITEM"),
    ReviveStoneOrb("REVIVE_STONE_ORB"),
    RubyCrystal("RUBY_CRYSTAL"),
    SapphireCrystal("SAPPHIRE_CRYSTAL"),
    SeaArcherHelmet("SEA_ARCHER_HELMET", { Armor(it.raw) }),
    SeaWalkerBoots("SEA_WALKER_BOOTS", { Armor(it.raw) }),
    SeaWalkerChestplate("SEA_WALKER_CHESTPLATE", { Armor(it.raw) }),
    SeaWalkerHelmet("SEA_WALKER_HELMET", { Armor(it.raw) }),
    SeaWalkerLeggings("SEA_WALKER_LEGGINGS", { Armor(it.raw) }),
    SkeletonLordBow("SKELETON_LORD_BOW", { Weapon(it.raw) }),
    SmallPotionBag("SMALL_POTION_BAG"), //TODO test how this item has been found in testing data???
    SmallTalismanBag("SMALL_TALISMAN_BAG"),
    SwappablePreview("SWAPPABLE_PREVIEW"),
    TankDungeonAbility1("TANK_DUNGEON_ABILITY_1"),
    TankDungeonAbility2("TANK_DUNGEON_ABILITY_2"),
    TheWatchersHead("THE_WATCHERS_HEAD"),
    ThrowingAxeAbility("THROWING_AXE"),
    Thunderstorm("THUNDERSTORM_ABILITY"),
    TopazCrystal("TOPAZ_CRYSTAL"),
    UnknownItem("UNKNOWN_ITEM"),
    VanguardBoots("VANGUARD_BOOTS", { Armor(it.raw) }),
    VanguardChestplate("VANGUARD_CHESTPLATE", { Armor(it.raw) }),
    VanguardHelmet("VANGUARD_HELMET", { Armor(it.raw) }),
    VanguardLeggings("VANGUARD_LEGGINGS", { Armor(it.raw) }),
    WarriorDungeonAbility1("WARRIOR_DUNGEON_ABILITY_1"),
    WatcherBoots("WATCHER_BOOTS", { Armor(it.raw) }),
    WatcherChestplate("WATCHER_CHESTPLATE", { Armor(it.raw) }),
    WatcherEye("WATCHER_EYE", { Armor(it.raw) }),
    WatcherLeggings("WATCHER_LEGS", { Armor(it.raw) }),
    WaterHydraBoots("HYDRA1_BOOTS"),
    WaterHydraChestplate("HYDRA1_CHESTPLATE"),
    WaterHydraLeggings("HYDRA1_LEGGINGS"),
    WishUltimate("WISH_ULTIMATE");

    constructor(apiName: String) : this(apiName, { it })
}