package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.SkyblockItem
import net.dungeonhub.hypixel.entities.inventory.items.special.DefuseKit

enum class DungeonItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    AncientRose("GOLEM_POPPY"),
    ArchitectsFirstDraft("ARCHITECT_FIRST_DRAFT"),
    AspiringLeap("ASPIRING_LEAP"),
    BigfootsLasso("GIANT_FRAGMENT_BIGFOOT"),
    BonzoFragment("BONZO_FRAGMENT"),
    Decoy("DUNGEON_DECOY"),
    DefuseKit("DEFUSE_KIT", { DefuseKit(it.raw) }),
    DiamantesHandle("GIANT_FRAGMENT_DIAMOND"),
    DungeonChestKey("DUNGEON_CHEST_KEY"),
    DungeonOrb("DUNGEON_STONE"),
    FelPearl("FEL_PEARL"),
    FelRose("FEL_ROSE"),
    FelSkull("FEL_SKULL"),
    FumingPotatoBook("FUMING_POTATO_BOOK"),
    GoldorTheFish("GOLDOR_THE_FISH"),
    HealingTissue("HEALING_TISSUE"),
    Infinileap("INFINITE_SPIRIT_LEAP"),
    InflatableJerry("INFLATABLE_JERRY"),
    JollyPinkRock("GIANT_FRAGMENT_BOULDER"),
    JournalEntry("DUNGEON_LORE_PAPER"),
    LASRsEye("GIANT_FRAGMENT_LASER"),
    LesserOrbOfHealing("LESSER_ORB_OF_HEALING"),
    LividFragment("LIVID_FRAGMENT"),
    FirstMasterStar("FIRST_MASTER_STAR"),
    SecondMasterStar("SECOND_MASTER_STAR"),
    ThirdMasterStar("THIRD_MASTER_STAR"),
    FourthMasterStar("FOURTH_MASTER_STAR"),
    FifthMasterStar("FIFTH_MASTER_STAR"),
    MaxorTheFish("MAXOR_THE_FISH"),
    MimicFragment("MIMIC_FRAGMENT"),
    Implosion("IMPLOSION_SCROLL"),
    WitherShield("WITHER_SHIELD_SCROLL"),
    ShadowWarp("SHADOW_WARP_SCROLL"),
    NecronsHandle("NECRON_HANDLE"),
    Recombobulator3000("RECOMBOBULATOR_3000"),
    RedstoneKey("SECRET_DUNGEON_REDSTONE_KEY"),
    ReviveStone("REVIVE_STONE"),
    ScarfFragment("SCARF_FRAGMENT"),
    SecretTracker3000("SECRET_TRACKER"),
    SpiritBone("SPIRIT_BONE"),
    SpiritLeap("SPIRIT_LEAP"),
    SpiritWing("SPIRIT_WING"),
    StormTheFish("STORM_THE_FISH"),
    SummoningRing("SUMMONING_RING"),
    ThornFragment("THORN_FRAGMENT"),
    TrainingWeights("TRAINING_WEIGHTS"),
    Trap("DUNGEON_TRAP"),
    UltimateWitherScroll("ULTIMATE_WITHER_SCROLL"),
    WitherCatalyst("WITHER_CATALYST"),
    WizardsCrystal("DUNGEON_WIZARD_CRYSTAL");

    constructor(apiName: String) : this(apiName, { it })
}