package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.SkyblockItem

enum class GemstoneItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) : KnownSkyblockItemId {
    RoughRubyGemstone("ROUGH_RUBY_GEM"),
    FlawedRubyGemstone("FLAWED_RUBY_GEM"),
    FineRubyGemstone("FINE_RUBY_GEM"),
    FlawlessRubyGemstone("FLAWLESS_RUBY_GEM"),
    PerfectRubyGemstone("PERFECT_RUBY_GEM"),
    RoughAmberGemstone("ROUGH_AMBER_GEM"),
    FlawedAmberGemstone("FLAWED_AMBER_GEM"),
    FineAmberGemstone("FINE_AMBER_GEM"),
    FlawlessAmberGemstone("FLAWLESS_AMBER_GEM"),
    PerfectAmberGemstone("PERFECT_AMBER_GEM"),
    RoughSapphireGemstone("ROUGH_SAPPHIRE_GEM"),
    FlawedSapphireGemstone("FLAWED_SAPPHIRE_GEM"),
    FineSapphireGemstone("FINE_SAPPHIRE_GEM"),
    FlawlessSapphireGemstone("FLAWLESS_SAPPHIRE_GEM"),
    PerfectSapphireGemstone("PERFECT_SAPPHIRE_GEM"),
    RoughJadeGemstone("ROUGH_JADE_GEM"),
    FlawedJadeGemstone("FLAWED_JADE_GEM"),
    FineJadeGemstone("FINE_JADE_GEM"),
    FlawlessJadeGemstone("FLAWLESS_JADE_GEM"),
    PerfectJadeGemstone("PERFECT_JADE_GEM"),
    RoughAmethystGemstone("ROUGH_AMETHYST_GEM"),
    FlawedAmethystGemstone("FLAWED_AMETHYST_GEM"),
    FineAmethystGemstone("FINE_AMETHYST_GEM"),
    FlawlessAmethystGemstone("FLAWLESS_AMETHYST_GEM"),
    PerfectAmethystGemstone("PERFECT_AMETHYST_GEM"),
    RoughTopazGemstone("ROUGH_TOPAZ_GEM"),
    FlawedTopazGemstone("FLAWED_TOPAZ_GEM"),
    FineTopazGemstone("FINE_TOPAZ_GEM"),
    FlawlessTopazGemstone("FLAWLESS_TOPAZ_GEM"),
    PerfectTopazGemstone("PERFECT_TOPAZ_GEM"),
    RoughJasperGemstone("ROUGH_JASPER_GEM"),
    FlawedJasperGemstone("FLAWED_JASPER_GEM"),
    FineJasperGemstone("FINE_JASPER_GEM"),
    FlawlessJasperGemstone("FLAWLESS_JASPER_GEM"),
    PerfectJasperGemstone("PERFECT_JASPER_GEM"),
    RoughOpalGemstone("ROUGH_OPAL_GEM"),
    FlawedOpalGemstone("FLAWED_OPAL_GEM"),
    FineOpalGemstone("FINE_OPAL_GEM"),
    FlawlessOpalGemstone("FLAWLESS_OPAL_GEM"),
    PerfectOpalGemstone("PERFECT_OPAL_GEM"),
    RoughAquamarineGemstone("ROUGH_AQUAMARINE_GEM"),
    FlawedAquamarineGemstone("FLAWED_AQUAMARINE_GEM"),
    FineAquamarineGemstone("FINE_AQUAMARINE_GEM"),
    FlawlessAquamarineGemstone("FLAWLESS_AQUAMARINE_GEM"),
    PerfectAquamarineGemstone("PERFECT_AQUAMARINE_GEM"),
    RoughCitrineGemstone("ROUGH_CITRINE_GEM"),
    FlawedCitrineGemstone("FLAWED_CITRINE_GEM"),
    FineCitrineGemstone("FINE_CITRINE_GEM"),
    FlawlessCitrineGemstone("FLAWLESS_CITRINE_GEM"),
    PerfectCitrineGemstone("PERFECT_CITRINE_GEM"),
    RoughOnyxGemstone("ROUGH_ONYX_GEM"),
    FlawedOnyxGemstone("FLAWED_ONYX_GEM"),
    FineOnyxGemstone("FINE_ONYX_GEM"),
    FlawlessOnyxGemstone("FLAWLESS_ONYX_GEM"),
    PerfectOnyxGemstone("PERFECT_ONYX_GEM"),
    RoughPeridotGemstone("ROUGH_PERIDOT_GEM"),
    FlawedPeridotGemstone("FLAWED_PERIDOT_GEM"),
    FinePeridotGemstone("FINE_PERIDOT_GEM"),
    FlawlessPeridotGemstone("FLAWLESS_PERIDOT_GEM"),
    PerfectPeridotGemstone("PERFECT_PERIDOT_GEM");

    constructor(apiName: String) : this(apiName, { it })
}