package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.SkyblockItem

enum class ItemSackId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    BronzeTrophyFishingSack("BRONZE_TROPHY_FISHING_SACK"),
    CrystalHollowsSack("CRYSTAL_HOLLOWS_SACK"),
    DungeonSack("LARGE_DUNGEON_SACK"),
    DwarvenSack("DWARVEN_MINES_SACK"),
    EventsSack("LARGE_EVENTS_SACK"),
    FlowerSack("FLOWER_SACK"),
    GardenSack("GARDEN_SACK"),
    LargeAgronomySack("LARGE_AGRONOMY_SACK"),
    LargeCombatSack("LARGE_COMBAT_SACK"),
    LargeDragonSack("LARGE_DRAGON_SACK"),
    LargeEnchantedAgronomySack("LARGE_ENCHANTED_AGRONOMY_SACK"),
    LargeEnchantedCombatSack("LARGE_ENCHANTED_COMBAT_SACK"),
    LargeEnchantedFishingSack("LARGE_ENCHANTED_FISHING_SACK"),
    LargeEnchantedForagingSack("LARGE_ENCHANTED_FORAGING_SACK"),
    LargeEnchantedHusbandrySack("LARGE_ENCHANTED_HUSBANDRY_SACK"),
    LargeEnchantedMiningSack("LARGE_ENCHANTED_MINING_SACK"),
    LargeFishingSack("LARGE_FISHING_SACK"),
    LargeForagingSack("LARGE_FORAGING_SACK"),
    LargeGemstoneSack("LARGE_GEMSTONE_SACK"),
    LargeHusbandrySack("LARGE_HUSBANDRY_SACK"),
    LargeLavaFishingSack("LARGE_LAVA_FISHING_SACK"),
    LargeMiningSack("LARGE_MINING_SACK"),
    LargeNetherSack("LARGE_NETHER_SACK"),
    LargeSlayerSack("LARGE_SLAYER_SACK"),
    MediumAgronomySack("MEDIUM_AGRONOMY_SACK"),
    MediumCombatSack("MEDIUM_COMBAT_SACK"),
    MediumDragonSack("MEDIUM_DRAGON_SACK"),
    MediumFishingSack("MEDIUM_FISHING_SACK"),
    MediumForagingSack("MEDIUM_FORAGING_SACK"),
    MediumGemstoneSack("MEDIUM_GEMSTONE_SACK"),
    MediumHusbandrySack("MEDIUM_HUSBANDRY_SACK"),
    MediumLavaFishingSack("MEDIUM_LAVA_FISHING_SACK"),
    MediumMiningSack("MEDIUM_MINING_SACK"),
    MediumNetherSack("MEDIUM_NETHER_SACK"),
    MediumSlayerSack("MEDIUM_SLAYER_SACK"),
    RuneSack("RUNE_SACK"),
    SilverTrophyFishingSack("SILVER_TROPHY_FISHING_SACK"),
    SmallAgronomySack("SMALL_AGRONOMY_SACK"),
    SmallCombatSack("SMALL_COMBAT_SACK"),
    SmallDragonSack("SMALL_DRAGON_SACK"),
    SmallFishingSack("SMALL_FISHING_SACK"),
    SmallForagingSack("SMALL_FORAGING_SACK"),
    SmallGemstoneSack("SMALL_GEMSTONE_SACK"),
    SmallHusbandrySack("SMALL_HUSBANDRY_SACK"),
    SmallLavaFishingSack("SMALL_LAVA_FISHING_SACK"),
    SmallMiningSack("SMALL_MINING_SACK"),
    SmallNetherSack("SMALL_NETHER_SACK"),
    SmallSlayerSack("SMALL_SLAYER_SACK"),
    SpookySack("LARGE_CANDY_SACK"),
    WinterSack("LARGE_WINTER_SACK");

    constructor(apiName: String) : this(apiName, { it })
}