package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.PetAsItem
import net.dungeonhub.hypixel.entities.inventory.items.SkyblockItem
import net.dungeonhub.hypixel.entities.inventory.items.TeleportationSword
import net.dungeonhub.hypixel.entities.inventory.items.Weapon
import net.dungeonhub.hypixel.entities.inventory.items.special.*

enum class MiscItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    ABeginnersGuideToPesthunting("PESTHUNTING_GUIDE"),
    AbiphoneBingo("ABINGOPHONE", { Abiphone(it.raw) }),
    AbiphoneContactsTrio("TRIO_CONTACTS_ADDON"),
    AbiphoneFlipDragon("ABIPHONE_FLIP_DRAGON", { Abiphone(it.raw) }),
    AbiphoneFlipNucleus("ABIPHONE_FLIP_NUCLEUS", { Abiphone(it.raw) }),
    AbiphoneFlipVolcano("ABIPHONE_FLIP_VOLCANO", { Abiphone(it.raw) }),
    AbiphoneXIIIPro("ABIPHONE_XIII_PRO", { Abiphone(it.raw) }),
    AbiphoneXIIIProGiga("ABIPHONE_XIII_PRO_GIGA", { Abiphone(it.raw) }),
    AbiphoneXIIMega("ABIPHONE_XII_MEGA", { Abiphone(it.raw) }),
    AbiphoneXIIMegaColor("ABIPHONE_XII_MEGA_COLOR", { Abiphone(it.raw) }),
    AbiphoneXIUltra("ABIPHONE_XI_ULTRA", { Abiphone(it.raw) }),
    AbiphoneXIUltraStyle("ABIPHONE_XI_ULTRA_STYLE", { Abiphone(it.raw) }),
    AbiphoneXIVEnormous("ABIPHONE_XIV_ENORMOUS", { Abiphone(it.raw) }),
    AbiphoneXIVEnormousBlack("ABIPHONE_XIV_ENORMOUS_BLACK", { Abiphone(it.raw) }),
    AbiphoneXIVEnormousPurple("ABIPHONE_XIV_ENORMOUS_PURPLE", { Abiphone(it.raw) }),
    AbiphoneXPlus("ABIPHONE_X_PLUS", { Abiphone(it.raw) }),
    AbiphoneXPlusSpecialEdition("ABIPHONE_X_PLUS_SPECIAL_EDITION", { Abiphone(it.raw) }),
    AbsoluteEnderPearl("ABSOLUTE_ENDER_PEARL"),
    AccessoryEnrichmentSwapper("TALISMAN_ENRICHMENT_SWAPPER"),
    AlchemistRecipe("ALCHEMIST_RECIPE", { GreatSpookItem(it.raw) }),
    AmalgamatedCrimsonite("AMALGAMATED_CRIMSONITE_NEW"),
    AmberPowerScroll("AMBER_POWER_SCROLL"),
    AmethystPowerScroll("AMETHYST_POWER_SCROLL"),
    AncestralSpade("ANCESTRAL_SPADE", { AncestralSpade(it.raw) }),
    AncientClaw("ANCIENT_CLAW"),
    AncientElevator("ANCIENT_ELEVATOR", { AdminGiftedItem(it.raw) }),
    AncientFruitDecoration("BUILDER_ANCIENT_FRUIT"),
    AnExtremelyDifficultItemForYouToFind("DIFFICULT_ITEM"),
    AppalledPumpkinDecoration("BUILDER_APPALLED_PUMPKIN"),
    AppleDecoration("BUILDER_APPLE"),
    ArachneCrystal("ARACHNE_CRYSTAL"),
    ArachneFragment("ARACHNE_FRAGMENT"),
    ArachnesCalling("ARACHNE_KEEPER_FRAGMENT"),
    ArachnesFang("ARACHNE_FANG"),
    ArcheryCube("ARCHERY_CUBE"),
    ArchfiendDice("ARCHFIEND_DICE"),
    ArrowSwapper("ARROW_SWAPPER"),
    AscensionRope("ASCENSION_ROPE"),
    Atominizer("ATOMINIZER"),
    AttackSpeedEnrichment("TALISMAN_ENRICHMENT_ATTACK_SPEED"),
    AttributeShard("ATTRIBUTE_SHARD", { AttributeShard(it.raw) }),
    AutoSmelter("AUTO_SMELTER"),
    AutopetRules2Pack("AUTOPET_RULES_2"),
    AvariciousChalice("AVARICIOUS_CHALICE"),
    BagOfCash("BAG_OF_CASH"),
    BagOfGold("BAG_OF_GOLD"),
    BananaBunchDecoration("BUILDER_BANANA_BUNCH"),
    BarryCenturyCake("EPOCH_CAKE_AQUA"),
    BaseGriffinUpgradeStone("BASE_GRIFFIN_UPGRADE_STONE"),
    BasketOfSeeds("BASKET_OF_SEEDS", { BasketOfSeeds(it.raw) }),
    BatFirework("BAT_FIREWORK"),
    BatTheFish("BAT_THE_FISH"),
    BattleDisc("BATTLE_DISC"),
    Beacon1("BEACON_1"),
    Beacon2("BEACON_2"),
    Beacon3("BEACON_3"),
    Beacon4("BEACON_4"),
    Beacon5("BEACON_5"),
    Bedrock("BEDROCK"),
    BeetrootDecoration("BUILDER_BEETROOT"),
    BeheadedHorror("BEHEADED_HORROR"),
    BerryBushDecoration("BUILDER_BERRY_BUSH"),
    BerryDecoration("BUILDER_BERRY"),
    Bezos("BEZOS"),
    BingoCard("BINGO_CARD", { BingoCard(it.raw) }),
    Biofuel("BIOFUEL"),
    BirchForestBiomeStick("BIRCH_FOREST_BIOME_STICK", { BiomeStick(it.raw) }),
    BlackGreaterBackpack("BLACK_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    BlackLargeBackpack("BLACK_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    BlackMediumBackpack("BLACK_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    BlackSmallBackpack("BLACK_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    BlastOLantern("PUMPKIN_BOMB"),
    BlazeAshes("BLAZE_ASHES"),
    BlazeRodDistillate("BLAZE_ROD_DISTILLATE"),
    BlazetekkHam("BLAZETEKK_HAM"),
    BlazetekkHamRadio("BLAZETEKK_HAM_RADIO", { BlazetekkHamRadio(it.raw) }),
    BlockOfCoal("COAL_BLOCK"),
    BlockOfDiamond("DIAMOND_BLOCK"),
    BlockOfEmerald("EMERALD_BLOCK"),
    BlockOfGold("GOLD_BLOCK"),
    BlockOfIron("IRON_BLOCK"),
    BlockOfRedstone("REDSTONE_BLOCK"),
    BlockZapper("BLOCK_ZAPPER"),
    BloodSoakedCoins("BLOOD_SOAKED_COINS"),
    BloodStainedCoins("BLOOD_STAINED_COINS"),
    BlueCornDecoration("BUILDER_BLUE_CORN"),
    BlueGoblinEgg("GOBLIN_EGG_BLUE"),
    BlueGreaterBackpack("BLUE_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    BlueJerryBox("JERRY_BOX_BLUE"),
    BlueLargeBackpack("BLUE_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    BlueMediumBackpack("BLUE_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    BlueSharkTooth("BLUE_SHARK_TOOTH"),
    BlueSmallBackpack("BLUE_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    BobOmb("BOB_OMB"),
    BobbinScriptures("BOBBIN_SCRIPTURES"),
    BookwormsFavoriteBook("BOOKWORM_BOOK"),
    BoosterCookie("BOOSTER_COOKIE"),
    BottleOfJyrre("NEW_BOTTLE_OF_JYRRE", { BottleOfJyrre(it.raw) }),
    BouncyBeachBall("BOUNCY_BEACH_BALL"),
    BoxOfSeeds("BOX_OF_SEEDS"),
    BraidedGriffinFeather("BRAIDED_GRIFFIN_FEATHER"),
    BridgeEgg("BRIDGE_EGG"),
    BrimstoneHandle("BRIMSTONE_HANDLE"),
    BrokenRadar("BROKEN_RADAR"),
    BronzeBowl("BRONZE_BOWL"),
    BronzeShipEngine("BRONZE_SHIP_ENGINE"),
    BronzeShipHelm("BRONZE_SHIP_HELM"),
    BronzeShipHull("BRONZE_SHIP_HULL"),
    BrownGreaterBackpack("BROWN_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    BrownLargeBackpack("BROWN_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    BrownMediumBackpack("BROWN_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    BrownMushroomDecoration("BUILDER_BROWN_MUSHROOM"),
    BrownSmallBackpack("BROWN_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    BudgetHopper("BUDGET_HOPPER"),
    BuildersRuler("BUILDERS_RULER", { BuildersRuler(it.raw) }),
    BuildersWand("BUILDERS_WAND", { BuildersWand(it.raw) }),
    BundleOfMagmaArrows("ARROW_BUNDLE_MAGMA"),
    BurningEye("BURNING_EYE"),
    BurningKuudraKey("KUUDRA_BURNING_TIER_KEY"),
    BushDecoration("BUILDER_BUSH"),
    BustedBeltBuckle("BUSTED_BELT_BUCKLE"),
    BuzzinBeatsVinyl("VINYL_BUZZIN_BEATS"),
    CactusDecoration("BUILDER_CACTUS"),
    CakeSoul("CAKE_SOUL", { CakeSoul(it.raw) }),
    CandyTheFish("CANDY_THE_FISH"),
    CapsaicinEyedrops("CAPSAICIN_EYEDROPS_NO_CHARGES"),
    CapsaicinEyedropsOld("CAPSAICIN_EYEDROPS", { CapsaicinEyedropsOld(it.raw) }),
    CarnivalDartTube("CARNIVAL_DART_TUBE"),
    CarnivalTicket("CARNIVAL_TICKET"),
    CarpentryTable("CARPENTRY_BENCH"),
    Catalyst("CATALYST"),
    CenturyCakeOfHype("EPOCH_CAKE_CYAN"),
    CenturyCakeOfTheNextDungeonFloor("EPOCH_CAKE_BLACK"),
    CenturyPartyInvitation("CENTURY_PARTY_INVITATION", { CenturyPartyInvitation(it.raw) }),
    CenturyTheFish("CENTURY_THE_FISH"),
    Charminizer("CHARMINIZER"),
    ChestoBerryDecoration("BUILDER_CHESTO_BERRY"),
    ChillTheFish1("CHILL_THE_FISH"),
    ChillTheFish2("CHILL_THE_FISH_2"),
    ChilledPristinePotato("CHILLED_PRISTINE_POTATO"),
    ChirpingStereo("CHIRPING_STEREO"),
    ChocolateCenturyCake("EPOCH_CAKE_BROWN"),
    ChocolateSyringe("PET_ITEM_CHOCOLATE_SYRINGE"),
    Chum("CHUM"),
    ChunkOfTheMoon("MOON_CHUNK"),
    Chyme("CHYME"),
    CicadaSymphonyVinyl("VINYL_CICADA_SYMPHONY"),
    ClawFossil("CLAW_FOSSIL"),
    ClayMinionXIIUpgradeStone("GENERATOR_UPGRADE_STONE_CLAY_12"),
    CloudyCenturyCake("EPOCH_CAKE_WHITE"),
    ClownDisc("DUNGEON_DISC_2"),
    ClubbedFossil("CLUBBED_FOSSIL"),
    CluckTheFish("CLUCK_THE_FISH"),
    ColossalExperienceBottle("COLOSSAL_EXP_BOTTLE"),
    ColossalExperienceBottleUpgrade("COLOSSAL_EXP_BOTTLE_UPGRADE"),
    CompactOoze("COMPACT_OOZE"),
    Compactor("COMPACTOR"),
    CompleteCenturyCakeBundle("FULL_CENTURY_CAKE_PACK"),
    Compost("COMPOST"),
    CompostBundle("ENCHANTED_COMPOST"),
    ConcentratedStone("CONCENTRATED_STONE"),
    CondensedFermento("CONDENSED_FERMENTO"),
    ControlSwitch("CONTROL_SWITCH"),
    Corleonite("CORLEONITE"),
    CornDecoration("BUILDER_CORN"),
    CorpseFlavoredCenturyCake("EPOCH_CAKE_SILVER"),
    CorruptSoil("CORRUPT_SOIL"),
    CorruptedFragment("CORRUPTED_FRAGMENT"),
    CrabColoredCenturyCake("EPOCH_CAKE_PINK"),
    CreativeMind("CREATIVE_MIND", { CreativeMind(it.raw) }),
    CricketChoirVinyl("VINYL_CRICKET_CHOIR"),
    CriticalChanceEnrichment("TALISMAN_ENRICHMENT_CRITICAL_CHANCE"),
    CriticalDamageEnrichment("TALISMAN_ENRICHMENT_CRITICAL_DAMAGE"),
    Cropie("CROPIE"),
    CrudeGabagool("CRUDE_GABAGOOL"),
    CryopowderShard("CRYOPOWDER_SHARD"),
    CrystalFragment("CRYSTAL_FRAGMENT"),
    CupOfBlood("CUP_OF_BLOOD"),
    CyanGreaterBackpack("CYAN_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    CyanLargeBackpack("CYAN_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    CyanMediumBackpack("CYAN_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    CyanSmallBackpack("CYAN_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    DaedalusStick("DAEDALUS_STICK"),
    DarkCacaoTruffle("DARK_CACAO_TRUFFLE", { TimeBagItem(it.raw) }),
    DarkCandy("DARK_CANDY"),
    DarkQueensSoul("DARK_QUEENS_SOUL_DROP"),
    DaySaver("DAY_SAVER"),
    DeadBushOfLove("DEAD_BUSH_OF_LOVE"),
    DeadSeed("DEAD_SEED"),
    DecayedBat("DECAYED_BAT"),
    DeepOceanBiomeStick("DEEP_OCEAN_BIOME_STICK", { BiomeStick(it.raw) }),
    DefenseEnrichment("TALISMAN_ENRICHMENT_DEFENSE"),
    DerelictAshe("DERELICT_ASHE"),
    DesertBiomeStick("DESERT_BIOME_STICK", { BiomeStick(it.raw) }),
    DesertCrystal("DESERT_ISLAND_CRYSTAL"),
    DesertIsland("DESERT_ISLAND"),
    DiamondMagmafish("MAGMA_FISH_DIAMOND"),
    DiamondSpreading("DIAMOND_SPREADING"),
    DiamondTheFish("DIAMOND_THE_FISH"),
    DianasBookshelf("DIANAS_BOOKSHELF", { DianasBookshelf(it.raw) }),
    DigestedMosquito("DIGESTED_MOSQUITO"),
    DigestedMushrooms("DIGESTED_MUSHROOMS"),
    DivanFragment("DIVAN_FRAGMENT"),
    DivansAlloy("DIVAN_ALLOY"),
    DragonEgg("DRAGON_EGG"),
    Dung("DUNG"),
    DungeonDisc("DUNGEON_DISC_1"),
    DungeonJournal("DUNGEON_LORE_DIARY"),
    DustTheFish("DUST_THE_FISH"),
    DwarvenSuperCompactor("DWARVEN_COMPACTOR"),
    DwarvenTankard("DWARVEN_TANKARD"),
    DynaMITESVinyl("VINYL_DYNAMITES"),
    EarthwormEnsembleVinyl("VINYL_EARTHWORM_ENSEMBLE"),
    EccentricPaintingBundle("ECCENTRIC_PAINTING_BUNDLE"),
    Echolocator("ECHOLOCATOR"),
    Ectoplasm("ECTOPLASM"),
    EditorsPencil("EDITOR_PENCIL", { EditorsPencil(it.raw) }),
    EerieToy("EERIE_TOY", { GreatSpookItem(it.raw) }),
    EerieTreat("EERIE_TREAT", { GreatSpookItem(it.raw) }),
    EggHunt("EGG_HUNT"),
    EggTheFish("EGG_THE_FISH"),
    Egglocator("EGGLOCATOR", { Egglocator(it.raw) }),
    EinarysRedHoodie("EINARY_RED_HOODIE"),
    EkacYrutnecTfir("EPOCH_CAKE_MAGENTA"),
    ElectronTransmitter("ELECTRON_TRANSMITTER"),
    EmberFragment("EMBER_FRAGMENT"),
    EmperorsSkull("DIVER_FRAGMENT"),
    EmptyChumBucket("EMPTY_CHUM_BUCKET"),
    EmptyHurricaneBottle("HURRICANE_IN_A_BOTTLE_EMPTY", { EmptyThunderBottle(it.raw) }),
    EmptyStormBottle("STORM_IN_A_BOTTLE_EMPTY", { EmptyThunderBottle(it.raw) }),
    EmptyThunderBottle("THUNDER_IN_A_BOTTLE_EMPTY", { EmptyThunderBottle(it.raw) }),
    EnchantedAcaciaWood("ENCHANTED_ACACIA_LOG"),
    EnchantedAncientClaw("ENCHANTED_ANCIENT_CLAW"),
    EnchantedBakedPotato("ENCHANTED_BAKED_POTATO"),
    EnchantedBirchWood("ENCHANTED_BIRCH_LOG"),
    EnchantedBlazePowder("ENCHANTED_BLAZE_POWDER"),
    EnchantedBlazeRod("ENCHANTED_BLAZE_ROD"),
    EnchantedBone("ENCHANTED_BONE"),
    EnchantedBoneBlock("ENCHANTED_BONE_BLOCK"),
    EnchantedBoneMeal("ENCHANTED_BONE_MEAL"),
    EnchantedBook("ENCHANTED_BOOK", { EnchantedBook(it.raw) }),
    EnchantedBookBundleBigBrain("ENCHANTED_BOOK_BUNDLE_BIG_BRAIN"),
    EnchantedBookBundleChimera("ENCHANTED_BOOK_BUNDLE_CHIMERA"),
    EnchantedBookBundleCounterStrike("ENCHANTED_BOOK_BUNDLE_COUNTER_STRIKE"),
    EnchantedBookBundlePrismatic("ENCHANTED_BOOK_BUNDLE_PRISMATIC"),
    EnchantedBookBundleQuantum("ENCHANTED_BOOK_BUNDLE_QUANTUM", { EnchantedBookBundle(it.raw) }),
    EnchantedBookBundleRainbow("ENCHANTED_BOOK_BUNDLE_RAINBOW", { EnchantedBookBundle(it.raw) }),
    EnchantedBookBundleReflection("ENCHANTED_BOOK_BUNDLE_REFLECTION"),
    EnchantedBookBundleSmallBrain("ENCHANTED_BOOK_BUNDLE_SMALL_BRAIN", { EnchantedBookBundle(it.raw) }),
    EnchantedBookBundleTheOne("ENCHANTED_BOOK_BUNDLE_THE_ONE", { EnchantedBookBundle(it.raw) }),
    EnchantedBookBundleTransylvanian("ENCHANTED_BOOK_BUNDLE_TRANSYLVANIAN"),
    EnchantedBookBundleVicious("ENCHANTED_BOOK_BUNDLE_VICIOUS"),
    EnchantedBookshelf("ENCHANTED_BOOKSHELF"),
    EnchantedBread("ENCHANTED_BREAD"),
    EnchantedBrownMushroom("ENCHANTED_BROWN_MUSHROOM"),
    EnchantedBrownMushroomBlock("ENCHANTED_HUGE_MUSHROOM_1"),
    EnchantedCactus("ENCHANTED_CACTUS"),
    EnchantedCactusGreen("ENCHANTED_CACTUS_GREEN"),
    EnchantedCarrot("ENCHANTED_CARROT"),
    EnchantedCarrotOnAStick("ENCHANTED_CARROT_STICK"),
    EnchantedCharcoal("ENCHANTED_CHARCOAL"),
    EnchantedClay("ENCHANTED_CLAY_BALL"),
    EnchantedClayBlock("ENCHANTED_CLAY_BLOCK"),
    EnchantedClownfishIncorrect("ENCHANTED_FISH:2"),
    EnchantedCoal("ENCHANTED_COAL"),
    EnchantedCoalBlock("ENCHANTED_COAL_BLOCK"),
    EnchantedCobblestone("ENCHANTED_COBBLESTONE"),
    EnchantedCocoaBeans("ENCHANTED_COCOA"),
    EnchantedCookedFish("ENCHANTED_COOKED_FISH"),
    EnchantedCookedMutton("ENCHANTED_COOKED_MUTTON"),
    EnchantedCookedSalmon("ENCHANTED_COOKED_SALMON"),
    EnchantedCookie("ENCHANTED_COOKIE"),
    EnchantedDandelion("ENCHANTED_DANDELION"),
    EnchantedDarkOakWood("ENCHANTED_DARK_OAK_LOG"),
    EnchantedDiamond("ENCHANTED_DIAMOND"),
    EnchantedDiamondBlock("ENCHANTED_DIAMOND_BLOCK"),
    EnchantedEgg("ENCHANTED_EGG"),
    EnchantedEmerald("ENCHANTED_EMERALD"),
    EnchantedEmeraldBlock("ENCHANTED_EMERALD_BLOCK"),
    EnchantedEndStone("ENCHANTED_ENDSTONE"),
    EnchantedEnderPearl("ENCHANTED_ENDER_PEARL"),
    EnchantedEyeOfEnder("ENCHANTED_EYE_OF_ENDER"),
    EnchantedFeather("ENCHANTED_FEATHER"),
    EnchantedFermentedSpiderEye("ENCHANTED_FERMENTED_SPIDER_EYE"),
    EnchantedFireworkRocket("ENCHANTED_FIREWORK_ROCKET"),
    EnchantedFlint("ENCHANTED_FLINT"),
    EnchantedGhastTear("ENCHANTED_GHAST_TEAR"),
    EnchantedGlacite("ENCHANTED_GLACITE"),
    EnchantedGlisteringMelon("ENCHANTED_GLISTERING_MELON"),
    EnchantedGlowstone("ENCHANTED_GLOWSTONE"),
    EnchantedGlowstoneDust("ENCHANTED_GLOWSTONE_DUST"),
    EnchantedGold("ENCHANTED_GOLD"),
    EnchantedGoldBlock("ENCHANTED_GOLD_BLOCK"),
    EnchantedGoldenCarrot("ENCHANTED_GOLDEN_CARROT"),
    EnchantedGrilledPork("ENCHANTED_GRILLED_PORK"),
    EnchantedGunpowder("ENCHANTED_GUNPOWDER"),
    EnchantedHardStone("ENCHANTED_HARD_STONE"),
    EnchantedHayBale("ENCHANTED_HAY_BALE"),
    EnchantedHayBaleOld("ENCHANTED_HAY_BLOCK"),
    EnchantedHopper("ENCHANTED_HOPPER"),
    EnchantedIce("ENCHANTED_ICE"),
    EnchantedInkSac("ENCHANTED_INK_SACK"),
    EnchantedIron("ENCHANTED_IRON"),
    EnchantedIronBlock("ENCHANTED_IRON_BLOCK"),
    EnchantedJungleWood("ENCHANTED_JUNGLE_LOG"),
    EnchantedLapisBlock("ENCHANTED_LAPIS_LAZULI_BLOCK"),
    EnchantedLapisLazuli("ENCHANTED_LAPIS_LAZULI"),
    EnchantedLavaBucket("ENCHANTED_LAVA_BUCKET"),
    EnchantedLeather("ENCHANTED_LEATHER"),
    EnchantedLilyPad("ENCHANTED_WATER_LILY"),
    EnchantedLushBerberis("ENCHANTED_LUSH_BERBERIS"),
    EnchantedMagmaCream("ENCHANTED_MAGMA_CREAM"),
    EnchantedMelon("ENCHANTED_MELON"),
    EnchantedMelonBlock("ENCHANTED_MELON_BLOCK"),
    EnchantedMithril("ENCHANTED_MITHRIL"),
    EnchantedMushroomSoup("ENCHANTED_MUSHROOM_SOUP"),
    EnchantedMutton("ENCHANTED_MUTTON"),
    EnchantedMycelium("ENCHANTED_MYCELIUM"),
    EnchantedMyceliumCube("ENCHANTED_MYCELIUM_CUBE"),
    EnchantedNetherWart("ENCHANTED_NETHER_STALK"),
    EnchantedNetherrack("ENCHANTED_NETHERRACK"),
    EnchantedOakWood("ENCHANTED_OAK_LOG"),
    EnchantedObsidian("ENCHANTED_OBSIDIAN"),
    EnchantedPackedIce("ENCHANTED_PACKED_ICE"),
    EnchantedPaper("ENCHANTED_PAPER"),
    EnchantedPoisonousPotato("ENCHANTED_POISONOUS_POTATO"),
    EnchantedPoppy("ENCHANTED_POPPY"),
    EnchantedPork("ENCHANTED_PORK"),
    EnchantedPotato("ENCHANTED_POTATO"),
    EnchantedPrismarineCrystals("ENCHANTED_PRISMARINE_CRYSTALS"),
    EnchantedPrismarineShard("ENCHANTED_PRISMARINE_SHARD"),
    EnchantedPufferfish("ENCHANTED_PUFFERFISH"),
    EnchantedPumpkin("ENCHANTED_PUMPKIN"),
    EnchantedQuartz("ENCHANTED_QUARTZ"),
    EnchantedQuartzBlock("ENCHANTED_QUARTZ_BLOCK"),
    EnchantedRabbitFoot("ENCHANTED_RABBIT_FOOT"),
    EnchantedRabbitHide("ENCHANTED_RABBIT_HIDE"),
    EnchantedRawBeef("ENCHANTED_RAW_BEEF"),
    EnchantedRawChicken("ENCHANTED_RAW_CHICKEN"),
    EnchantedRawFish("ENCHANTED_RAW_FISH"),
    EnchantedRawRabbit("ENCHANTED_RABBIT"),
    EnchantedRawSalmon("ENCHANTED_RAW_SALMON"),
    EnchantedRedMushroom("ENCHANTED_RED_MUSHROOM"),
    EnchantedRedMushroomBlock("ENCHANTED_HUGE_MUSHROOM_2"),
    EnchantedRedSand("ENCHANTED_RED_SAND"),
    EnchantedRedSandCube("ENCHANTED_RED_SAND_CUBE"),
    EnchantedRedstone("ENCHANTED_REDSTONE"),
    EnchantedRedstoneBlock("ENCHANTED_REDSTONE_BLOCK"),
    EnchantedRottenFlesh("ENCHANTED_ROTTEN_FLESH"),
    EnchantedSand("ENCHANTED_SAND"),
    EnchantedSeeds("ENCHANTED_SEEDS"),
    EnchantedSharkFin("ENCHANTED_SHARK_FIN"),
    EnchantedSlimeBlock("ENCHANTED_SLIME_BLOCK"),
    EnchantedSlimeball("ENCHANTED_SLIME_BALL"),
    EnchantedSnowBlock("ENCHANTED_SNOW_BLOCK"),
    EnchantedSpiderEye("ENCHANTED_SPIDER_EYE"),
    EnchantedSponge("ENCHANTED_SPONGE"),
    EnchantedSpruceWood("ENCHANTED_SPRUCE_LOG"),
    EnchantedString("ENCHANTED_STRING"),
    EnchantedSugar("ENCHANTED_SUGAR"),
    EnchantedSugarCane("ENCHANTED_SUGAR_CANE"),
    EnchantedSulphur("ENCHANTED_SULPHUR"),
    EnchantedSulphurCube("ENCHANTED_SULPHUR_CUBE"),
    EnchantedTitanium("ENCHANTED_TITANIUM"),
    EnchantedTungsten("ENCHANTED_TUNGSTEN"),
    EnchantedUmber("ENCHANTED_UMBER"),
    EnchantedWetSponge("ENCHANTED_WET_SPONGE"),
    EnchantedWheat("ENCHANTED_WHEAT"),
    EnchantedWool("ENCHANTED_WOOL"),
    EndBiomeStick("END_BIOME_STICK", { BiomeStick(it.raw) }),
    EndstoneRose("ENDSTONE_ROSE"),
    EnrichedKuudraChunk("LEGENDARY_KUUDRA_CHUNK"),
    EonTheFish("EON_THE_FISH"),
    EphemeralGratitude("EPHEMERAL_GRATITUDE"),
    EpicGriffinUpgradeStone("GRIFFIN_UPGRADE_STONE_EPIC"),
    EternalFlameRing("ETERNAL_FLAME_RING"),
    EtherwarpConduit("ETHERWARP_CONDUIT", { TeleportationSword(it.raw) /*isn't a Sword, but honestly, who cares*/ }),
    EtherwarpMerger("ETHERWARP_MERGER"),
    EverburningFlame("EVERBURNING_FLAME"),
    ExceedinglyRareEnderArtifactUpgrade("EXCEEDINGLY_RARE_ENDER_ARTIFACT_UPGRADER"),
    ExpShareCore("PET_ITEM_EXP_SHARE_DROP"),
    ExperimentTheFish("EXPERIMENT_THE_FISH"),
    ExperimentationTable("EXPERIMENTATION_TABLE"),
    ExpiredPumpkin("EXPIRED_PUMPKIN"),
    ExtremeBingoCard("EXTREME_BINGO_CARD", { BingoCard(it.raw) }),
    FTX3070("FTX_3070"),
    FairyWings("FAIRY_WINGS"),
    FakeEmeraldAltar("FAKE_EMERALD_ALTAR"),
    FallenStarLozenge("FALLEN_STAR_TRACKER"),
    FarmCrystal("FARM_CRYSTAL"),
    FarmingForDummies("FARMING_FOR_DUMMIES"),
    FarmingIsland("FARMING_ISLAND"),
    Fermento("FERMENTO"),
    FerocityEnrichment("TALISMAN_ENRICHMENT_FEROCITY"),
    FieryKuudraKey("KUUDRA_FIERY_TIER_KEY"),
    FiletOFortune("FILET_O_FORTUNE"),
    FineFlour("FINE_FLOUR"),
    FireworkIncorrect("FIREWORK"),
    FireworkRocket("FIREWORK_ROCKET"),
    FishChocolatALaVapeur("STEAMED_CHOCOLATE_FISH"),
    FishFood("FISH_FOOD", { FishFood(it.raw) }),
    FishingCrystal("FISHING_CRYSTAL"),
    FishingMinionXIIUpgradeStone("GENERATOR_UPGRADE_STONE_FISHING_12"),
    FishyTreat("FISHY_TREAT"),
    FlakeTheFish("SNOWFLAKE_THE_FISH"),
    Flames("FLAMES"),
    FlamingHeart("FLAMING_HEART"),
    FlowerMaelstrom("FLOWER_MAELSTROM"),
    FlySwatter("FLY_SWATTER"),
    Flycatcher("FLYCATCHER_UPGRADE"),
    FootprintFossil("FOOTPRINT_FOSSIL"),
    ForestBiomeStick("FOREST_BIOME_STICK", { BiomeStick(it.raw) }),
    ForestCrystal("FOREST_ISLAND_CRYSTAL"),
    FossilTheFish("FOSSIL_THE_FISH"),
    FourInARow("CONNECT_FOUR"),
    FramedVolcanicStonefish("FRAMED_VOLCANIC_STONEFISH"),
    FreeBoosterCookie("FREE_COOKIE", { FreeBoosterCookie(it.raw) }),
    FreeSpider("FREE_SPIDER"),
    FrenchFries("FRENCH_FRIES"),
    FreshlyMintedCoins("FRESHLY_MINTED_COINS"),
    FriedFeather("FRIED_FEATHER"),
    FrostySnowball("FROSTY_SNOW_BALL", { SnowShooter(it.raw) }),
    FrostyTheHowitzer("SNOW_HOWITZER", { SnowShooter(it.raw) }),
    FrostyTheSnowBlaster("SNOW_BLASTER", { SnowShooter(it.raw) }),
    FrostyTheSnowCannon("SNOW_CANNON", { SnowShooter(it.raw) }),
    FrozenSpider("FROZEN_SPIDER"),
    FruitBowl("FRUIT_BOWL", { FruitBowl(it.raw) }),
    FruitCenturyCake("EPOCH_CAKE_RED"),
    FudgeMintCore("FUDGE_MINT_CORE"),
    FuelGabagool("FUEL_GABAGOOL"),
    FullChumBucket("FULL_CHUM_BUCKET"),
    GabagoolDistillate("CRUDE_GABAGOOL_DISTILLATE"),
    GabagoolTheFish("GABAGOOL_THE_FISH"),
    GameAnnihilator("GAME_ANNIHILATOR"),
    GameBreaker("GAME_BREAKER"),
    GardenScythe("GARDEN_SCYTHE"),
    GazingPearl("GAZING_PEARL"),
    GiantBouncyBeachBall("GIANT_BOUNCY_BEACH_BALL"),
    GiftBagOfTheCentury("GIFTBAG_OF_THE_CENTURY"),
    GiftCompass("GIFT_COMPASS"),
    GiftOfLearning("GIFT_OF_LEARNING"),
    GiftTheFish("GIFT_THE_FISH"),
    GlacialFragment("GLACIAL_FRAGMENT"),
    GlaciteJewel("GLACITE_JEWEL"),
    GloomlockGrimoire("GLOOMLOCK_GRIMOIRE", { GloomlockGrimoire(it.raw) }),
    GlossyGemstone("GLOSSY_GEMSTONE"),
    GlowingMushroom("GLOWING_MUSHROOM"),
    GlowstoneDistillate("GLOWSTONE_DUST_DISTILLATE"),
    GoblinEgg("GOBLIN_EGG"),
    GodPotion("GOD_POTION_2", { GodPotion(it.raw) }),
    GoldMagmafish("MAGMA_FISH_GOLD"),
    GoldenBounty("GOLDEN_BOUNTY"),
    GoldenFragment("GOLDEN_FRAGMENT"),
    GoldenGift("GOLD_GIFT"),
    GoldenJerryBox("JERRY_BOX_GOLDEN"),
    GoldenPowder("GOLDEN_POWDER"),
    GoldenTooth("GOLDEN_TOOTH"),
    GoldenTreat("GOLD_CANDY"),
    GrandExperienceBottle("GRAND_EXP_BOTTLE"),
    GrapplingHook("GRAPPLING_HOOK"),
    GreatCarrotCandy("GREAT_CARROT_CANDY"),
    GreatSpookPotion("GREAT_SPOOK_POTION"),
    GreatSpookReforgingManual("GREAT_SPOOK_REFORGING_MANUAL", { GreatSpookItem(it.raw) }),
    GreatSpookStaff("GREAT_SPOOK_STAFF", { GreatSpookStaff(it.raw) }),
    GreatWhiteSharkTooth("GREAT_WHITE_SHARK_TOOTH"),
    GreatWhiteToothMeal("GREAT_WHITE_TOOTH_MEAL"),
    GreaterBackpack("GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    GreenCandy("GREEN_CANDY"),
    GreenGift("GREEN_GIFT"),
    GreenGoblinEgg("GOBLIN_EGG_GREEN"),
    GreenGreaterBackpack("GREEN_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    GreenJerryBox("JERRY_BOX_GREEN"),
    GreenLargeBackpack("GREEN_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    GreenMediumBackpack("GREEN_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    GreenSmallBackpack("GREEN_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    GreyGreaterBackpack("GREY_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    GreyLargeBackpack("GREY_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    GreyMediumBackpack("GREY_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    GreySmallBackpack("GREY_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    GriffinFeather("GRIFFIN_FEATHER"),
    GrizzlySalmon("GRIZZLY_BAIT"),
    HalfEatenMushroom("HALF_EATEN_MUSHROOM"),
    HalfEatenProteinBar("PROTEIN_BAR"),
    HallowedSkull("HALLOWED_SKULL"),
    HamsterWheel("HAMSTER_WHEEL"),
    HardGlass("HARD_GLASS"),
    HardenedKuudraChunk("EPIC_KUUDRA_CHUNK"),
    HasteBlock("HASTE_BLOCK"),
    HealthEnrichment("TALISMAN_ENRICHMENT_HEALTH"),
    HeatCore("HEAT_CORE"),
    HeavyGabagool("HEAVY_GABAGOOL"),
    HeavyPearl("HEAVY_PEARL"),
    HelixFossil("HELIX"),
    HerringTheFish("HERRING_THE_FISH", { HerringTheFish(it.raw) }),
    HighClassArchfiendDice("HIGH_CLASS_ARCHFIEND_DICE"),
    HiltOfTrueIce("HILT_OF_TRUE_ICE"),
    HolyDragonFragment("HOLY_FRAGMENT"),
    HoneyJar("HONEY_JAR"),
    HornOfTaurus("HORN_OF_TAURUS"),
    HorsemansCandle("HORSEMAN_CANDLE"),
    HostageCompass("HOSTAGE_COMPASS"),
    HotKuudraKey("KUUDRA_HOT_TIER_KEY"),
    HotPotatoBook("HOT_POTATO_BOOK"),
    HotspotRadar("HOTSPOT_RADAR"),
    HunkOfBlueIce("BLUE_ICE_HUNK"),
    HunkOfIce("ICE_HUNK"),
    HurricaneInABottle("HURRICANE_IN_A_BOTTLE"),
    HyperCatalyst("HYPER_CATALYST"),
    HyperCatalystUpgrade("HYPER_CATALYST_UPGRADE"),
    HyperFurnace("HYPER_FURNACE"),
    HypergolicGabagool("HYPERGOLIC_GABAGOOL"),
    HypergolicIonizedCeramics("HYPERGOLIC_IONIZED_CERAMICS"),
    IceCube("ICE_CUBE"),
    InfernalKuudraKey("KUUDRA_INFERNAL_TIER_KEY"),
    InfernoApex("INFERNO_APEX"),
    InfernoFuelBlock("INFERNO_FUEL_BLOCK"),
    InfernoVertex("INFERNO_VERTEX"),
    InfiniDirtWand("INFINIDIRT_WAND", { InfiniDirtWand(it.raw) }),
    InfiniTorch("INFINI_TORCH"),
    InfinityboomTNT("INFINITE_SUPERBOOM_TNT"),
    IntelligenceEnrichment("TALISMAN_ENRICHMENT_INTELLIGENCE"),
    IslandNPC("ISLAND_NPC"),
    JacobsTicket("JACOBS_TICKET"),
    JadePowerScroll("JADE_POWER_SCROLL"),
    JalapenoBook("JALAPENO_BOOK"),
    JarOfSand("JAR_OF_SAND"),
    JasperPowerScroll("JASPER_POWER_SCROLL"),
    JerryCandy("JERRY_CANDY"),
    JingleBells("JINGLE_BELLS"),
    JudgementCore("JUDGEMENT_CORE"),
    JumboBackpack("JUMBO_BACKPACK", { JumboBackpack(it.raw) }),
    JumboBackpackUpgrade("JUMBO_BACKPACK_UPGRADE"),
    JungleBiomeStick("JUNGLE_BIOME_STICK", { BiomeStick(it.raw) }),
    JungleHeart("JUNGLE_HEART"),
    JungleKey("JUNGLE_KEY"),
    KadaLead("KADA_LEAD"),
    KatBouquet("KAT_BOUQUET"),
    KatFlower("KAT_FLOWER"),
    KelvinInverter("KELVIN_INVERTER"),
    KismetFeather("KISMET_FEATHER"),
    KiwiDecoration("BUILDER_KIWI"),
    Kloonboat("KLOONBOAT"),
    KuudraChunk("UNCOMMON_KUUDRA_CHUNK"),
    KuudraKey("KUUDRA_TIER_KEY"),
    KuudraRelic("KUUDRA_RELIC"),
    KuudraTeeth("KUUDRA_TEETH"),
    KuudraTeethPlaque("KUUDRA_CAVITY", { KuudraTeethPlaque(it.raw) }),
    KuudraWashingMachine("KUUDRA_WASHING_MACHINE"),
    Lantern("LANTERN"),
    LanternOfTheDead("LANTERN_OF_THE_DEAD", { LeaderboardItem(it.raw) }),
    LapisLazuliBlock("LAPIS_BLOCK"),
    LargeBackpack("LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    LargeStorage("LARGE_ENCHANTED_CHEST"),
    LatestUpdateCenturyCake("EPOCH_CAKE_ORANGE"),
    LaunchPad("LAUNCH_PAD"),
    LavaShell("LAVA_SHELL"),
    LavaWaterOrb("LAVA_WATER_ORB"),
    LeatherCloth("LEATHER_CLOTH"),
    LegacyGotPotion("GOD_POTION"),
    LegendaryGriffinUpgradeStone("GRIFFIN_UPGRADE_STONE_LEGENDARY"),
    LemonDecoration("BUILDER_LEMON"),
    LesserSoulflowEngine("LESSER_SOULFLOW_ENGINE"),
    LetterOfRecommendation("DEAN_LETTER_OF_RECOMMENDATION"),
    LettuceDecoration("BUILDER_LETTUCE"),
    LightBlueGreaterBackpack("LIGHT_BLUE_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    LightBlueLargeBackpack("LIGHT_BLUE_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    LightBlueMediumBackpack("LIGHT_BLUE_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    LightBlueSmallBackpack("LIGHT_BLUE_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    LightGreyGreaterBackpack("LIGHT_GREY_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    LightGreyLargeBackpack("LIGHT_GREY_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    LightGreyMediumBackpack("LIGHT_GREY_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    LightGreySmallBackpack("LIGHT_GREY_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    LilacFruitDecoration("BUILDER_LILAC_FRUIT"),
    LimeGreaterBackpack("LIME_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    LimeLargeBackpack("LIME_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    LimeMediumBackpack("LIME_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    LimeSmallBackpack("LIME_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    LostBottleOfJyrre("BOTTLE_OF_JYRRE", { BottleOfJyrre(it.raw) }),
    LoudmouthBass("LOUDMOUTH_BASS", { LoudmouthBass(it.raw) }),
    LuckyCloverCore("PET_ITEM_LUCKY_CLOVER_DROP"),
    LuminoFiber("LUMINO_FIBER"),
    LumpOfMagma("LUMP_OF_MAGMA"),
    LushBerberis("LUSH_BERBERIS"),
    MaddoxBadphone("AATROX_BADPHONE"),
    MaddoxBatphone("AATROX_BATPHONE", { MaddoxBatphone(it.raw) }),
    MaddoxsPhoneNumber("AATROX_PHONE_NUMBER"),
    MagentaGreaterBackpack("MAGENTA_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    MagentaLargeBackpack("MAGENTA_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    MagentaMediumBackpack("MAGENTA_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    MagentaSmallBackpack("MAGENTA_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    MagicFindEnrichment("TALISMAN_ENRICHMENT_MAGIC_FIND"),
    MagicalLavaBucket("MAGICAL_LAVA_BUCKET"),
    MagicalMap("MAP:2", { MagicalMap(it.raw) }),
    MagicalMilkBucket("MAGICAL_MILK_BUCKET"),
    MagicalMushroomSoup("MAGIC_MUSHROOM_SOUP"),
    MagicalWaterBucket("MAGICAL_WATER_BUCKET"),
    MagmaBucket("MAGMA_BUCKET"),
    MagmaChunk("MAGMA_CHUNK"),
    MagmaCore("MAGMA_CORE"),
    MagmaCreamDistillate("MAGMA_CREAM_DISTILLATE"),
    MagmaLordFragment("MAGMA_LORD_FRAGMENT"),
    Magmag("MAGMAG"),
    ManaDisintegrator("MANA_DISINTEGRATOR"),
    MatchSticks("MATCH_STICKS"),
    MatriarchsPerfume("MATRIARCH_PARFUM"),
    MeatyKuudraChunk("RARE_KUUDRA_CHUNK"),
    MediumBackpack("MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    MediumStorage("MEDIUM_ENCHANTED_CHEST"),
    MegaJerryBox("JERRY_BOX_MEGA"),
    MelonDecoration("BUILDER_MELON"),
    MesaBiomeStick("MESA_BIOME_STICK", { BiomeStick(it.raw) }),
    MetalDetector("DWARVEN_METAL_DETECTOR"),
    MetaphysicalSerum("METAPHYSICAL_SERUM"),
    MillenniaOldBlazeAshes("MILLENIA_OLD_BLAZE_ASHES"),
    MiniFishBowl("MINI_FISH_BOWL"),
    MinionExpander("MINION_EXPANDER"),
    MinionStorageXpender("MINION_STORAGE_EXPANDER"),
    MiteGel("MITE_GEL"),
    MithrilCrystal("MITHRIL_CRYSTAL"),
    MithrilInfusion("MITHRIL_INFUSION"),
    MobyDuck("MOBY_DUCK", { TimeBagItem(it.raw) }),
    MobyDuckCollectorsEdition("MOBY_DUCK_COLLECTOR_EDITION"),
    MoltenPowder("MOLTEN_POWDER"),
    MoodyGrappleshot("MOODY_GRAPPLESHOT", { MoodyGrappleshot(it.raw) }),
    MoogmaPelt("MOOGMA_PELT"),
    MouseTrap("MOUSE_PEST_TRAP"),
    MoveJerry("ASSISTANT"),
    MoveSam("SAM_ASSISTANT"),
    MushroomBiomeStick("MUSHROOM_BIOME_STICK", { BiomeStick(it.raw) }),
    MushroomSpore("MUSHROOM_SPORE"),
    MushroomWartsStew("WARTS_STEW"),
    MusicDisc11("RECORD_11"),
    MusicDisc13("GOLD_RECORD"),
    MusicDiscBlocks("RECORD_3"),
    MusicDiscCat("GREEN_RECORD"),
    MusicDiscChirp("RECORD_4"),
    MusicDiscFar("RECORD_5"),
    MusicDiscMall("RECORD_6"),
    MusicDiscMellohi("RECORD_7"),
    MusicDiscStal("RECORD_8"),
    MusicDiscStrad("RECORD_9"),
    MusicDiscWait("RECORD_12"),
    MusicDiscWard("RECORD_10"),
    MutantNetherWart("MUTANT_NETHER_STALK"),
    MutatedBlazeAshes("MUTATED_BLAZE_ASHES"),
    MyceliumDust("MYCELIUM_DUST"),
    MysteriousCrop("MYSTERIOUS_CROP"),
    MysteriousMeat("MYSTERIOUS_MEAT"),
    MysteriousPackage("MYSTERIOUS_PACKAGE"),
    MysticalMushroomSoup("SUPER_MAGIC_MUSHROOM_SOUP"),
    NameTag("NAME_TAG", { NameTag(it.raw) }),
    NecronDisc("DUNGEON_DISC_5"),
    NecronsLadder("NECRONS_LADDER", { NecronsLadder(it.raw) }),
    NetherBiomeStick("NETHER_BIOME_STICK", { BiomeStick(it.raw) }),
    NetherIsland("NETHER_ISLAND"),
    NetherStar("CORRUPTED_NETHER_STAR"),
    NetherWartCrystal("NETHER_WART_ISLAND_CRYSTAL"),
    NetherWartDistillate("NETHER_STALK_DISTILLATE"),
    NetherWartIsland("NETHER_WART_ISLAND"),
    NetherWartPouch("NETHER_WART_POUCH", { NetherWartPouch(it.raw) }),
    NewYearCake("NEW_YEAR_CAKE", { NewYearCake(it.raw) }),
    NightSaver("NIGHT_SAVER"),
    NightmareNullifier("NIGHTMARE_NULLIFIER"),
    NoisyPearl("NOISY_PEARL"),
    NopeTheFish("NOPE_THE_FISH"),
    NotALieCenturyCake("EPOCH_CAKE_GRAY"),
    NotJustAPestVinyl("VINYL_BEETLE"),
    NullAtom("NULL_ATOM"),
    NullBlade("NULL_BLADE"),
    NullEdge("NULL_EDGE"),
    NullOvoid("NULL_OVOID"),
    NullSphere("NULL_SPHERE"),
    NurseSharkTooth("NURSE_SHARK_TOOTH"),
    ObscureEnding("OBSCURE_ENDING"),
    OctopusTendril("OCTOPUS_TENDRIL"),
    OilBarrel("OIL_BARREL"),
    OldAmalgamatedCrimsonite("AMALGAMATED_CRIMSONITE"),
    OldLeatherBoot("OLD_LEATHER_BOOT"),
    OldDisc("DUNGEON_DISC_4"),
    OldDragonFragment("OLD_FRAGMENT"),
    OmegaEnchantedEgg("OMEGA_EGG"),
    OnionDecoration("BUILDER_ONION"),
    OopsTheFish("OOPS_THE_FISH"),
    OpalPowerScroll("OPAL_POWER_SCROLL"),
    OrangeDecoration("BUILDER_ORANGE"),
    OrangeGreaterBackpack("ORANGE_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    OrangeLargeBackpack("ORANGE_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    OrangeMediumBackpack("ORANGE_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    OrangeSmallBackpack("ORANGE_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    OrbOfEnergy("ORB_OF_ENERGY"),
    OverfluxCapacitor("OVERFLUX_CAPACITOR"),
    PaintDryingSimulator("PAINT_CARTRIDGE"),
    ParkourCheckpoint("PARKOUR_POINT"),
    ParkourStartEnd("PARKOUR_CONTROLLER"),
    ParkourTimes("PARKOUR_TIMES"),
    PartyGift("PARTY_GIFT"),
    PartyTheFish("PARTY_THE_FISH"),
    PerfectlyCutDiamond("PERFECTLY_CUT_DIAMOND"),
    PersonalBankItem("PERSONAL_BANK_ITEM"),
    PestRepellent("PEST_REPELLENT"),
    PestRepellentMax("PEST_REPELLENT_MAX"),
    PestTrap("PEST_TRAP"),
    Pet("PET", { PetAsItem(it.raw) }),
    PetCake("PET_CAKE"),
    PetRockCenturyCake("EPOCH_CAKE_GREEN"),
    PinkBerryDecoration("BUILDER_PINK_BERRY"),
    PinkGreaterBackpack("PINK_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    PinkLargeBackpack("PINK_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    PinkMediumBackpack("PINK_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    PinkSmallBackpack("PINK_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    PlantMatter("PLANT_MATTER"),
    Plasma("PLASMA"),
    PlasmaBucket("PLASMA_BUCKET"),
    PlasmaNucleus("PLASMA_NUCLEUS", { PlasmaNucleus(it.raw) }),
    PlasticShovel("PLASTIC_SHOVEL", { LeaderboardItem(it.raw) }),
    PlumbersSponge("PLUMBER_SPONGE"),
    PocketSackInASack("POCKET_SACK_IN_A_SACK"),
    PoemOfTrueLove("POEM_OF_INFINITE_LOVE"),
    PoisonSample("POISON_SAMPLE"),
    PoisonedCandy("POISONED_CANDY"),
    PolishedPebble("POLISHED_PEBBLE"),
    PolishedPumpkin("POLISHED_PUMPKIN"),
    PondIsland("POND_ISLAND"),
    PoorlyWrappedRock("POORLY_WRAPPED_ROCK"),
    PortableBuilder("PORTABLE_BUILDER"),
    PortableWasher("PORTABLE_WASHER"),
    PortableWoolWeaver("PORTABLE_WOOL_WEAVER"),
    PortalToArachnesSanctuary("ARACHNE_SANCTUARY_PORTAL"),
    PortalToBirchPark("FORAGING_1_PORTAL"),
    PortalToDarkThicket("FORAGING_5_PORTAL"),
    PortalToDragontail("DRAGONTAIL_PORTAL"),
    PortalToJungleIsland("FORAGING_3_PORTAL"),
    PortalToMushroomIsland("FARMING_2_PORTAL"),
    PortalToSavannaWoodland("FORAGING_4_PORTAL"),
    PortalToScarleton("SCARLETON_PORTAL"),
    PortalToSpruceWoods("FORAGING_2_PORTAL"),
    PortalToTheBarn("FARMING_1_PORTAL"),
    PortalToTheCastle("HUB_CASTLE_PORTAL"),
    PortalToTheCrimsonIsle("DANGER_2_PORTAL"),
    PortalToTheCrypts("HUB_CRYPTS_PORTAL"),
    PortalToTheCrystalHollows("CRYSTAL_HOLLOWS_PORTAL"),
    PortalToTheCrystalNucleus("CRYSTAL_NUCLEUS_PORTAL"),
    PortalToTheDarkAuction("DARK_AUCTION_PORTAL"),
    PortalToTheDeepCaverns("MINING_2_PORTAL"),
    PortalToTheDragonsNest("DRAGON_NEST_PORTAL"),
    PortalToTheDwarvenBaseCamp("BASE_CAMP_PORTAL"),
    PortalToTheDwarvenMines("DWARVEN_MINES_PORTAL"),
    PortalToTheEnd("DANGER_3_PORTAL"),
    PortalToTheForge("FORGE_PORTAL"),
    PortalToTheForgottenSkull("KUUDRA_SKULL_PORTAL"),
    PortalToTheGoldMine("MINING_1_PORTAL"),
    PortalToTheHowlingCaves("HOWLING_CAVE_PORTAL"),
    PortalToTheHub("HUB_PORTAL"),
    PortalToTheMuseum("MUSEUM_PORTAL"),
    PortalToTheRift("RIFT_WIZARD_TOWER_PORTAL"),
    PortalToTheSmolderingTomb("SMOLDERING_TOMB_PORTAL"),
    PortalToTheSpidersDen("DANGER_1_PORTAL"),
    PortalToTheTopOfTheNest("TOP_OF_SPIDERS_DEN_PORTAL"),
    PortalToTheTrappersDen("TRAPPER_DEN_PORTAL"),
    PortalToTheVoidSepulture("VOID_SEPULTURE_PORTAL"),
    PortalToTheWasteland("WASTELAND_PORTAL"),
    PortalToTheWizardTower("WIZARD_TOWER_PORTAL"),
    Portalizer("PORTALIZER"),
    PotatoSpreading("POTATO_SPREADING"),
    PotatoStyleCenturyCake("EPOCH_CAKE_YELLOW"),
    PotatoWarSilverMedal("POTATO_SILVER_MEDAL"),
    PowderPumpkin("MINING_PUMPKIN"),
    Precious("PRECIOUS"),
    PrecursorApparatus("PRECURSOR_APPARATUS"),
    PrehistoricEgg("PREHISTORIC_EGG", { PrehistoricEgg(it.raw) }),
    PrettyFlyVinyl("VINYL_PRETTY_FLY"),
    PricelessTheFish("PRICELESS_THE_FISH", { PricelessTheFish(it.raw) }),
    Prismapump("PRISMAPUMP"),
    ProtectorDragonFragment("PROTECTOR_FRAGMENT"),
    PumpkinGuts("PUMPKIN_GUTS"),
    PumpkinLauncher("PUMPKIN_LAUNCHER", { Weapon(it.raw) }),
    PurpleCandy("PURPLE_CANDY"),
    PurpleGreaterBackpack("PURPLE_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    PurpleJerryBox("JERRY_BOX_PURPLE"),
    PurpleLargeBackpack("PURPLE_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    PurpleMediumBackpack("PURPLE_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    PurpleSmallBackpack("PURPLE_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    PuzzleCube("PUZZLE_CUBE", { PuzzleCube(it.raw) }),
    PyroclasticScale("PYROCLASTIC_SCALE"),
    QualityMap("QUALITY_MAP"),
    RabbitTheFish("RABBIT_THE_FISH"),
    RaffleTicket("MINING_RAFFLE_TICKET", { RaffleTicket(it.raw) }),
    RagnaRock("RAGNA_ROCK"),
    RandomCenturyCakeBundle("RANDOM_CENTURY_CAKE_PACK"),
    RareGriffinUpgradeStone("GRIFFIN_UPGRADE_STONE_RARE"),
    RawSoulflow("RAW_SOULFLOW"),
    ReaperPepper("REAPER_PEPPER"),
    RecallPotion("RECALL_POTION", { RecallPotion(it.raw) }),
    RedClawEgg("RED_CLAW_EGG"),
    RedGift("RED_GIFT"),
    RedGoblinEgg("GOBLIN_EGG_RED"),
    RedGreaterBackpack("RED_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    RedLargeBackpack("RED_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    RedMediumBackpack("RED_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    RedSmallBackpack("RED_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    RedThornleaf("RED_THORNLEAF"),
    RefinedBottleOfJyrre("REFINED_BOTTLE_OF_JYRRE"),
    RefinedDarkCacaoTruffle("REFINED_DARK_CACAO_TRUFFLE"),
    RefinedMineral("REFINED_MINERAL"),
    ReforgeAnvil("REFORGE_ANVIL"),
    RefundBoosterCookie("REFUND_COOKIE", { FreeBoosterCookie(it.raw) }),
    ReheatedGummyPolarBear("REHEATED_GUMMY_POLAR_BEAR"),
    RekindledEmberFragment("REKINDLED_EMBER_FRAGMENT"),
    RemnantOfTheEye("REMNANT_OF_THE_EYE"),
    RepellingCandle("REPELLING_CANDLE", { RepellingCandle(it.raw) }),
    RevenantCatalyst("REVENANT_CATALYST"),
    RevenantFlesh("REVENANT_FLESH"),
    RevenantViscera("REVENANT_VISCERA"),
    RitualResidue("RITUAL_RESIDUE"),
    RobotronReflector("ROBOTRON_REFLECTOR"),
    RockPaperShears("ROCK_PAPER_SHEARS"),
    RockTheFish("ROCK_THE_FISH"),
    RodentRevolutionVinyl("VINYL_RODENT_REVOLUTION"),
    RogueFlesh("ROGUE_FLESH"),
    RoofedForestBiomeStick("ROOFED_FOREST_BIOME_STICK", { BiomeStick(it.raw) }),
    RoofedForestIsland("ROOFED_FOREST_ISLAND"),
    RoseBouquet("ROSE_BOUQUET"),
    RoyalCompass("ROYAL_COMPASS"),
    RoyalPigeon("ROYAL_PIGEON", { RoyalPigeon(it.raw) }),
    RubyPowerScroll("RUBY_POWER_SCROLL"),
    RustyCoin("RUSTY_COIN"),
    RustyShipEngine("RUSTY_SHIP_ENGINE"),
    SamsScythe("SAM_SCYTHE"),
    SapphirePowerScroll("SAPPHIRE_POWER_SCROLL"),
    SaulsRecommendation("SAULS_RECOMMENDATION", { SaulsRecommendation(it.raw) }),
    SavannaBiomeStick("SAVANA_BIOME_STICK", { BiomeStick(it.raw) }),
    SavingGrace("SAVING_GRACE"),
    ScareFragment("SCARE_FRAGMENT"),
    ScaryGrimoire("SCARY_GRIMOIRE", { ScaryGrimoire(it.raw) }),
    ScavengedDiamondAxe("DWARVEN_DIAMOND_AXE"),
    ScavengedEmeraldHammer("DWARVEN_EMERALD_HAMMER"),
    ScavengedGoldenHammer("DWARVEN_GOLD_HAMMER"),
    ScavengedIronHammer("DWARVEN_IRON_HAMMER"),
    ScavengedLapisSword("DWARVEN_LAPIS_SWORD"),
    ScorchedCrabStick("SCORCHED_CRAB_STICK"),
    ScorchedPowerCrystal("SCORCHED_POWER_CRYSTAL"),
    ScornclawBrew("SCORNCLAW_BREW"),
    ScytheBlade("SCYTHE_BLADE"),
    SeaCreatureChanceEnrichment("TALISMAN_ENRICHMENT_SEA_CREATURE_CHANCE"),
    SeaEmperorCenturyCake("EPOCH_CAKE_BLUE"),
    SealsTreatBag("SEAL_TREAT_BAG"),
    SecretBingoCard("SECRET_BINGO_CARD", { BingoCard(it.raw) }),
    SecretGiftForJuliette("WRAPPED_GIFT_FOR_JULIETTE"),
    SeveredPincer("SEVERED_PINCER"),
    SewerFish("SEWER_FISH"),
    ShadowsIndicateRiddlesIlluminatingUnseenStars("SIRIUS_BOOK"),
    ShardOfTheShredded("SHARD_OF_THE_SHREDDED"),
    SharkFin("SHARK_FIN"),
    SharkWaterOrb("SHARK_WATER_ORB"),
    SharpRock("SILEX"),
    ShatteredLocket("SHATTERED_PENDANT"),
    ShinyOrb("SHINY_ORB"),
    ShinyRod("SHINY_ROD"),
    ShinyShard("SHINY_SHARD"),
    ShowcaseBlock("SHOWCASE_BLOCK"),
    ShrimpTheFish("SHRIMP_THE_FISH"),
    SilenceBlock("SILENCE_BLOCK"),
    SilentPearl("SILENT_PEARL"),
    Silex("SIL_EX"),
    SilkyLichen("SILKY_LICHEN"),
    SilverMagmafish("MAGMA_FISH_SILVER"),
    SimpleCarrotCandy("SIMPLE_CARROT_CANDY"),
    SinfulDice("SINFUL_DICE"),
    SingedPowder("SINGED_POWDER"),
    SingingFish("SINGING_FISH", { LeaderboardItem(it.raw) }),
    SiriusPersonalPhoneNumber("SIRIUS_PERSONAL_PHONE_NUMBER"),
    SkeletonTheFish("SKELETON_THE_FISH"),
    SkyblockMenu("SKYBLOCK_MENU"),
    SleepingEye("SLEEPING_EYE"),
    SleepyHollow("SLEEPY_HOLLOW"),
    SliceOfBlueberryCake("SLICE_OF_BLUEBERRY_CAKE", { CakeSlice(it.raw) }),
    SliceOfLemonCheesecake("SLICE_OF_CHEESECAKE", { CakeSlice(it.raw) }),
    SliceOfMatchaCake("SLICE_OF_GREEN_VELVET_CAKE", { CakeSlice(it.raw) }),
    SliceOfRedVelvetCake("SLICE_OF_RED_VELVET_CAKE", { CakeSlice(it.raw) }),
    SliceOfStrawberryShortcake("SLICE_OF_STRAWBERRY_SHORTCAKE", { CakeSlice(it.raw) }),
    SlowAndGroovyVinyl("VINYL_SLOW_AND_GROOVY"),
    SludgeJuice("SLUDGE_JUICE"),
    SmallBackpack("SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    SmallStorage("SMALL_ENCHANTED_CHEST"),
    SnowBlock("SNOW_BLOCK"),
    SnowShovel("SNOW_SHOVEL"),
    SnowUnionI("SNOW_UNION"),
    SocialDisplay("SOCIAL_DISPLAY"),
    SolarPanel("SOLAR_PANEL"),
    SolvedRubixPrism("SOLVED_PRISM"),
    Sorrow("SORROW"),
    SoulEsoward("SOUL_ESOWARD"),
    SoulFragment("SOUL_FRAGMENT"),
    SoulString("SOUL_STRING"),
    Soulflow("SOULFLOW"),
    SoulflowEngine("SOULFLOW_ENGINE"),
    SpeckledTeacup("SPECKLED_TEACUP"),
    SpectreDust("SPECTRE_DUST"),
    SpeedEnrichment("TALISMAN_ENRICHMENT_WALK_SPEED"),
    SpellPowder("SPELL_POWDER"),
    SpiderCatalyst("SPIDER_CATALYST"),
    SpineFossil("SPINE_FOSSIL"),
    SpookTheFish("SPOOK_THE_FISH"),
    SpookyDisc("SPOOKY_DISC"),
    SpookyPie("SPOOKY_PIE", { LeaderboardItem(it.raw) }),
    SpookyShard("SPOOKY_SHARD"),
    SpookyWaterOrb("SPOOKY_WATER_ORB"),
    Sprayonator("SPRAYONATOR", { Sprayonator(it.raw) }),
    Squash("SQUASH"),
    SqueakyMousemat("SQUEAKY_MOUSEMAT", { SqueakyMousemat(it.raw) }),
    Starfall("STARFALL"),
    StewTheFish("STEW_THE_FISH"),
    StockOfStonks("STOCK_OF_STONKS"),
    StonePlatform("STONE_BRIDGE"),
    StormInABottle("STORM_IN_A_BOTTLE"),
    StreamersCenturyCake("EPOCH_CAKE_PURPLE"),
    StrengthEnrichment("TALISMAN_ENRICHMENT_STRENGTH"),
    StrongDragonFragment("STRONG_FRAGMENT"),
    StuffedChiliPepper("STUFFED_CHILI_PEPPER"),
    SubzeroInverter("SUBZERO_INVERTER"),
    SulphuricCoal("SULPHURIC_COAL"),
    SummoningEye("SUMMONING_EYE"),
    SuperCompactor3000("SUPER_COMPACTOR_3000"),
    SuperEnchantedEgg("SUPER_EGG"),
    SuperFurnace("SUPER_FURNACE"),
    SuperbCarrotCandy("SUPERB_CARROT_CANDY"),
    SuperboomTNT("SUPERBOOM_TNT"),
    SuperiorDragonFragment("SUPERIOR_FRAGMENT"),
    SuperliteMotor("SUPERLITE_MOTOR"),
    SupremeChocolateBar("SUPREME_CHOCOLATE_BAR"),
    SuspiciousRedGift("SUSPICIOUS_RED_GIFT"),
    SuspiciousScrap("SUSPICIOUS_SCRAP"),
    SuspiciousStew("SUSPICIOUS_STEW"),
    SweetFlesh("SWEET_FLESH"),
    SyntheticHeart("SYNTHETIC_HEART"),
    TacticalInsertion("TACTICAL_INSERTION", { TacticalInsertion(it.raw) }),
    TaigaBiomeStick("TAIGA_BIOME_STICK", { BiomeStick(it.raw) }),
    TalbotsTheodolite("TALBOTS_THEODOLITE"),
    TarantulaSilk("TARANTULA_SILK"),
    TarantulaWeb("TARANTULA_WEB"),
    TastyCheese("CHEESE_FUEL"),
    TastyMithril("MITHRIL_GOURMAND", { TastyMithril(it.raw) }),
    TeleportPad("TELEPORT_PAD"),
    TeleporterPill("TELEPORTER_PILL"),
    TentacleMeat("TENTACLE_MEAT"),
    TessellatedEnderPearl("TESSELLATED_ENDER_PEARL"),
    TheArtOfPeace("THE_ART_OF_PEACE"),
    TheArtOfWar("THE_ART_OF_WAR"),
    TheCake("THE_CAKE"),
    TheSoup("THE_SOUP_PAINTING"),
    ThunderInABottle("THUNDER_IN_A_BOTTLE"),
    ThunderShards("THUNDER_SHARDS"),
    TicTacToe("TIC_TAC_TOE"),
    TierBoostCore("PET_ITEM_TIER_BOOST_DROP", { TierBoostCore(it.raw) }),
    TigerSharkTooth("TIGER_SHARK_TOOTH"),
    TightlyTiedHayBale("TIGHTLY_TIED_HAY_BALE"),
    TitanicExperienceBottle("TITANIC_EXP_BOTTLE"),
    Titanium("TITANIUM_ORE"),
    TitanoboaShed("TITANOBOA_SHED"),
    TokenOfTheCentury("TOKEN_OF_THE_CENTURY"),
    TopazPowerScroll("TOPAZ_POWER_SCROLL"),
    TornCloth("TORN_CLOTH"),
    TotemOfCorruption("TOTEM_OF_CORRUPTION", { TotemOfCorruption(it.raw) }),
    Toy("TOY"),
    TrainingDummy("TRAINING_DUMMY"),
    TransmissionTuner("TRANSMISSION_TUNER"),
    TravelScrollToArachnesSanctuary("ARACHNE_SANCTUARY_TRAVEL_SCROLL"),
    TravelScrollToDarkAuction("HUB_DA_TRAVEL_SCROLL"),
    TravelScrollToDeepCaverns("MINING_2_TRAVEL_SCROLL"),
    TravelScrollToDragonsNest("DRAGON_NEST_TRAVEL_SCROLL"),
    TravelScrollToDwarvenMines("MINING_3_TRAVEL_SCROLL"),
    TravelScrollToHowlingCave("PARK_CAVE_TRAVEL_SCROLL"),
    TravelScrollToHubCastle("HUB_CASTLE_TRAVEL_SCROLL"),
    TravelScrollToHubCrypts("HUB_CRYPTS_TRAVEL_SCROLL"),
    TravelScrollToJungleIsland("PARK_JUNGLE_TRAVEL_SCROLL"),
    TravelScrollToMuseum("MUSEUM_TRAVEL_SCROLL"),
    TravelScrollToMushroomIsland("FARMING_2_TRAVEL_SCROLL"),
    TravelScrollToSpidersDen("DANGER_1_TRAVEL_SCROLL"),
    TravelScrollToSpidersDenTopOfNest("SPIDERS_DEN_TOP_TRAVEL_SCROLL"),
    TravelScrollToTheBarn("FARMING_1_TRAVEL_SCROLL"),
    TravelScrollToTheBayou("BAYOU_TRAVEL_SCROLL"),
    TravelScrollToTheCrimsonIsle("DANGER_2_TRAVEL_SCROLL"),
    TravelScrollToTheCrystalHollows("CRYSTAL_HOLLOWS_TRAVEL_SCROLL"),
    TravelScrollToTheCrystalNucleus("CRYSTAL_NUCLEUS_TRAVEL_SCROLL"),
    TravelScrollToTheDwarvenBaseCamp("BASE_CAMP_TRAVEL_SCROLL"),
    TravelScrollToTheDwarvenForge("FORGE_TRAVEL_SCROLL"),
    TravelScrollToTheEnd("DANGER_3_TRAVEL_SCROLL"),
    TravelScrollToTheGoldMine("MINING_1_TRAVEL_SCROLL"),
    TravelScrollToTheKuudraSkull("NETHER_FORTRESS_BOSS_TRAVEL_SCROLL"),
    TravelScrollToThePark("FORAGING_1_TRAVEL_SCROLL"),
    TravelScrollToTheRift("RIFT_WIZARD_TOWER_TRAVEL_SCROLL"),
    TravelScrollToTheSmolderingTomb("SMOLDERING_CHAMBERS_TRAVEL_SCROLL"),
    TravelScrollToTheTrappersDen("TRAPPER_DEN_TRAVEL_SCROLL"),
    TravelScrollToTheVoidSepulture("VOID_SEPULTURE_TRAVEL_SCROLL"),
    TravelScrollToTheWizardTower("HUB_WIZARD_TOWER_TRAVEL_SCROLL"),
    Treasurite("TREASURITE"),
    TrickOrTreatBag("TRICK_OR_TREAT_BAG"),
    TroubledBubble("TROUBLED_BUBBLE"),
    TrueEssence("TRUE_ESSENCE"),
    TuningFork("TUNING_FORK", { TuningFork(it.raw) }),
    TuskFossil("TUSK_FOSSIL"),
    UglyFossil("UGLY_FOSSIL"),
    UltimateCarrotCandy("ULTIMATE_CARROT_CANDY"),
    UltimateCarrotCandyUpgrade("ULTIMATE_CARROT_CANDY_UPGRADE"),
    UncommonGriffinUpgradeStone("GRIFFIN_UPGRADE_STONE_UNCOMMON"),
    UndeadCatalyst("UNDEAD_CATALYST"),
    UndeadCenturyCake("EPOCH_CAKE_DARK_GREEN"),
    UnstableDragonFragment("UNSTABLE_FRAGMENT"),
    VeryCrudeGabagool("VERY_CRUDE_GABAGOOL"),
    VeryOfficialYellowRockOfLove("VERY_OFFICIAL_YELLOW_ROCK"),
    VitaminLife("VITAMIN_LIFE"),
    VolcanicRock("VOLCANIC_ROCK"),
    Volta("VOLTA"),
    VoodooDoll("VOODOO_DOLL", { VoodooDoll(it.raw) }),
    Wallet("DETECTIVE_WALLET"),
    Walnut("WALNUT"),
    WardenArt("WARDEN_ART"),
    WardenHeart("WARDEN_HEART"),
    WatcherDisc("DUNGEON_DISC_3"),
    WaterOrb("WATER_ORB"),
    WeakWolfCatalyst("WEAK_WOLF_CATALYST"),
    WeatherNode("WEATHER_NODE"),
    WeatherStick("WEATHER_STICK"),
    WebbedFossil("WEBBED_FOSSIL"),
    WeirdTuba("WEIRD_TUBA", { WeirdTuba(it.raw) }),
    WeirderTuba("WEIRDER_TUBA", { WeirdTuba(it.raw) }),
    WerewolfSkin("WEREWOLF_SKIN"),
    WetNapkin("WET_NAPKIN"),
    WetPumpkin("WET_PUMPKIN"),
    WheatCrystal("WHEAT_ISLAND_CRYSTAL"),
    WheelOfFate("WHEEL_OF_FATE"),
    WhippedMagmaCream("WHIPPED_MAGMA_CREAM"),
    WhiteGift("WHITE_GIFT"),
    WhiteGreaterBackpack("WHITE_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    WhiteLargeBackpack("WHITE_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    WhiteMediumBackpack("WHITE_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    WhiteSmallBackpack("WHITE_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    WikiJournal("WIKI_JOURNAL", { WikiJournal(it.raw) }),
    WilsonsEngineeringPlans("WILSON_ENGINEERING_PLANS"),
    WingsOfHarmonyVinyl("VINYL_WINGS_OF_HARMONY"),
    WinterCrystal("WINTER_ISLAND_CRYSTAL"),
    WinterDisc("WINTER_DISC"),
    WinterFragment("WINTER_FRAGMENT"),
    WinterIsland("WINTER_ISLAND"),
    WinterWaterOrb("WINTER_WATER_ORB"),
    WiseDragonFragment("WISE_FRAGMENT"),
    WishingCompass("WISHING_COMPASS", { WishingCompass(it.raw) }),
    WispUpgradeStoneEpic("UPGRADE_STONE_GLACIAL"),
    WispUpgradeStoneLegendary("UPGRADE_STONE_SUBZERO"),
    WispUpgradeStoneRare("UPGRADE_STONE_FROST"),
    WitherSoul("WITHER_SOUL"),
    WolfTooth("WOLF_TOOTH"),
    WoodSingularity("WOOD_SINGULARITY"),
    WoodcuttingCrystal("WOODCUTTING_CRYSTAL"),
    WormMembrane("WORM_MEMBRANE"),
    WormTheFish("WORM_THE_FISH"),
    WrigglingLarva("WRIGGLING_LARVA"),
    X("X"),
    XLargeStorage("XLARGE_ENCHANTED_CHEST"),
    XXLargeStorage("XXLARGE_ENCHANTED_CHEST"),
    Y("Y"),
    YellowGoblinEgg("GOBLIN_EGG_YELLOW"),
    YellowGreaterBackpack("YELLOW_GREATER_BACKPACK", { GreaterBackpack(it.raw) }),
    YellowLargeBackpack("YELLOW_LARGE_BACKPACK", { LargeBackpack(it.raw) }),
    YellowMediumBackpack("YELLOW_MEDIUM_BACKPACK", { MediumBackpack(it.raw) }),
    YellowRock("YELLOW_ROCK"),
    YellowSmallBackpack("YELLOW_SMALL_BACKPACK", { SmallBackpack(it.raw) }),
    Yoggie("YOGGIE"),
    YoungDragonFragment("YOUNG_FRAGMENT"),
    Z("Z"),
    ZogAnvil("ZOG_ANVIL");

    constructor(apiName: String) : this(apiName, { it })
}