package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.SkyblockItem
import net.dungeonhub.hypixel.entities.inventory.items.special.Postcard
import net.dungeonhub.hypixel.entities.inventory.items.special.VoodooDoll

enum class RiftItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    AgaricusCap("AGARICUS_CAP"),
    AgaricusCapBunch("AGARICUS_CAP_BUNCH"),
    AgaricusChumcap("AGARICUS_CHUM_CAP"),
    AgaricusSoup("AGARICUS_SOUP"),
    AgarimooTongue("AGARIMOO_TONGUE"),
    AntiMorphPotion("ANTI_MORPH_POTION"),
    BacteFragment("BACTE_FRAGMENT"),
    BarrysMontgrayPen("BARRY_PEN"),
    BerberisBlowgun("BERBERIS_BLOWGUN"),
    BerberisFuelInjector("BERBERIS_FUEL_INJECTOR"),
    Bloodbadge("BLOODBADGE"),
    BottledOdonata("BOTTLED_ODONATA"),
    CaducousExtract("CADUCOUS_EXTRACT"),
    CaducousFeeder("CADUCOUS_FEEDER"),
    CaducousLegume("CADUCOUS_LEGUME"),
    CaducousStem("CADUCOUS_STEM"),
    CaducousStemBunch("CADUCOUS_STEM_BUNCH"),
    CovenSeal("COVEN_SEAL"),
    Cruxmotion("CRUXMOTION"),
    DaeL("MIRRORED_LEASH"),
    DarkPebble("DARK_PEBBLE"),
    DeadCatDetector("DEAD_CAT_DETECTOR"),
    DeadgehogSpine("DEADGEHOG_SPINE"),
    DetectiveScanner("DETECTIVE_SCANNER"),
    Discrite("DISCRITE"),
    DoRgnihsiF("MIRRORED_FISHING_ROD"),
    DoubloonOfTheFamily("FAMILY_DOUBLOON"),
    EmmettPointer("EMMETT_POINTER"),
    EmptyChumcapBucket("EMPTY_CHUMCAP_BUCKET"),
    EmptyOdonataBottle("EMPTY_ODONATA_BOTTLE"),
    EnchantedClock("ENCHANTED_TIME_CLOCK"),
    EnchantedVampiricMelon("ENCHANTED_VAMPIRIC_MELON"),
    ExportableCarrots("EXPORTABLE_CARROTS"),
    ExtremelyRealShuriken("FAKE_SHURIKEN"),
    FreeWill("FREE_WILL"),
    FrostyCrux("FROSTY_CRUX"),
    FrozenWater("FROZEN_WATER"),
    FrozenWaterPungi("FROZEN_WATER_PUNGI"),
    GnirtS("MIRRORED_STRING"),
    GunthesizerLichen("GUNTHESIZER_LICHEN"),
    HalfEatenCarrot("HALF_EATEN_CARROT"),
    HealingMelon("HEALING_MELON"),
    Hemobomb("HEMOBOMB"),
    Hemoglass("HEMOGLASS"),
    Highlite("HIGHLITE"),
    HolyIce("HOLY_ICE"),
    Horsezooka("HORSEZOOKA"),
    HotDog("HOT_DOG"),
    JinxedVoodooDoll("VOODOO_DOLL_WILTED", { VoodooDoll(it.raw) }),
    JuicyHealingMelon("JUICY_HEALING_MELON"),
    JumpElixir("RIFT_JUMP_ELIXIR"),
    KcitS("MIRRORED_STICK"),
    KeyToInfestedHouseSoul("KEY_TO_KAT_SOUL"),
    KnalPdooWkaO("MIRRORED_WOOD"),
    LarvaHook("LARVA_HOOK"),
    LarvaSilk("LARVA_SILK"),
    LeechSupremeFragment("LEECH_SUPREME_FRAGMENT"),
    LilPad("LIL_PAD"),
    LivingMetal("LIVING_METAL"),
    LivingMetalAnchor("LIVING_METAL_ANVIL"),
    LivingMetalBootspawn("LM_EGG_BOOTS"),
    LivingMetalCapspawn("LM_EGG_CAP"),
    LivingMetalChestspawn("LM_EGG_CHEST"),
    LivingMetalHeart("METAL_HEART"),
    LivingMetalPantspawn("LM_EGG_LEGS"),
    LlabemilS("MIRRORED_SLIME_BALL"),
    LusciousHealingMelon("LUSCIOUS_HEALING_MELON"),
    McGrubbersBurger("MCGRUBBER_BURGER"),
    MetaphoricEgg("METAPHORIC_EGG"),
    MutedBark("MUTED_BARK"),
    NearlyCoherentdoRgnihsiF("NEARLY_COHERENT_ROD"),
    NearlyWholeCarrot("NEARLY_WHOLE_CARROT"),
    NullifiedMetal("NULLIFIED_METAL"),
    Obsolite("OBSOLITE"),
    PlaceableFairySoul("PLACEABLE_FAIRY_SOUL_RIFT"),
    PlumbersBucket("RIFT_BUCKET"),
    PolarvoidBook("POLARVOID_BOOK"),
    Postcard("POSTCARD", { Postcard(it.raw) }),
    PreDigestionFish("PRE_DIGESTION_FISH"),
    ProtoChicken("PROTOCHICKEN"),
    PuffCrux("PUFF_CRUX"),
    RemmaHyniT("TINY_HAMMER"),
    RemoteTimeChamberRemote("REMOTE_TIME_CHAMBER_REMOTE"),
    RiftBoat("REED_BOAT"),
    RiftwartRoots("RIFTWART_ROOTS"),
    ScribeCrux("SCRIBE_CRUX"),
    ShadowCrux("SHADOW_CRUX"),
    ShyCrux("SHAME_CRUX"),
    SilkwireStick("SILKWIRE_STICK"),
    SpeedElixir("RIFT_SPEED_ELIXIR"),
    SplatterCrux("SPLATTER_CRUX"),
    Spotlite("SPOTLITE"),
    StabilityElixir("RIFT_STABILITY_ELIXIR"),
    StrengthElixir("RIFT_STRENGTH_ELIXIR"),
    SuperLeechModifier("SUPER_LEECH_MODIFIER"),
    TightPantsFragment("TIGHT_PANTS_FRAGMENT"),
    TimeGun("TIME_GUN"),
    Timite("TIMITE"),
    TreelikeWool("BEDWARS_WOOL"),
    TurbomaxVacuumCleaner("TURBOMAX_VACUUM"),
    UbiksCube("UBIKS_CUBE"),
    UglyBootsFragment("UGLY_BOOTS_FRAGMENT"),
    UnfangedVampirePart("UNFANGED_VAMPIRE_PART"),
    VampiricMelon("VAMPIRIC_MELON"),
    VeryScientificPaper("VERY_SCIENTIFIC_PAPER"),
    VoltCrux("VOLT_CRUX"),
    WLogoFragment("S_LOGO_FRAGMENT"),
    WardingDiamathame("WAND_OF_WARDING"),
    WiltedBerberis("WILTED_BERBERIS"),
    WiltedBerberisBunch("WILTED_BERBERIS_BUNCH"),
    WizardsBreadcrumbs("WIZARD_BREADCRUMBS"),
    WoB("MIRRORED_BOW"),
    Youngite("YOUNGITE"),
    ZoopTheFish("ZOOP_THE_FISH");

    constructor(apiName: String) : this(apiName, { it })
}