package net.dungeonhub.hypixel.entities.inventory.items.id

import net.dungeonhub.hypixel.entities.inventory.items.Gear
import net.dungeonhub.hypixel.entities.inventory.items.SkyblockItem
import net.dungeonhub.hypixel.entities.inventory.items.special.Pickonimbus

enum class ToolItemId(override val apiName: String, override val itemClass: ((SkyblockItem) -> SkyblockItem)) :
    KnownSkyblockItemId {
    AdvancedGardeningAxe("ADVANCED_GARDENING_AXE"),
    AdvancedGardeningHoe("ADVANCED_GARDENING_HOE"),
    AugerRod("AUGER_ROD"),
    BandagedMithrilPickaxe("BANDAGED_MITHRIL_PICKAXE"),
    BasicGardeningAxe("BASIC_GARDENING_AXE"),
    BasicGardeningHoe("BASIC_GARDENING_HOE"),
    Binghoe("BINGHOE"),
    BingoLavaRod("BINGO_LAVA_ROD"),
    Bingonimbus2000("BINGONIMBUS_2000"),
    CactusKnife("CACTUS_KNIFE"),
    CarnivalRod("CARNIVAL_FISHING_ROD"),
    CarnivalShovel("CARNIVAL_SHOVEL"),
    ChallengingRod("CHALLENGE_ROD"),
    ChickenAxe("CHICKEN_AXE"),
    ChumRod("CHUM_ROD"),
    CocoaChopper("COCO_CHOPPER"),
    CowAxe("COW_AXE"),
    DiamondAxe("DIAMOND_AXE"),
    DiamondHoe("DIAMOND_HOE"),
    DiamondPickaxe("DIAMOND_PICKAXE"),
    DiamondShovel("DIAMOND_SPADE"),
    DirtRod("DIRT_ROD"),
    DivansDrill("DIVAN_DRILL", { Gear(it.raw) }),
    EfficientAxe("EFFICIENT_AXE"),
    EllesLavaRod("ELLES_LAVA_ROD"),
    EllesPickaxe("ELLES_PICKAXE"),
    EuclidsWheatHoeCommon("THEORETICAL_HOE_WHEAT_1"),
    EuclidsWheatHoeRare("THEORETICAL_HOE_WHEAT_3"),
    EuclidsWheatHoeUncommon("THEORETICAL_HOE_WHEAT_2"),
    FarmersRod("FARMER_ROD"),
    FishingRod("FISHING_ROD"),
    FlintShovel("FLINT_SHOVEL"),
    FracturedMithrilPickaxe("FRACTURED_MITHRIL_PICKAXE"),
    FungiCutter("FUNGI_CUTTER"),
    GameFixer("GAME_FIXER"),
    GaussCarrotHoeCommon("THEORETICAL_HOE_CARROT_1"),
    GaussCarrotHoeRare("THEORETICAL_HOE_CARROT_3"),
    GaussCarrotHoeUncommon("THEORETICAL_HOE_CARROT_2"),
    GemstoneDrillLT522("GEMSTONE_DRILL_2", { Gear(it.raw) }),
    GemstoneGauntlet("GEMSTONE_GAUNTLET"),
    GiantFishingRod("GIANT_FISHING_ROD"),
    GoldenAxe("GOLD_AXE"),
    GoldenHoe("GOLD_HOE"),
    GoldenPickaxe("GOLD_PICKAXE"),
    GoldenShovel("GOLD_SPADE"),
    HellfireRod("HELLFIRE_ROD"),
    HoeOfGreatTilling("HOE_OF_GREAT_TILLING"),
    HoeOfGreaterTilling("HOE_OF_GREATER_TILLING"),
    HoeOfGreatestTilling("HOE_OF_GREATEST_TILLING"),
    HoeOfNoTilling("HOE_OF_NO_TILLING"),
    IceRod("ICE_ROD"),
    InfernoRod("INFERNO_ROD", { Gear(it.raw) }),
    InfiniVacuum("INFINI_VACUUM"),
    InfiniVacuumHooverius("INFINI_VACUUM_HOOVERIUS"),
    IronAxe("IRON_AXE"),
    IronHoe("IRON_HOE"),
    IronPickaxe("IRON_PICKAXE"),
    IronShovel("IRON_SPADE"),
    JasperDrillX("GEMSTONE_DRILL_4", { Gear(it.raw) }),
    JungleAxe("JUNGLE_AXE"),
    JunglePickaxe("JUNGLE_PICKAXE"),
    LapisPickaxe("LAPIS_PICKAXE"),
    MagmaRod("MAGMA_ROD"),
    MathematicalHoeBlueprint("THEORETICAL_HOE"),
    MelonDicer("MELON_DICER"),
    MelonDicer2("MELON_DICER_2"),
    MelonDicer3("MELON_DICER_3"),
    MithrilDrillSXR226("MITHRIL_DRILL_1", { Gear(it.raw) }),
    MithrilDrillSXR326("MITHRIL_DRILL_2", { Gear(it.raw) }),
    MithrilPickaxe("MITHRIL_PICKAXE"),
    MushroomCowAxe("MUSHROOM_COW_AXE"),
    NewtonNetherWartsHoeCommon("THEORETICAL_HOE_WARTS_1"),
    NewtonNetherWartsHoeRare("THEORETICAL_HOE_WARTS_3"),
    NewtonNetherWartsHoeUncommon("THEORETICAL_HOE_WARTS_2"),
    Pickonimbus2000("PICKONIMBUS", { Pickonimbus(it.raw) }),
    PigAxe("PIG_AXE"),
    PioneerPickaxe("ALPHA_PICK"),
    PolishedTitaniumPickaxe("REFINED_TITANIUM_PICKAXE"),
    PolishedTopazRod("POLISHED_TOPAZ_ROD", { Gear(it.raw) }),
    PrismarineRod("PRISMARINE_ROD"),
    PromisingAxe("PROMISING_AXE"),
    PromisingHoe("PROMISING_HOE"),
    PromisingPickaxe("PROMISING_PICKAXE"),
    PromisingShovel("PROMISING_SPADE"),
    PumpkinDicer("PUMPKIN_DICER"),
    PumpkinDicer2("PUMPKIN_DICER_2"),
    PumpkinDicer3("PUMPKIN_DICER_3"),
    PythagoreanPotatoHoeCommon("THEORETICAL_HOE_POTATO_1"),
    PythagoreanPotatoHoeRare("THEORETICAL_HOE_POTATO_3"),
    PythagoreanPotatoHoeUncommon("THEORETICAL_HOE_POTATO_2"),
    RabbitAxe("RABBIT_AXE"),
    RefinedMithrilPickaxe("REFINED_MITHRIL_PICKAXE"),
    RodOfChampions("CHAMP_ROD"),
    RodOfLegends("LEGEND_ROD", { Gear(it.raw) }),
    RodOfTheSea("ROD_OF_THE_SEA", { Gear(it.raw) }),
    RookieAxe("ROOKIE_AXE"),
    RookieHoe("ROOKIE_HOE"),
    RookiePickaxe("ROOKIE_PICKAXE"),
    RubyDrillTX15("GEMSTONE_DRILL_1", { Gear(it.raw) }),
    RustyTitaniumPickaxe("RUSTY_TITANIUM_PICKAXE"),
    SculptorsAxe("SCULPTORS_AXE"),
    SheepAxe("SHEEP_AXE"),
    SkyMartHyperVacuum("SKYMART_HYPER_VACUUM"),
    SkyMartTurboVacuum("SKYMART_TURBO_VACUUM"),
    SkyMartVacuum("SKYMART_VACUUM"),
    SpeedsterRod("SPEEDSTER_ROD"),
    SpongeRod("SPONGE_ROD"),
    SporeHarvester("SPORE_HARVESTER"),
    StarterLavaRod("STARTER_LAVA_ROD"),
    StoneAxe("STONE_AXE"),
    StoneHoe("STONE_HOE"),
    StonePickaxe("STONE_PICKAXE"),
    StoneShovel("STONE_SPADE"),
    Stonk("STONK_PICKAXE", { Gear(it.raw) }),
    SweetAxe("SWEET_AXE"),
    ThornleafScythe("THORNLEAF_SCYTHE"),
    TitaniumDrillDRX355("TITANIUM_DRILL_1", { Gear(it.raw) }),
    TitaniumDrillDRX455("TITANIUM_DRILL_2", { Gear(it.raw) }),
    TitaniumDrillDRX555("TITANIUM_DRILL_3", { Gear(it.raw) }),
    TitaniumDrillDRX655("TITANIUM_DRILL_4", { Gear(it.raw) }),
    TitaniumPickaxe("TITANIUM_PICKAXE"),
    TopazDrillKGR12("GEMSTONE_DRILL_3", { Gear(it.raw) }),
    Treecapitator("TREECAPITATOR_AXE", { Gear(it.raw) }),
    TuringSugarCaneHoeCommon("THEORETICAL_HOE_CANE_1"),
    TuringSugarCaneHoeRare("THEORETICAL_HOE_CANE_3"),
    TuringSugarCaneHoeUncommon("THEORETICAL_HOE_CANE_2"),
    WinterRod("WINTER_ROD"),
    WoodenAxe("WOOD_AXE"),
    WoodenHoe("WOOD_HOE"),
    WoodenPickaxe("WOOD_PICKAXE"),
    WoodenShovel("WOOD_SPADE"),
    YetiRod("YETI_ROD"),
    ZombiePickaxe("ZOMBIE_PICKAXE");

    constructor(apiName: String) : this(apiName, { it })
}