name: Update Bingo Event Data

on:
  schedule:
    - cron: "0 10 3 * *"

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Fetch the latest Bingo Data
        run: kotlin .github/scripts/update-bingo.main.kts

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m')" >> $GITHUB_ENV

      - name: Switch branch
        run: git checkout -b bingo-${{ env.NOW }}

      - name: Copy files, commit and push

        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions-user@users.noreply.github.com"

          git add src
          git commit -am "Added this months Bingo data"
          git push origin bingo-${{ env.NOW }}

      - name: Create Pull Request
        run: gh pr create -B main -H bingo-${{ env.NOW }} --title 'Merge bingo-${{ env.NOW }} into main' --body 'Created automatically by a GitHub Actions workflow'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
